// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_activity.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAgentActivity = `-- name: CountAgentActivity :one

SELECT COUNT(*)::int FROM (
    SELECT uh.id
    FROM update_history uh
    WHERE uh.host_id = $1::text
      AND ($2::text = '' OR $2::text = 'in')
      AND (COALESCE(cardinality($3::text[]), 0) = 0 OR uh.report_type = ANY($3::text[]))
      AND (COALESCE(cardinality($4::text[]), 0) = 0 OR uh.status = ANY($4::text[]))
      AND ($5::timestamp IS NULL OR uh.timestamp >= $5::timestamp)
      AND ($6::text = '' OR (uh.error_message IS NOT NULL AND uh.error_message ILIKE '%' || $6::text || '%'))

    UNION ALL

    SELECT jh.id
    FROM job_history jh
    WHERE jh.host_id = $1::text
      AND ($2::text = '' OR $2::text = 'out')
      AND (COALESCE(cardinality($3::text[]), 0) = 0 OR jh.job_name = ANY($3::text[]))
      AND (COALESCE(cardinality($4::text[]), 0) = 0 OR jh.status = ANY($4::text[]))
      AND ($5::timestamp IS NULL OR jh.created_at >= $5::timestamp)
      AND ($6::text = ''
           OR (jh.error_message IS NOT NULL AND jh.error_message ILIKE '%' || $6::text || '%')
           OR (jh.output IS NOT NULL AND jh.output::text ILIKE '%' || $6::text || '%'))
) merged
`

type CountAgentActivityParams struct {
	HostID    string           `json:"host_id"`
	Direction string           `json:"direction"`
	Types     []string         `json:"types"`
	Statuses  []string         `json:"statuses"`
	SinceTs   pgtype.Timestamp `json:"since_ts"`
	Search    string           `json:"search"`
}

// Agent Activity feed. Returns the merged time-ordered stream of agent comm
// rows for a given host: inbound reports (update_history) AND outbound jobs
// (job_history). The two source tables have different shapes; this query
// normalises them to one column set and discriminates via the `kind` column
// ('report' or 'job'). Caller passes the host_id, optional direction / type /
// status filters, optional search string (ILIKE on error_message and job
// output), optional time-range / limit / offset for pagination.
//
// CountAgentActivity returns the filtered total separately so stale/deep-linked
// pages beyond the end can still report the real total.
//
// The since_ts arg uses sqlc.narg (nullable) on both branches; pgx encodes
// pgtype.Timestamp{Valid:false} as SQL NULL, which the IS NULL guard catches.
func (q *Queries) CountAgentActivity(ctx context.Context, arg CountAgentActivityParams) (int32, error) {
	row := q.db.QueryRow(ctx, countAgentActivity,
		arg.HostID,
		arg.Direction,
		arg.Types,
		arg.Statuses,
		arg.SinceTs,
		arg.Search,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteOldUpdateHistoryBatch = `-- name: DeleteOldUpdateHistoryBatch :execrows
DELETE FROM update_history
WHERE id IN (
    SELECT id FROM update_history
    WHERE timestamp < (NOW() - ($1::int * INTERVAL '1 day'))
    LIMIT $2::int
)
`

type DeleteOldUpdateHistoryBatchParams struct {
	RetentionDays int32 `json:"retention_days"`
	BatchLimit    int32 `json:"batch_limit"`
}

// Retention sweep target, deliberately batched. Steady state deletes a day's
// worth of rows, but the FIRST sweep after upgrading an existing install has
// to clear the entire pre-2.0.3 update_history backlog, which was never pruned
// before — millions of rows on a multi-year install. An unbounded single-
// statement DELETE would hold one transaction (and its locks / WAL / dead
// tuples) open for the whole thing. The worker calls this in a loop until it
// returns 0, so each transaction stays small and interruptible.
//
// Returns the number of rows deleted so the worker can both log the volume and
// decide whether to keep looping.
func (q *Queries) DeleteOldUpdateHistoryBatch(ctx context.Context, arg DeleteOldUpdateHistoryBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldUpdateHistoryBatch, arg.RetentionDays, arg.BatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAgentActivity = `-- name: ListAgentActivity :many
SELECT kind, row_id, occurred_at, type, job_id, job_name, queue_name, sections_sent, sections_unchanged, payload_size_kb, server_processing_ms, agent_execution_ms, attempt_number, status, error_message, packages_count, security_count, completed_at, output FROM (
    SELECT
        'report'::text AS kind,
        uh.id AS row_id,
        uh.timestamp AS occurred_at,
        uh.report_type AS type,
        ''::text AS job_id,
        ''::text AS job_name,
        ''::text AS queue_name,
        uh.sections_sent AS sections_sent,
        uh.sections_unchanged AS sections_unchanged,
        uh.payload_size_kb AS payload_size_kb,
        uh.execution_time AS server_processing_ms,
        uh.agent_execution_ms AS agent_execution_ms,
        0::int AS attempt_number,
        uh.status AS status,
        uh.error_message AS error_message,
        uh.packages_count AS packages_count,
        uh.security_count AS security_count,
        NULL::timestamp AS completed_at,
        ''::text AS output
    FROM update_history uh
    WHERE uh.host_id = $1::text
      AND ($2::text = '' OR $2::text = 'in')
      AND (COALESCE(cardinality($3::text[]), 0) = 0 OR uh.report_type = ANY($3::text[]))
      AND (COALESCE(cardinality($4::text[]), 0) = 0 OR uh.status = ANY($4::text[]))
      AND ($5::timestamp IS NULL OR uh.timestamp >= $5::timestamp)
      AND ($6::text = '' OR (uh.error_message IS NOT NULL AND uh.error_message ILIKE '%' || $6::text || '%'))

    UNION ALL

    SELECT
        'job'::text AS kind,
        jh.id AS row_id,
        jh.created_at AS occurred_at,
        jh.job_name AS type,
        jh.job_id AS job_id,
        jh.job_name AS job_name,
        jh.queue_name AS queue_name,
        ARRAY[]::text[] AS sections_sent,
        ARRAY[]::text[] AS sections_unchanged,
        NULL::double precision AS payload_size_kb,
        CASE
            WHEN jh.completed_at IS NOT NULL
            THEN EXTRACT(EPOCH FROM (jh.completed_at - jh.created_at)) * 1000
            ELSE NULL
        END AS server_processing_ms,
        NULL::int AS agent_execution_ms,
        jh.attempt_number AS attempt_number,
        jh.status AS status,
        jh.error_message AS error_message,
        -- packages_count / security_count are NOT NULL on update_history,
        -- so the report branch dictates a NOT NULL int32 in the generated
        -- row struct. Returning 0 here (instead of NULL) keeps pgx scan
        -- happy; the store layer only surfaces these for kind='report' so
        -- the wire response is unaffected for jobs.
        0::int AS packages_count,
        0::int AS security_count,
        jh.completed_at AS completed_at,
        COALESCE(jh.output::text, '') AS output
    FROM job_history jh
    WHERE jh.host_id = $1::text
      AND ($2::text = '' OR $2::text = 'out')
      AND (COALESCE(cardinality($3::text[]), 0) = 0 OR jh.job_name = ANY($3::text[]))
      AND (COALESCE(cardinality($4::text[]), 0) = 0 OR jh.status = ANY($4::text[]))
      AND ($5::timestamp IS NULL OR jh.created_at >= $5::timestamp)
      AND ($6::text = ''
           OR (jh.error_message IS NOT NULL AND jh.error_message ILIKE '%' || $6::text || '%')
           OR (jh.output IS NOT NULL AND jh.output::text ILIKE '%' || $6::text || '%'))
) merged
ORDER BY occurred_at DESC
LIMIT $8::int
OFFSET $7::int
`

type ListAgentActivityParams struct {
	HostID    string           `json:"host_id"`
	Direction string           `json:"direction"`
	Types     []string         `json:"types"`
	Statuses  []string         `json:"statuses"`
	SinceTs   pgtype.Timestamp `json:"since_ts"`
	Search    string           `json:"search"`
	RowOffset int32            `json:"row_offset"`
	RowLimit  int32            `json:"row_limit"`
}

type ListAgentActivityRow struct {
	Kind               string           `json:"kind"`
	RowID              string           `json:"row_id"`
	OccurredAt         pgtype.Timestamp `json:"occurred_at"`
	Type               string           `json:"type"`
	JobID              string           `json:"job_id"`
	JobName            string           `json:"job_name"`
	QueueName          string           `json:"queue_name"`
	SectionsSent       []string         `json:"sections_sent"`
	SectionsUnchanged  []string         `json:"sections_unchanged"`
	PayloadSizeKb      *float64         `json:"payload_size_kb"`
	ServerProcessingMs *float64         `json:"server_processing_ms"`
	AgentExecutionMs   *int32           `json:"agent_execution_ms"`
	AttemptNumber      int32            `json:"attempt_number"`
	Status             string           `json:"status"`
	ErrorMessage       *string          `json:"error_message"`
	PackagesCount      int32            `json:"packages_count"`
	SecurityCount      int32            `json:"security_count"`
	CompletedAt        pgtype.Timestamp `json:"completed_at"`
	Output             string           `json:"output"`
}

func (q *Queries) ListAgentActivity(ctx context.Context, arg ListAgentActivityParams) ([]ListAgentActivityRow, error) {
	rows, err := q.db.Query(ctx, listAgentActivity,
		arg.HostID,
		arg.Direction,
		arg.Types,
		arg.Statuses,
		arg.SinceTs,
		arg.Search,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentActivityRow
	for rows.Next() {
		var i ListAgentActivityRow
		if err := rows.Scan(
			&i.Kind,
			&i.RowID,
			&i.OccurredAt,
			&i.Type,
			&i.JobID,
			&i.JobName,
			&i.QueueName,
			&i.SectionsSent,
			&i.SectionsUnchanged,
			&i.PayloadSizeKb,
			&i.ServerProcessingMs,
			&i.AgentExecutionMs,
			&i.AttemptNumber,
			&i.Status,
			&i.ErrorMessage,
			&i.PackagesCount,
			&i.SecurityCount,
			&i.CompletedAt,
			&i.Output,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
