// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alert_history.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAlertHistory = `-- name: InsertAlertHistory :one
INSERT INTO alert_history (id, alert_id, user_id, action, metadata, created_at)
VALUES ($1, $2, $3, $4, COALESCE($5, '{}'::jsonb), NOW())
RETURNING id, alert_id, user_id, action, metadata, created_at
`

type InsertAlertHistoryParams struct {
	ID      string      `json:"id"`
	AlertID string      `json:"alert_id"`
	UserID  *string     `json:"user_id"`
	Action  string      `json:"action"`
	Column5 interface{} `json:"column_5"`
}

func (q *Queries) InsertAlertHistory(ctx context.Context, arg InsertAlertHistoryParams) (AlertHistory, error) {
	row := q.db.QueryRow(ctx, insertAlertHistory,
		arg.ID,
		arg.AlertID,
		arg.UserID,
		arg.Action,
		arg.Column5,
	)
	var i AlertHistory
	err := row.Scan(
		&i.ID,
		&i.AlertID,
		&i.UserID,
		&i.Action,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listAlertHistoryByAlertID = `-- name: ListAlertHistoryByAlertID :many
SELECT
    ah.id,
    ah.alert_id,
    ah.user_id,
    ah.action,
    ah.metadata,
    ah.created_at,
    u.id AS user_id_val,
    u.username,
    u.email,
    u.first_name,
    u.last_name
FROM alert_history ah
LEFT JOIN users u ON ah.user_id = u.id
WHERE ah.alert_id = $1
ORDER BY ah.created_at DESC
`

type ListAlertHistoryByAlertIDRow struct {
	ID        string           `json:"id"`
	AlertID   string           `json:"alert_id"`
	UserID    *string          `json:"user_id"`
	Action    string           `json:"action"`
	Metadata  []byte           `json:"metadata"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UserIDVal *string          `json:"user_id_val"`
	Username  *string          `json:"username"`
	Email     *string          `json:"email"`
	FirstName *string          `json:"first_name"`
	LastName  *string          `json:"last_name"`
}

func (q *Queries) ListAlertHistoryByAlertID(ctx context.Context, alertID string) ([]ListAlertHistoryByAlertIDRow, error) {
	rows, err := q.db.Query(ctx, listAlertHistoryByAlertID, alertID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlertHistoryByAlertIDRow
	for rows.Next() {
		var i ListAlertHistoryByAlertIDRow
		if err := rows.Scan(
			&i.ID,
			&i.AlertID,
			&i.UserID,
			&i.Action,
			&i.Metadata,
			&i.CreatedAt,
			&i.UserIDVal,
			&i.Username,
			&i.Email,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
