// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alerts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAlert = `-- name: CreateAlert :one
INSERT INTO alerts (id, type, severity, title, message, metadata, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, COALESCE($6::jsonb, '{}'::jsonb), COALESCE($7, true), NOW(), NOW())
RETURNING id, type, severity, title, message, metadata, is_active, assigned_to_user_id, resolved_at, resolved_by_user_id, created_at, updated_at
`

type CreateAlertParams struct {
	ID       string      `json:"id"`
	Type     string      `json:"type"`
	Severity string      `json:"severity"`
	Title    string      `json:"title"`
	Message  string      `json:"message"`
	Column6  []byte      `json:"column_6"`
	Column7  interface{} `json:"column_7"`
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, createAlert,
		arg.ID,
		arg.Type,
		arg.Severity,
		arg.Title,
		arg.Message,
		arg.Column6,
		arg.Column7,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Severity,
		&i.Title,
		&i.Message,
		&i.Metadata,
		&i.IsActive,
		&i.AssignedToUserID,
		&i.ResolvedAt,
		&i.ResolvedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAlert = `-- name: DeleteAlert :exec
DELETE FROM alerts WHERE id = $1
`

func (q *Queries) DeleteAlert(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteAlert, id)
	return err
}

const deleteAlertsByIDs = `-- name: DeleteAlertsByIDs :exec
DELETE FROM alerts WHERE id = ANY($1::text[])
`

func (q *Queries) DeleteAlertsByIDs(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteAlertsByIDs, dollar_1)
	return err
}

const getAlertByID = `-- name: GetAlertByID :one
SELECT
    a.id,
    a.type,
    a.severity,
    a.title,
    a.message,
    a.metadata,
    a.is_active,
    a.assigned_to_user_id,
    a.resolved_at,
    a.resolved_by_user_id,
    a.created_at,
    a.updated_at,
    u.id AS assigned_user_id,
    u.username AS assigned_username,
    u.email AS assigned_email,
    u.first_name AS assigned_first_name,
    u.last_name AS assigned_last_name
FROM alerts a
LEFT JOIN users u ON a.assigned_to_user_id = u.id
WHERE a.id = $1
`

type GetAlertByIDRow struct {
	ID                string           `json:"id"`
	Type              string           `json:"type"`
	Severity          string           `json:"severity"`
	Title             string           `json:"title"`
	Message           string           `json:"message"`
	Metadata          []byte           `json:"metadata"`
	IsActive          bool             `json:"is_active"`
	AssignedToUserID  *string          `json:"assigned_to_user_id"`
	ResolvedAt        pgtype.Timestamp `json:"resolved_at"`
	ResolvedByUserID  *string          `json:"resolved_by_user_id"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	AssignedUserID    *string          `json:"assigned_user_id"`
	AssignedUsername  *string          `json:"assigned_username"`
	AssignedEmail     *string          `json:"assigned_email"`
	AssignedFirstName *string          `json:"assigned_first_name"`
	AssignedLastName  *string          `json:"assigned_last_name"`
}

func (q *Queries) GetAlertByID(ctx context.Context, id string) (GetAlertByIDRow, error) {
	row := q.db.QueryRow(ctx, getAlertByID, id)
	var i GetAlertByIDRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Severity,
		&i.Title,
		&i.Message,
		&i.Metadata,
		&i.IsActive,
		&i.AssignedToUserID,
		&i.ResolvedAt,
		&i.ResolvedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssignedUserID,
		&i.AssignedUsername,
		&i.AssignedEmail,
		&i.AssignedFirstName,
		&i.AssignedLastName,
	)
	return i, err
}

const getAlertStatsBySeverity = `-- name: GetAlertStatsBySeverity :many
SELECT severity, COUNT(*)::int AS count
FROM alerts
WHERE is_active = true AND resolved_at IS NULL
GROUP BY severity
`

type GetAlertStatsBySeverityRow struct {
	Severity string `json:"severity"`
	Count    int32  `json:"count"`
}

func (q *Queries) GetAlertStatsBySeverity(ctx context.Context) ([]GetAlertStatsBySeverityRow, error) {
	rows, err := q.db.Query(ctx, getAlertStatsBySeverity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAlertStatsBySeverityRow
	for rows.Next() {
		var i GetAlertStatsBySeverityRow
		if err := rows.Scan(&i.Severity, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlertsForCleanup = `-- name: GetAlertsForCleanup :many
SELECT id, type, created_at
FROM alerts
WHERE type = $1
  AND created_at < $2
  AND is_active = false
  AND (NOT $3 OR resolved_at IS NOT NULL)
`

type GetAlertsForCleanupParams struct {
	Type      string           `json:"type"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	Column3   interface{}      `json:"column_3"`
}

type GetAlertsForCleanupRow struct {
	ID        string           `json:"id"`
	Type      string           `json:"type"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetAlertsForCleanup(ctx context.Context, arg GetAlertsForCleanupParams) ([]GetAlertsForCleanupRow, error) {
	rows, err := q.db.Query(ctx, getAlertsForCleanup, arg.Type, arg.CreatedAt, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAlertsForCleanupRow
	for rows.Next() {
		var i GetAlertsForCleanupRow
		if err := rows.Scan(&i.ID, &i.Type, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlertsToAutoResolve = `-- name: GetAlertsToAutoResolve :many
SELECT id, type, created_at FROM alerts
WHERE type = $1 AND is_active = true AND created_at < $2
`

type GetAlertsToAutoResolveParams struct {
	Type      string           `json:"type"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type GetAlertsToAutoResolveRow struct {
	ID        string           `json:"id"`
	Type      string           `json:"type"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetAlertsToAutoResolve(ctx context.Context, arg GetAlertsToAutoResolveParams) ([]GetAlertsToAutoResolveRow, error) {
	rows, err := q.db.Query(ctx, getAlertsToAutoResolve, arg.Type, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAlertsToAutoResolveRow
	for rows.Next() {
		var i GetAlertsToAutoResolveRow
		if err := rows.Scan(&i.ID, &i.Type, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveAlertsByType = `-- name: ListActiveAlertsByType :many
SELECT id, type, metadata FROM alerts WHERE type = $1 AND is_active = true
`

type ListActiveAlertsByTypeRow struct {
	ID       string `json:"id"`
	Type     string `json:"type"`
	Metadata []byte `json:"metadata"`
}

func (q *Queries) ListActiveAlertsByType(ctx context.Context, type_ string) ([]ListActiveAlertsByTypeRow, error) {
	rows, err := q.db.Query(ctx, listActiveAlertsByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveAlertsByTypeRow
	for rows.Next() {
		var i ListActiveAlertsByTypeRow
		if err := rows.Scan(&i.ID, &i.Type, &i.Metadata); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlert = `-- name: UpdateAlert :exec
UPDATE alerts
SET updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateAlert(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateAlert, id)
	return err
}

const updateAlertAssignment = `-- name: UpdateAlertAssignment :exec
UPDATE alerts
SET assigned_to_user_id = $2, is_active = true, resolved_at = NULL, resolved_by_user_id = NULL, updated_at = NOW()
WHERE id = $1
`

type UpdateAlertAssignmentParams struct {
	ID               string  `json:"id"`
	AssignedToUserID *string `json:"assigned_to_user_id"`
}

func (q *Queries) UpdateAlertAssignment(ctx context.Context, arg UpdateAlertAssignmentParams) error {
	_, err := q.db.Exec(ctx, updateAlertAssignment, arg.ID, arg.AssignedToUserID)
	return err
}

const updateAlertResolved = `-- name: UpdateAlertResolved :exec
UPDATE alerts
SET is_active = $2, resolved_at = $3, resolved_by_user_id = $4, updated_at = NOW()
WHERE id = $1
`

type UpdateAlertResolvedParams struct {
	ID               string           `json:"id"`
	IsActive         bool             `json:"is_active"`
	ResolvedAt       pgtype.Timestamp `json:"resolved_at"`
	ResolvedByUserID *string          `json:"resolved_by_user_id"`
}

func (q *Queries) UpdateAlertResolved(ctx context.Context, arg UpdateAlertResolvedParams) error {
	_, err := q.db.Exec(ctx, updateAlertResolved,
		arg.ID,
		arg.IsActive,
		arg.ResolvedAt,
		arg.ResolvedByUserID,
	)
	return err
}

const updateAlertUnassign = `-- name: UpdateAlertUnassign :exec
UPDATE alerts
SET assigned_to_user_id = NULL, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateAlertUnassign(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateAlertUnassign, id)
	return err
}

const updateAlertUnresolve = `-- name: UpdateAlertUnresolve :exec
UPDATE alerts
SET is_active = true, resolved_at = NULL, resolved_by_user_id = NULL, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateAlertUnresolve(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateAlertUnresolve, id)
	return err
}
