// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: compliance_scans.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countComplianceScansByHost = `-- name: CountComplianceScansByHost :one
SELECT COUNT(*) FROM compliance_scans WHERE host_id = $1
`

func (q *Queries) CountComplianceScansByHost(ctx context.Context, hostID string) (int64, error) {
	row := q.db.QueryRow(ctx, countComplianceScansByHost, hostID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countComplianceScansHistory = `-- name: CountComplianceScansHistory :one
SELECT COUNT(*)
FROM compliance_scans cs
JOIN hosts h ON h.id = cs.host_id
JOIN compliance_profiles cp ON cp.id = cs.profile_id
WHERE ($1::text IS NULL OR cs.status = $1)
  AND ($2::text IS NULL OR cs.host_id = $2)
  AND ($3::text IS NULL OR cp.type = $3)
  AND ($4::text IS NULL OR h.friendly_name ILIKE '%' || $4 || '%' OR h.hostname ILIKE '%' || $4 || '%' OR cp.name ILIKE '%' || $4 || '%')
`

type CountComplianceScansHistoryParams struct {
	Status      *string `json:"status"`
	HostID      *string `json:"host_id"`
	ProfileType *string `json:"profile_type"`
	Search      *string `json:"search"`
}

func (q *Queries) CountComplianceScansHistory(ctx context.Context, arg CountComplianceScansHistoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countComplianceScansHistory,
		arg.Status,
		arg.HostID,
		arg.ProfileType,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComplianceScan = `-- name: CreateComplianceScan :one
INSERT INTO compliance_scans (
    id, host_id, profile_id, started_at, completed_at, status,
    total_rules, passed, failed, warnings, skipped, not_applicable,
    score, error_message, raw_output, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, NOW(), NOW())
RETURNING id, host_id, profile_id, started_at, completed_at, status,
          total_rules, passed, failed, warnings, skipped, not_applicable,
          score, error_message, raw_output, created_at, updated_at
`

type CreateComplianceScanParams struct {
	ID            string           `json:"id"`
	HostID        string           `json:"host_id"`
	ProfileID     string           `json:"profile_id"`
	StartedAt     pgtype.Timestamp `json:"started_at"`
	CompletedAt   pgtype.Timestamp `json:"completed_at"`
	Status        string           `json:"status"`
	TotalRules    int32            `json:"total_rules"`
	Passed        int32            `json:"passed"`
	Failed        int32            `json:"failed"`
	Warnings      int32            `json:"warnings"`
	Skipped       int32            `json:"skipped"`
	NotApplicable int32            `json:"not_applicable"`
	Score         *float64         `json:"score"`
	ErrorMessage  *string          `json:"error_message"`
	RawOutput     *string          `json:"raw_output"`
}

func (q *Queries) CreateComplianceScan(ctx context.Context, arg CreateComplianceScanParams) (ComplianceScan, error) {
	row := q.db.QueryRow(ctx, createComplianceScan,
		arg.ID,
		arg.HostID,
		arg.ProfileID,
		arg.StartedAt,
		arg.CompletedAt,
		arg.Status,
		arg.TotalRules,
		arg.Passed,
		arg.Failed,
		arg.Warnings,
		arg.Skipped,
		arg.NotApplicable,
		arg.Score,
		arg.ErrorMessage,
		arg.RawOutput,
	)
	var i ComplianceScan
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.ProfileID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Status,
		&i.TotalRules,
		&i.Passed,
		&i.Failed,
		&i.Warnings,
		&i.Skipped,
		&i.NotApplicable,
		&i.Score,
		&i.ErrorMessage,
		&i.RawOutput,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePreviousCompletedScansByHostAndProfile = `-- name: DeletePreviousCompletedScansByHostAndProfile :exec
DELETE FROM compliance_scans
WHERE host_id = $1 AND profile_id = $2 AND status = 'completed'
`

type DeletePreviousCompletedScansByHostAndProfileParams struct {
	HostID    string `json:"host_id"`
	ProfileID string `json:"profile_id"`
}

func (q *Queries) DeletePreviousCompletedScansByHostAndProfile(ctx context.Context, arg DeletePreviousCompletedScansByHostAndProfileParams) error {
	_, err := q.db.Exec(ctx, deletePreviousCompletedScansByHostAndProfile, arg.HostID, arg.ProfileID)
	return err
}

const deleteRunningComplianceScansByHost = `-- name: DeleteRunningComplianceScansByHost :exec
DELETE FROM compliance_scans
WHERE host_id = $1 AND status = 'running'
`

func (q *Queries) DeleteRunningComplianceScansByHost(ctx context.Context, hostID string) error {
	_, err := q.db.Exec(ctx, deleteRunningComplianceScansByHost, hostID)
	return err
}

const getComplianceScanByID = `-- name: GetComplianceScanByID :one
SELECT cs.id, cs.host_id, cs.profile_id, cs.started_at, cs.completed_at, cs.status,
       cs.total_rules, cs.passed, cs.failed, cs.warnings, cs.skipped, cs.not_applicable,
       cs.score, cs.error_message, cs.raw_output, cs.created_at, cs.updated_at,
       cp.name as profile_name, cp.type as profile_type
FROM compliance_scans cs
JOIN compliance_profiles cp ON cp.id = cs.profile_id
WHERE cs.id = $1
`

type GetComplianceScanByIDRow struct {
	ID            string           `json:"id"`
	HostID        string           `json:"host_id"`
	ProfileID     string           `json:"profile_id"`
	StartedAt     pgtype.Timestamp `json:"started_at"`
	CompletedAt   pgtype.Timestamp `json:"completed_at"`
	Status        string           `json:"status"`
	TotalRules    int32            `json:"total_rules"`
	Passed        int32            `json:"passed"`
	Failed        int32            `json:"failed"`
	Warnings      int32            `json:"warnings"`
	Skipped       int32            `json:"skipped"`
	NotApplicable int32            `json:"not_applicable"`
	Score         *float64         `json:"score"`
	ErrorMessage  *string          `json:"error_message"`
	RawOutput     *string          `json:"raw_output"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	ProfileName   string           `json:"profile_name"`
	ProfileType   string           `json:"profile_type"`
}

func (q *Queries) GetComplianceScanByID(ctx context.Context, id string) (GetComplianceScanByIDRow, error) {
	row := q.db.QueryRow(ctx, getComplianceScanByID, id)
	var i GetComplianceScanByIDRow
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.ProfileID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Status,
		&i.TotalRules,
		&i.Passed,
		&i.Failed,
		&i.Warnings,
		&i.Skipped,
		&i.NotApplicable,
		&i.Score,
		&i.ErrorMessage,
		&i.RawOutput,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfileName,
		&i.ProfileType,
	)
	return i, err
}

const getComplianceScansForTrends = `-- name: GetComplianceScansForTrends :many
SELECT cs.completed_at, cs.score, cp.name as profile_name, cp.type as profile_type
FROM compliance_scans cs
JOIN compliance_profiles cp ON cp.id = cs.profile_id
WHERE cs.host_id = $1 AND cs.status = 'completed' AND cs.completed_at >= $2
ORDER BY cs.completed_at ASC
`

type GetComplianceScansForTrendsParams struct {
	HostID      string           `json:"host_id"`
	CompletedAt pgtype.Timestamp `json:"completed_at"`
}

type GetComplianceScansForTrendsRow struct {
	CompletedAt pgtype.Timestamp `json:"completed_at"`
	Score       *float64         `json:"score"`
	ProfileName string           `json:"profile_name"`
	ProfileType string           `json:"profile_type"`
}

func (q *Queries) GetComplianceScansForTrends(ctx context.Context, arg GetComplianceScansForTrendsParams) ([]GetComplianceScansForTrendsRow, error) {
	rows, err := q.db.Query(ctx, getComplianceScansForTrends, arg.HostID, arg.CompletedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetComplianceScansForTrendsRow
	for rows.Next() {
		var i GetComplianceScansForTrendsRow
		if err := rows.Scan(
			&i.CompletedAt,
			&i.Score,
			&i.ProfileName,
			&i.ProfileType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestCompletedScans = `-- name: GetLatestCompletedScans :many
SELECT cs.id, cs.host_id, cs.profile_id, cs.completed_at, cs.passed, cs.failed,
       cs.warnings, cs.skipped, cs.not_applicable, cs.score, cs.total_rules,
       cp.name as profile_name, cp.type as profile_type
FROM (
    SELECT DISTINCT ON (host_id, profile_id)
        id, host_id, profile_id, completed_at, passed, failed, warnings,
        skipped, not_applicable, score, total_rules
    FROM compliance_scans
    WHERE status = 'completed'
    ORDER BY host_id, profile_id, completed_at DESC
) cs
JOIN compliance_profiles cp ON cp.id = cs.profile_id
`

type GetLatestCompletedScansRow struct {
	ID            string           `json:"id"`
	HostID        string           `json:"host_id"`
	ProfileID     string           `json:"profile_id"`
	CompletedAt   pgtype.Timestamp `json:"completed_at"`
	Passed        int32            `json:"passed"`
	Failed        int32            `json:"failed"`
	Warnings      int32            `json:"warnings"`
	Skipped       int32            `json:"skipped"`
	NotApplicable int32            `json:"not_applicable"`
	Score         *float64         `json:"score"`
	TotalRules    int32            `json:"total_rules"`
	ProfileName   string           `json:"profile_name"`
	ProfileType   string           `json:"profile_type"`
}

func (q *Queries) GetLatestCompletedScans(ctx context.Context) ([]GetLatestCompletedScansRow, error) {
	rows, err := q.db.Query(ctx, getLatestCompletedScans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestCompletedScansRow
	for rows.Next() {
		var i GetLatestCompletedScansRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.ProfileID,
			&i.CompletedAt,
			&i.Passed,
			&i.Failed,
			&i.Warnings,
			&i.Skipped,
			&i.NotApplicable,
			&i.Score,
			&i.TotalRules,
			&i.ProfileName,
			&i.ProfileType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestCompletedScansByProfile = `-- name: GetLatestCompletedScansByProfile :many
SELECT cs.id, cs.host_id, cs.profile_id, cs.completed_at, cs.passed, cs.failed,
       cs.warnings, cs.skipped, cs.not_applicable, cs.score, cs.total_rules,
       cp.name as profile_name, cp.type as profile_type
FROM (
    SELECT DISTINCT ON (host_id)
        id, host_id, profile_id, completed_at, passed, failed, warnings,
        skipped, not_applicable, score, total_rules
    FROM compliance_scans
    WHERE status = 'completed' AND profile_id = $1
    ORDER BY host_id, completed_at DESC
) cs
JOIN compliance_profiles cp ON cp.id = cs.profile_id
`

type GetLatestCompletedScansByProfileRow struct {
	ID            string           `json:"id"`
	HostID        string           `json:"host_id"`
	ProfileID     string           `json:"profile_id"`
	CompletedAt   pgtype.Timestamp `json:"completed_at"`
	Passed        int32            `json:"passed"`
	Failed        int32            `json:"failed"`
	Warnings      int32            `json:"warnings"`
	Skipped       int32            `json:"skipped"`
	NotApplicable int32            `json:"not_applicable"`
	Score         *float64         `json:"score"`
	TotalRules    int32            `json:"total_rules"`
	ProfileName   string           `json:"profile_name"`
	ProfileType   string           `json:"profile_type"`
}

func (q *Queries) GetLatestCompletedScansByProfile(ctx context.Context, profileID string) ([]GetLatestCompletedScansByProfileRow, error) {
	rows, err := q.db.Query(ctx, getLatestCompletedScansByProfile, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestCompletedScansByProfileRow
	for rows.Next() {
		var i GetLatestCompletedScansByProfileRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.ProfileID,
			&i.CompletedAt,
			&i.Passed,
			&i.Failed,
			&i.Warnings,
			&i.Skipped,
			&i.NotApplicable,
			&i.Score,
			&i.TotalRules,
			&i.ProfileName,
			&i.ProfileType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestComplianceScanByHost = `-- name: GetLatestComplianceScanByHost :one
SELECT cs.id, cs.host_id, cs.profile_id, cs.started_at, cs.completed_at, cs.status,
       cs.total_rules, cs.passed, cs.failed, cs.warnings, cs.skipped, cs.not_applicable,
       cs.score, cs.error_message, cs.raw_output, cs.created_at, cs.updated_at,
       cp.name as profile_name, cp.type as profile_type
FROM compliance_scans cs
JOIN compliance_profiles cp ON cp.id = cs.profile_id
WHERE cs.host_id = $1 AND cs.status = 'completed'
ORDER BY cs.completed_at DESC
LIMIT 1
`

type GetLatestComplianceScanByHostRow struct {
	ID            string           `json:"id"`
	HostID        string           `json:"host_id"`
	ProfileID     string           `json:"profile_id"`
	StartedAt     pgtype.Timestamp `json:"started_at"`
	CompletedAt   pgtype.Timestamp `json:"completed_at"`
	Status        string           `json:"status"`
	TotalRules    int32            `json:"total_rules"`
	Passed        int32            `json:"passed"`
	Failed        int32            `json:"failed"`
	Warnings      int32            `json:"warnings"`
	Skipped       int32            `json:"skipped"`
	NotApplicable int32            `json:"not_applicable"`
	Score         *float64         `json:"score"`
	ErrorMessage  *string          `json:"error_message"`
	RawOutput     *string          `json:"raw_output"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	ProfileName   string           `json:"profile_name"`
	ProfileType   string           `json:"profile_type"`
}

func (q *Queries) GetLatestComplianceScanByHost(ctx context.Context, hostID string) (GetLatestComplianceScanByHostRow, error) {
	row := q.db.QueryRow(ctx, getLatestComplianceScanByHost, hostID)
	var i GetLatestComplianceScanByHostRow
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.ProfileID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Status,
		&i.TotalRules,
		&i.Passed,
		&i.Failed,
		&i.Warnings,
		&i.Skipped,
		&i.NotApplicable,
		&i.Score,
		&i.ErrorMessage,
		&i.RawOutput,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfileName,
		&i.ProfileType,
	)
	return i, err
}

const getLatestComplianceScanByHostAndType = `-- name: GetLatestComplianceScanByHostAndType :one
SELECT cs.id, cs.host_id, cs.profile_id, cs.started_at, cs.completed_at, cs.status,
       cs.total_rules, cs.passed, cs.failed, cs.warnings, cs.skipped, cs.not_applicable,
       cs.score, cs.error_message, cs.raw_output, cs.created_at, cs.updated_at,
       cp.name as profile_name, cp.type as profile_type
FROM compliance_scans cs
JOIN compliance_profiles cp ON cp.id = cs.profile_id
WHERE cs.host_id = $1 AND cs.status = 'completed' AND cp.type = $2
ORDER BY cs.completed_at DESC
LIMIT 1
`

type GetLatestComplianceScanByHostAndTypeParams struct {
	HostID string `json:"host_id"`
	Type   string `json:"type"`
}

type GetLatestComplianceScanByHostAndTypeRow struct {
	ID            string           `json:"id"`
	HostID        string           `json:"host_id"`
	ProfileID     string           `json:"profile_id"`
	StartedAt     pgtype.Timestamp `json:"started_at"`
	CompletedAt   pgtype.Timestamp `json:"completed_at"`
	Status        string           `json:"status"`
	TotalRules    int32            `json:"total_rules"`
	Passed        int32            `json:"passed"`
	Failed        int32            `json:"failed"`
	Warnings      int32            `json:"warnings"`
	Skipped       int32            `json:"skipped"`
	NotApplicable int32            `json:"not_applicable"`
	Score         *float64         `json:"score"`
	ErrorMessage  *string          `json:"error_message"`
	RawOutput     *string          `json:"raw_output"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	ProfileName   string           `json:"profile_name"`
	ProfileType   string           `json:"profile_type"`
}

func (q *Queries) GetLatestComplianceScanByHostAndType(ctx context.Context, arg GetLatestComplianceScanByHostAndTypeParams) (GetLatestComplianceScanByHostAndTypeRow, error) {
	row := q.db.QueryRow(ctx, getLatestComplianceScanByHostAndType, arg.HostID, arg.Type)
	var i GetLatestComplianceScanByHostAndTypeRow
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.ProfileID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Status,
		&i.TotalRules,
		&i.Passed,
		&i.Failed,
		&i.Warnings,
		&i.Skipped,
		&i.NotApplicable,
		&i.Score,
		&i.ErrorMessage,
		&i.RawOutput,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfileName,
		&i.ProfileType,
	)
	return i, err
}

const getRecentComplianceScans = `-- name: GetRecentComplianceScans :many
SELECT cs.id, cs.host_id, cs.profile_id, cs.started_at, cs.completed_at, cs.status,
       cs.total_rules, cs.passed, cs.failed, cs.warnings, cs.skipped, cs.not_applicable,
       cs.score, cs.error_message,
       h.hostname, h.friendly_name,
       cp.name as profile_name, cp.type as profile_type
FROM compliance_scans cs
JOIN hosts h ON h.id = cs.host_id
JOIN compliance_profiles cp ON cp.id = cs.profile_id
ORDER BY cs.completed_at DESC NULLS LAST
LIMIT 10
`

type GetRecentComplianceScansRow struct {
	ID            string           `json:"id"`
	HostID        string           `json:"host_id"`
	ProfileID     string           `json:"profile_id"`
	StartedAt     pgtype.Timestamp `json:"started_at"`
	CompletedAt   pgtype.Timestamp `json:"completed_at"`
	Status        string           `json:"status"`
	TotalRules    int32            `json:"total_rules"`
	Passed        int32            `json:"passed"`
	Failed        int32            `json:"failed"`
	Warnings      int32            `json:"warnings"`
	Skipped       int32            `json:"skipped"`
	NotApplicable int32            `json:"not_applicable"`
	Score         *float64         `json:"score"`
	ErrorMessage  *string          `json:"error_message"`
	Hostname      *string          `json:"hostname"`
	FriendlyName  string           `json:"friendly_name"`
	ProfileName   string           `json:"profile_name"`
	ProfileType   string           `json:"profile_type"`
}

func (q *Queries) GetRecentComplianceScans(ctx context.Context) ([]GetRecentComplianceScansRow, error) {
	rows, err := q.db.Query(ctx, getRecentComplianceScans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentComplianceScansRow
	for rows.Next() {
		var i GetRecentComplianceScansRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.ProfileID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Status,
			&i.TotalRules,
			&i.Passed,
			&i.Failed,
			&i.Warnings,
			&i.Skipped,
			&i.NotApplicable,
			&i.Score,
			&i.ErrorMessage,
			&i.Hostname,
			&i.FriendlyName,
			&i.ProfileName,
			&i.ProfileType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveComplianceScans = `-- name: ListActiveComplianceScans :many
SELECT cs.id, cs.host_id, cs.profile_id, cs.started_at, cs.status,
       h.hostname, h.friendly_name, h.api_id,
       cp.name as profile_name, cp.type as profile_type
FROM compliance_scans cs
JOIN hosts h ON h.id = cs.host_id
JOIN compliance_profiles cp ON cp.id = cs.profile_id
WHERE cs.status = 'running' OR (cs.completed_at IS NULL AND cs.status != 'failed')
ORDER BY cs.started_at DESC
`

type ListActiveComplianceScansRow struct {
	ID           string           `json:"id"`
	HostID       string           `json:"host_id"`
	ProfileID    string           `json:"profile_id"`
	StartedAt    pgtype.Timestamp `json:"started_at"`
	Status       string           `json:"status"`
	Hostname     *string          `json:"hostname"`
	FriendlyName string           `json:"friendly_name"`
	ApiID        string           `json:"api_id"`
	ProfileName  string           `json:"profile_name"`
	ProfileType  string           `json:"profile_type"`
}

func (q *Queries) ListActiveComplianceScans(ctx context.Context) ([]ListActiveComplianceScansRow, error) {
	rows, err := q.db.Query(ctx, listActiveComplianceScans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveComplianceScansRow
	for rows.Next() {
		var i ListActiveComplianceScansRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.ProfileID,
			&i.StartedAt,
			&i.Status,
			&i.Hostname,
			&i.FriendlyName,
			&i.ApiID,
			&i.ProfileName,
			&i.ProfileType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComplianceScansByHost = `-- name: ListComplianceScansByHost :many
SELECT cs.id, cs.host_id, cs.profile_id, cs.started_at, cs.completed_at, cs.status,
       cs.total_rules, cs.passed, cs.failed, cs.warnings, cs.skipped, cs.not_applicable,
       cs.score, cs.error_message, cs.created_at, cs.updated_at,
       cp.name as profile_name, cp.type as profile_type
FROM compliance_scans cs
JOIN compliance_profiles cp ON cp.id = cs.profile_id
WHERE cs.host_id = $1
ORDER BY cs.completed_at DESC NULLS LAST
LIMIT $2 OFFSET $3
`

type ListComplianceScansByHostParams struct {
	HostID string `json:"host_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListComplianceScansByHostRow struct {
	ID            string           `json:"id"`
	HostID        string           `json:"host_id"`
	ProfileID     string           `json:"profile_id"`
	StartedAt     pgtype.Timestamp `json:"started_at"`
	CompletedAt   pgtype.Timestamp `json:"completed_at"`
	Status        string           `json:"status"`
	TotalRules    int32            `json:"total_rules"`
	Passed        int32            `json:"passed"`
	Failed        int32            `json:"failed"`
	Warnings      int32            `json:"warnings"`
	Skipped       int32            `json:"skipped"`
	NotApplicable int32            `json:"not_applicable"`
	Score         *float64         `json:"score"`
	ErrorMessage  *string          `json:"error_message"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	ProfileName   string           `json:"profile_name"`
	ProfileType   string           `json:"profile_type"`
}

func (q *Queries) ListComplianceScansByHost(ctx context.Context, arg ListComplianceScansByHostParams) ([]ListComplianceScansByHostRow, error) {
	rows, err := q.db.Query(ctx, listComplianceScansByHost, arg.HostID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListComplianceScansByHostRow
	for rows.Next() {
		var i ListComplianceScansByHostRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.ProfileID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Status,
			&i.TotalRules,
			&i.Passed,
			&i.Failed,
			&i.Warnings,
			&i.Skipped,
			&i.NotApplicable,
			&i.Score,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProfileName,
			&i.ProfileType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComplianceScansHistory = `-- name: ListComplianceScansHistory :many
SELECT cs.id, cs.host_id, cs.status, cs.started_at, cs.completed_at,
       cs.total_rules, cs.passed, cs.failed, cs.warnings, cs.skipped, cs.not_applicable,
       cs.score, cs.error_message,
       h.hostname, h.friendly_name,
       cp.name as profile_name, cp.type as profile_type
FROM compliance_scans cs
JOIN hosts h ON h.id = cs.host_id
JOIN compliance_profiles cp ON cp.id = cs.profile_id
WHERE ($3::text IS NULL OR cs.status = $3)
  AND ($4::text IS NULL OR cs.host_id = $4)
  AND ($5::text IS NULL OR cp.type = $5)
  AND ($6::text IS NULL OR h.friendly_name ILIKE '%' || $6 || '%' OR h.hostname ILIKE '%' || $6 || '%' OR cp.name ILIKE '%' || $6 || '%')
ORDER BY cs.started_at DESC
LIMIT $1 OFFSET $2
`

type ListComplianceScansHistoryParams struct {
	Limit       int32   `json:"limit"`
	Offset      int32   `json:"offset"`
	Status      *string `json:"status"`
	HostID      *string `json:"host_id"`
	ProfileType *string `json:"profile_type"`
	Search      *string `json:"search"`
}

type ListComplianceScansHistoryRow struct {
	ID            string           `json:"id"`
	HostID        string           `json:"host_id"`
	Status        string           `json:"status"`
	StartedAt     pgtype.Timestamp `json:"started_at"`
	CompletedAt   pgtype.Timestamp `json:"completed_at"`
	TotalRules    int32            `json:"total_rules"`
	Passed        int32            `json:"passed"`
	Failed        int32            `json:"failed"`
	Warnings      int32            `json:"warnings"`
	Skipped       int32            `json:"skipped"`
	NotApplicable int32            `json:"not_applicable"`
	Score         *float64         `json:"score"`
	ErrorMessage  *string          `json:"error_message"`
	Hostname      *string          `json:"hostname"`
	FriendlyName  string           `json:"friendly_name"`
	ProfileName   string           `json:"profile_name"`
	ProfileType   string           `json:"profile_type"`
}

func (q *Queries) ListComplianceScansHistory(ctx context.Context, arg ListComplianceScansHistoryParams) ([]ListComplianceScansHistoryRow, error) {
	rows, err := q.db.Query(ctx, listComplianceScansHistory,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.HostID,
		arg.ProfileType,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListComplianceScansHistoryRow
	for rows.Next() {
		var i ListComplianceScansHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.TotalRules,
			&i.Passed,
			&i.Failed,
			&i.Warnings,
			&i.Skipped,
			&i.NotApplicable,
			&i.Score,
			&i.ErrorMessage,
			&i.Hostname,
			&i.FriendlyName,
			&i.ProfileName,
			&i.ProfileType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStalledComplianceScans = `-- name: ListStalledComplianceScans :many
SELECT id, host_id, profile_id, started_at, status FROM compliance_scans
WHERE (status = 'running' OR (completed_at IS NULL AND status != 'failed'))
AND started_at < $1
`

type ListStalledComplianceScansRow struct {
	ID        string           `json:"id"`
	HostID    string           `json:"host_id"`
	ProfileID string           `json:"profile_id"`
	StartedAt pgtype.Timestamp `json:"started_at"`
	Status    string           `json:"status"`
}

func (q *Queries) ListStalledComplianceScans(ctx context.Context, startedAt pgtype.Timestamp) ([]ListStalledComplianceScansRow, error) {
	rows, err := q.db.Query(ctx, listStalledComplianceScans, startedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStalledComplianceScansRow
	for rows.Next() {
		var i ListStalledComplianceScansRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.ProfileID,
			&i.StartedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStalledComplianceScansWithDetails = `-- name: ListStalledComplianceScansWithDetails :many
SELECT cs.id, cs.host_id, cs.profile_id, cs.started_at, cs.status,
       h.hostname, h.friendly_name, h.api_id,
       cp.name as profile_name, cp.type as profile_type
FROM compliance_scans cs
JOIN hosts h ON h.id = cs.host_id
JOIN compliance_profiles cp ON cp.id = cs.profile_id
WHERE (cs.status = 'running' OR (cs.completed_at IS NULL AND cs.status != 'failed'))
  AND cs.started_at < $1
ORDER BY cs.started_at ASC
`

type ListStalledComplianceScansWithDetailsRow struct {
	ID           string           `json:"id"`
	HostID       string           `json:"host_id"`
	ProfileID    string           `json:"profile_id"`
	StartedAt    pgtype.Timestamp `json:"started_at"`
	Status       string           `json:"status"`
	Hostname     *string          `json:"hostname"`
	FriendlyName string           `json:"friendly_name"`
	ApiID        string           `json:"api_id"`
	ProfileName  string           `json:"profile_name"`
	ProfileType  string           `json:"profile_type"`
}

func (q *Queries) ListStalledComplianceScansWithDetails(ctx context.Context, startedAt pgtype.Timestamp) ([]ListStalledComplianceScansWithDetailsRow, error) {
	rows, err := q.db.Query(ctx, listStalledComplianceScansWithDetails, startedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStalledComplianceScansWithDetailsRow
	for rows.Next() {
		var i ListStalledComplianceScansWithDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.ProfileID,
			&i.StartedAt,
			&i.Status,
			&i.Hostname,
			&i.FriendlyName,
			&i.ApiID,
			&i.ProfileName,
			&i.ProfileType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStalledComplianceScans = `-- name: UpdateStalledComplianceScans :exec
UPDATE compliance_scans
SET status = 'failed', completed_at = NOW(), error_message = $2
WHERE (status = 'running' OR (completed_at IS NULL AND status != 'failed'))
AND started_at < $1
`

type UpdateStalledComplianceScansParams struct {
	StartedAt    pgtype.Timestamp `json:"started_at"`
	ErrorMessage *string          `json:"error_message"`
}

func (q *Queries) UpdateStalledComplianceScans(ctx context.Context, arg UpdateStalledComplianceScansParams) error {
	_, err := q.db.Exec(ctx, updateStalledComplianceScans, arg.StartedAt, arg.ErrorMessage)
	return err
}
