// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: compliance_profiles.sql

package db

import (
	"context"
)

const createComplianceProfile = `-- name: CreateComplianceProfile :one
INSERT INTO compliance_profiles (id, name, type, os_family, version, description, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW(), NOW())
RETURNING id, name, type, os_family, version, description, created_at, updated_at
`

type CreateComplianceProfileParams struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Type        string  `json:"type"`
	OsFamily    *string `json:"os_family"`
	Version     *string `json:"version"`
	Description *string `json:"description"`
}

func (q *Queries) CreateComplianceProfile(ctx context.Context, arg CreateComplianceProfileParams) (ComplianceProfile, error) {
	row := q.db.QueryRow(ctx, createComplianceProfile,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.OsFamily,
		arg.Version,
		arg.Description,
	)
	var i ComplianceProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.OsFamily,
		&i.Version,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getComplianceProfileByID = `-- name: GetComplianceProfileByID :one
SELECT id, name, type, os_family, version, description, created_at, updated_at
FROM compliance_profiles
WHERE id = $1
`

func (q *Queries) GetComplianceProfileByID(ctx context.Context, id string) (ComplianceProfile, error) {
	row := q.db.QueryRow(ctx, getComplianceProfileByID, id)
	var i ComplianceProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.OsFamily,
		&i.Version,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getComplianceProfileByName = `-- name: GetComplianceProfileByName :one
SELECT id, name, type, os_family, version, description, created_at, updated_at
FROM compliance_profiles
WHERE name = $1
`

func (q *Queries) GetComplianceProfileByName(ctx context.Context, name string) (ComplianceProfile, error) {
	row := q.db.QueryRow(ctx, getComplianceProfileByName, name)
	var i ComplianceProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.OsFamily,
		&i.Version,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFirstComplianceProfileByType = `-- name: GetFirstComplianceProfileByType :one
SELECT id, name, type, os_family, version, description, created_at, updated_at
FROM compliance_profiles
WHERE type = $1
ORDER BY name ASC
LIMIT 1
`

func (q *Queries) GetFirstComplianceProfileByType(ctx context.Context, type_ string) (ComplianceProfile, error) {
	row := q.db.QueryRow(ctx, getFirstComplianceProfileByType, type_)
	var i ComplianceProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.OsFamily,
		&i.Version,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listComplianceProfiles = `-- name: ListComplianceProfiles :many
SELECT id, name, type, os_family, version, description, created_at, updated_at
FROM compliance_profiles
ORDER BY name ASC
`

func (q *Queries) ListComplianceProfiles(ctx context.Context) ([]ComplianceProfile, error) {
	rows, err := q.db.Query(ctx, listComplianceProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComplianceProfile
	for rows.Next() {
		var i ComplianceProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.OsFamily,
			&i.Version,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertComplianceProfile = `-- name: UpsertComplianceProfile :one
INSERT INTO compliance_profiles (id, name, type, os_family, version, description, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW(), NOW())
ON CONFLICT (name) DO UPDATE SET
    updated_at = NOW()
RETURNING id, name, type, os_family, version, description, created_at, updated_at
`

type UpsertComplianceProfileParams struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Type        string  `json:"type"`
	OsFamily    *string `json:"os_family"`
	Version     *string `json:"version"`
	Description *string `json:"description"`
}

// DO UPDATE rather than DO NOTHING so the row is always returned on conflict.
// Deliberately does not touch type: an existing profile keeps the type it was
// created with. Overwriting it flips which scanner toggle gates it in SubmitScan.
func (q *Queries) UpsertComplianceProfile(ctx context.Context, arg UpsertComplianceProfileParams) (ComplianceProfile, error) {
	row := q.db.QueryRow(ctx, upsertComplianceProfile,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.OsFamily,
		arg.Version,
		arg.Description,
	)
	var i ComplianceProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.OsFamily,
		&i.Version,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
