// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countHostsForList = `-- name: CountHostsForList :one
WITH base_hosts AS (
    SELECT h.id, h.status, h.last_update, h.needs_reboot
    FROM hosts h
    WHERE ($4::text IS NULL OR h.friendly_name ILIKE '%' || $4 || '%' OR h.hostname ILIKE '%' || $4 || '%' OR h.ip ILIKE '%' || $4 || '%' OR h.os_type ILIKE '%' || $4 || '%' OR h.notes ILIKE '%' || $4 || '%')
    AND (
        $5::text IS NULL
        OR ($5 = 'ungrouped' AND NOT EXISTS (SELECT 1 FROM host_group_memberships hgm WHERE hgm.host_id = h.id))
        OR ($5 != 'ungrouped' AND EXISTS (SELECT 1 FROM host_group_memberships hgm WHERE hgm.host_id = h.id AND hgm.host_group_id = $5))
    )
    AND ($6::text IS NULL OR h.status = $6)
    AND ($7::text IS NULL OR h.os_type ILIKE $7)
    AND ($8::text IS NULL OR h.os_version ILIKE $8)
    AND (
        $1::text IS DISTINCT FROM 'selected'
        OR h.id = ANY($9::text[])
    )
),
filtered_hosts AS (
    SELECT bh.id,
           (bh.status = 'active' AND bh.last_update < $10::timestamp) AS is_stale,
           CASE
               WHEN bh.status = 'active' AND bh.last_update < $10::timestamp THEN 'inactive'
               ELSE bh.status
           END AS effective_status,
           bh.needs_reboot
    FROM base_hosts bh
)
SELECT COUNT(*)::int
FROM filtered_hosts
WHERE (
    $1::text IS NULL
    OR ($1 = 'needsUpdates' AND EXISTS (
        SELECT 1 FROM host_packages hp WHERE hp.host_id = filtered_hosts.id AND hp.needs_update
    ))
    OR ($1 = 'inactive' AND effective_status = 'inactive')
    OR ($1 = 'upToDate' AND is_stale = false AND EXISTS (
        SELECT 1 FROM host_packages hp WHERE hp.host_id = filtered_hosts.id
    ) AND NOT EXISTS (
        SELECT 1 FROM host_packages hp WHERE hp.host_id = filtered_hosts.id AND hp.needs_update
    ))
    OR ($1 = 'awaitingData' AND NOT EXISTS (
        SELECT 1 FROM host_packages hp WHERE hp.host_id = filtered_hosts.id
    ))
    OR ($1 = 'stale' AND is_stale = true)
    OR ($1 = 'selected')
)
AND ($2::boolean = false OR needs_reboot = true)
AND ($3::boolean = false OR is_stale = false)
`

type CountHostsForListParams struct {
	Filter         *string          `json:"filter"`
	RebootOnly     bool             `json:"reboot_only"`
	HideStale      bool             `json:"hide_stale"`
	Search         *string          `json:"search"`
	Group          *string          `json:"group"`
	Status         *string          `json:"status"`
	Os             *string          `json:"os"`
	OsVersion      *string          `json:"os_version"`
	SelectedIds    []string         `json:"selected_ids"`
	StaleThreshold pgtype.Timestamp `json:"stale_threshold"`
}

// Total count matching the same filter set as GetHostsWithCounts. Used by
// the paginated UI so it can render "Showing X-Y of Z" and a correct page
// count.
func (q *Queries) CountHostsForList(ctx context.Context, arg CountHostsForListParams) (int32, error) {
	row := q.db.QueryRow(ctx, countHostsForList,
		arg.Filter,
		arg.RebootOnly,
		arg.HideStale,
		arg.Search,
		arg.Group,
		arg.Status,
		arg.Os,
		arg.OsVersion,
		arg.SelectedIds,
		arg.StaleThreshold,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countUpdateHistory = `-- name: CountUpdateHistory :one
SELECT COUNT(*)::int
FROM update_history
WHERE host_id = $1
  AND report_type IN ('full', 'partial')
`

func (q *Queries) CountUpdateHistory(ctx context.Context, hostID string) (int32, error) {
	row := q.db.QueryRow(ctx, countUpdateHistory, hostID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getDashboardStats = `-- name: GetDashboardStats :one
WITH host_counts AS (
    SELECT
        COUNT(*)::int AS total_hosts,
        -- Must match the effective_status = 'inactive' predicate the
        -- filter=inactive host list uses, otherwise the count and the list it
        -- links to disagree.
        COUNT(*) FILTER (WHERE (status = 'active' AND last_update < $1) OR status = 'inactive')::int AS errored_hosts,
        COUNT(*) FILTER (WHERE status = 'active' AND last_update < $2)::int AS offline_hosts,
        COUNT(*) FILTER (WHERE needs_reboot = true)::int AS hosts_needing_reboot,
        -- Hosts we have actually received packages from. "Up to date" is
        -- derived from this, not from total_hosts, so a host we know nothing
        -- about is never reported as healthy.
        --
        -- An EXISTS semi-join, not COUNT(DISTINCT host_id) over host_packages:
        -- the latter reads every row in the table (1.25M at 1k hosts, 55 ms)
        -- to rediscover something 1000 index probes answer in 2 ms, and it
        -- scales with package rows rather than host count. It also rides the
        -- scan of hosts this CTE is already doing.
        COUNT(*) FILTER (WHERE EXISTS (
            SELECT 1 FROM host_packages hp WHERE hp.host_id = hosts.id
        ))::int AS hosts_with_package_data
    FROM hosts
),
hp_package_counts AS (
    SELECT
        COALESCE((
            SELECT COUNT(*)::int
            FROM (
                SELECT hp.host_id
                FROM host_packages hp
                WHERE hp.needs_update = true
                GROUP BY hp.host_id
            ) hosts_with_updates
        ), 0)::int AS hosts_needing_updates,
        COALESCE((
            SELECT COUNT(*)::int
            FROM (
                SELECT hp.package_id
                FROM host_packages hp
                WHERE hp.needs_update = true
                GROUP BY hp.package_id
            ) outdated_packages
        ), 0)::int AS total_outdated_packages,
        COALESCE((
            SELECT COUNT(*)::int
            FROM (
                SELECT hp.package_id
                FROM host_packages hp
                WHERE hp.needs_update = true AND hp.is_security_update = true
                GROUP BY hp.package_id
            ) security_packages
        ), 0)::int AS security_updates
)
SELECT
    hc.total_hosts,
    hpc.hosts_needing_updates,
    hpc.total_outdated_packages,
    hc.errored_hosts,
    hpc.security_updates,
    hc.offline_hosts,
    hc.hosts_needing_reboot,
    (SELECT COUNT(*)::int FROM host_groups),
    (SELECT COUNT(*)::int FROM users),
    (SELECT COUNT(*)::int FROM repositories),
    hc.hosts_with_package_data
FROM host_counts hc
CROSS JOIN hp_package_counts hpc
`

type GetDashboardStatsParams struct {
	LastUpdate   pgtype.Timestamp `json:"last_update"`
	LastUpdate_2 pgtype.Timestamp `json:"last_update_2"`
}

type GetDashboardStatsRow struct {
	TotalHosts            int32 `json:"total_hosts"`
	HostsNeedingUpdates   int32 `json:"hosts_needing_updates"`
	TotalOutdatedPackages int32 `json:"total_outdated_packages"`
	ErroredHosts          int32 `json:"errored_hosts"`
	SecurityUpdates       int32 `json:"security_updates"`
	OfflineHosts          int32 `json:"offline_hosts"`
	HostsNeedingReboot    int32 `json:"hosts_needing_reboot"`
	Column8               int32 `json:"column_8"`
	Column9               int32 `json:"column_9"`
	Column10              int32 `json:"column_10"`
	HostsWithPackageData  int32 `json:"hosts_with_package_data"`
}

func (q *Queries) GetDashboardStats(ctx context.Context, arg GetDashboardStatsParams) (GetDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardStats, arg.LastUpdate, arg.LastUpdate_2)
	var i GetDashboardStatsRow
	err := row.Scan(
		&i.TotalHosts,
		&i.HostsNeedingUpdates,
		&i.TotalOutdatedPackages,
		&i.ErroredHosts,
		&i.SecurityUpdates,
		&i.OfflineHosts,
		&i.HostsNeedingReboot,
		&i.Column8,
		&i.Column9,
		&i.Column10,
		&i.HostsWithPackageData,
	)
	return i, err
}

const getHomepageStats = `-- name: GetHomepageStats :one
WITH host_counts AS (
    SELECT COUNT(*)::int AS total_hosts,
           -- See GetDashboardStats: semi-join, not COUNT(DISTINCT), and it
           -- rides the scan of ` + "`" + `hosts` + "`" + ` already happening here.
           COUNT(*) FILTER (WHERE EXISTS (
               SELECT 1 FROM host_packages hp WHERE hp.host_id = hosts.id
           ))::int AS hosts_with_package_data
    FROM hosts
),
hosts_needing_updates AS (
    SELECT COUNT(*)::int AS cnt FROM (
        SELECT hp.host_id
        FROM host_packages hp
        WHERE hp.needs_update = true
        GROUP BY hp.host_id
    ) t
),
hosts_with_security AS (
    SELECT COUNT(*)::int AS cnt FROM (
        SELECT hp.host_id
        FROM host_packages hp
        WHERE hp.needs_update = true AND hp.is_security_update = true
        GROUP BY hp.host_id
    ) t
),
package_counts AS (
    -- Split rather than one pass with FILTER: two passes each driven by their
    -- own covering index beat one pass that can only use the wider of them.
    SELECT
        COALESCE((
            SELECT COUNT(*)::int FROM (
                SELECT hp.package_id
                FROM host_packages hp
                WHERE hp.needs_update = true
                GROUP BY hp.package_id
            ) t
        ), 0)::int AS total_outdated,
        COALESCE((
            SELECT COUNT(*)::int FROM (
                SELECT hp.package_id
                FROM host_packages hp
                WHERE hp.needs_update = true AND hp.is_security_update = true
                GROUP BY hp.package_id
            ) t
        ), 0)::int AS security_updates
)
SELECT
    hc.total_hosts,
    hnu.cnt AS hosts_needing_updates,
    pc.total_outdated AS total_outdated_packages,
    pc.security_updates AS security_updates,
    hws.cnt AS hosts_with_security_updates,
    (SELECT COUNT(*)::int FROM repositories WHERE is_active = true) AS total_repos,
    (SELECT COUNT(*)::int FROM update_history WHERE timestamp >= $1 AND status = 'success' AND report_type IN ('full', 'partial')) AS recent_updates_24h,
    hc.hosts_with_package_data
FROM host_counts hc
CROSS JOIN hosts_needing_updates hnu
CROSS JOIN hosts_with_security hws
CROSS JOIN package_counts pc
`

type GetHomepageStatsRow struct {
	TotalHosts               int32 `json:"total_hosts"`
	HostsNeedingUpdates      int32 `json:"hosts_needing_updates"`
	TotalOutdatedPackages    int32 `json:"total_outdated_packages"`
	SecurityUpdates          int32 `json:"security_updates"`
	HostsWithSecurityUpdates int32 `json:"hosts_with_security_updates"`
	TotalRepos               int32 `json:"total_repos"`
	RecentUpdates24h         int32 `json:"recent_updates_24h"`
	HostsWithPackageData     int32 `json:"hosts_with_package_data"`
}

// The host counters here must match GetDashboardStats, otherwise a widget and
// the dashboard card it mirrors report different numbers for the same fleet.
// They previously filtered on status = 'active', which silently dropped hosts
// that had been created but not yet enrolled. That filter also did not mean
// what it appeared to: hosts.status is an enrolment lifecycle column and never
// becomes 'inactive', so a host that stopped reporting was counted regardless.
// Distinct counts are expressed as GROUP BY subqueries, not COUNT(DISTINCT),
// and must stay that way. COUNT(DISTINCT) cannot stream: it sorts the whole
// matching set, which at 3.7M host_packages rows spills multiple megabytes to
// disk and costs ~3x what the identical aggregates cost in GetDashboardStats,
// which already uses this shape. GROUP BY reads straight off the partial
// covering indexes (idx_host_packages_needs_update_host_cover and the
// _package / _security_package pair) and sorts nothing worth spilling.
//
// Exact, not approximate: the two forms differ only on NULL handling, and
// host_id and package_id are both NOT NULL.
func (q *Queries) GetHomepageStats(ctx context.Context, since pgtype.Timestamp) (GetHomepageStatsRow, error) {
	row := q.db.QueryRow(ctx, getHomepageStats, since)
	var i GetHomepageStatsRow
	err := row.Scan(
		&i.TotalHosts,
		&i.HostsNeedingUpdates,
		&i.TotalOutdatedPackages,
		&i.SecurityUpdates,
		&i.HostsWithSecurityUpdates,
		&i.TotalRepos,
		&i.RecentUpdates24h,
		&i.HostsWithPackageData,
	)
	return i, err
}

const getHostCounts = `-- name: GetHostCounts :one
SELECT
    COUNT(*)::int                                                                              AS total,
    COUNT(*) FILTER (WHERE status = 'active' AND last_update >= $1)::int                       AS up,
    COUNT(*) FILTER (WHERE status = 'active' AND last_update <  $1 AND last_update >= $2)::int AS stale,
    COUNT(*) FILTER (WHERE status = 'active' AND last_update <  $2)::int                       AS down,
    COUNT(*) FILTER (WHERE status = 'inactive')::int                                           AS inactive,
    COUNT(*) FILTER (WHERE needs_reboot = true)::int                                           AS needs_reboot,
    COUNT(*) FILTER (WHERE EXISTS (
        SELECT 1 FROM host_packages hp WHERE hp.host_id = hosts.id AND hp.needs_update = true
    ))::int                                                                                    AS needs_updates
FROM hosts
`

type GetHostCountsParams struct {
	LastUpdate   pgtype.Timestamp `json:"last_update"`
	LastUpdate_2 pgtype.Timestamp `json:"last_update_2"`
}

type GetHostCountsRow struct {
	Total        int32 `json:"total"`
	Up           int32 `json:"up"`
	Stale        int32 `json:"stale"`
	Down         int32 `json:"down"`
	Inactive     int32 `json:"inactive"`
	NeedsReboot  int32 `json:"needs_reboot"`
	NeedsUpdates int32 `json:"needs_updates"`
}

// Cheap host-only counts for the sidebar / navbar widgets. Replaces the
// old pattern of fetching the entire host list and computing counts in
// the browser. $1 = stale threshold, $2 = down threshold (timestamps).
func (q *Queries) GetHostCounts(ctx context.Context, arg GetHostCountsParams) (GetHostCountsRow, error) {
	row := q.db.QueryRow(ctx, getHostCounts, arg.LastUpdate, arg.LastUpdate_2)
	var i GetHostCountsRow
	err := row.Scan(
		&i.Total,
		&i.Up,
		&i.Stale,
		&i.Down,
		&i.Inactive,
		&i.NeedsReboot,
		&i.NeedsUpdates,
	)
	return i, err
}

const getHostPackageStats = `-- name: GetHostPackageStats :one
SELECT COUNT(*)::int, COUNT(*) FILTER (WHERE needs_update)::int, COUNT(*) FILTER (WHERE needs_update AND is_security_update)::int
FROM host_packages WHERE host_id = $1
`

type GetHostPackageStatsRow struct {
	Column1 int32 `json:"column_1"`
	Column2 int32 `json:"column_2"`
	Column3 int32 `json:"column_3"`
}

func (q *Queries) GetHostPackageStats(ctx context.Context, hostID string) (GetHostPackageStatsRow, error) {
	row := q.db.QueryRow(ctx, getHostPackageStats, hostID)
	var i GetHostPackageStatsRow
	err := row.Scan(&i.Column1, &i.Column2, &i.Column3)
	return i, err
}

const getHostPackagesForScopedApi = `-- name: GetHostPackagesForScopedApi :many
SELECT hp.id, hp.host_id, hp.package_id, hp.current_version, hp.available_version,
    hp.needs_update, hp.is_security_update, hp.last_checked,
    p.name as pkg_name, p.description as pkg_description, p.category as pkg_category
FROM host_packages hp
JOIN packages p ON p.id = hp.package_id
WHERE hp.host_id = $1
ORDER BY hp.is_security_update DESC, hp.needs_update DESC
`

type GetHostPackagesForScopedApiRow struct {
	ID               string           `json:"id"`
	HostID           string           `json:"host_id"`
	PackageID        string           `json:"package_id"`
	CurrentVersion   string           `json:"current_version"`
	AvailableVersion *string          `json:"available_version"`
	NeedsUpdate      bool             `json:"needs_update"`
	IsSecurityUpdate bool             `json:"is_security_update"`
	LastChecked      pgtype.Timestamp `json:"last_checked"`
	PkgName          string           `json:"pkg_name"`
	PkgDescription   *string          `json:"pkg_description"`
	PkgCategory      *string          `json:"pkg_category"`
}

func (q *Queries) GetHostPackagesForScopedApi(ctx context.Context, hostID string) ([]GetHostPackagesForScopedApiRow, error) {
	rows, err := q.db.Query(ctx, getHostPackagesForScopedApi, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHostPackagesForScopedApiRow
	for rows.Next() {
		var i GetHostPackagesForScopedApiRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.PackageID,
			&i.CurrentVersion,
			&i.AvailableVersion,
			&i.NeedsUpdate,
			&i.IsSecurityUpdate,
			&i.LastChecked,
			&i.PkgName,
			&i.PkgDescription,
			&i.PkgCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHostPackagesWithPackages = `-- name: GetHostPackagesWithPackages :many
SELECT hp.id, hp.host_id, hp.package_id, hp.current_version, hp.available_version,
    hp.needs_update, hp.is_security_update, hp.last_checked,
    p.name as pkg_name
FROM host_packages hp
JOIN packages p ON p.id = hp.package_id
WHERE hp.host_id = $1
ORDER BY hp.needs_update DESC
`

type GetHostPackagesWithPackagesRow struct {
	ID               string           `json:"id"`
	HostID           string           `json:"host_id"`
	PackageID        string           `json:"package_id"`
	CurrentVersion   string           `json:"current_version"`
	AvailableVersion *string          `json:"available_version"`
	NeedsUpdate      bool             `json:"needs_update"`
	IsSecurityUpdate bool             `json:"is_security_update"`
	LastChecked      pgtype.Timestamp `json:"last_checked"`
	PkgName          string           `json:"pkg_name"`
}

func (q *Queries) GetHostPackagesWithPackages(ctx context.Context, hostID string) ([]GetHostPackagesWithPackagesRow, error) {
	rows, err := q.db.Query(ctx, getHostPackagesWithPackages, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHostPackagesWithPackagesRow
	for rows.Next() {
		var i GetHostPackagesWithPackagesRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.PackageID,
			&i.CurrentVersion,
			&i.AvailableVersion,
			&i.NeedsUpdate,
			&i.IsSecurityUpdate,
			&i.LastChecked,
			&i.PkgName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHostsForPackageTrends = `-- name: GetHostsForPackageTrends :many
SELECT id, friendly_name, hostname
FROM hosts
ORDER BY friendly_name ASC
`

type GetHostsForPackageTrendsRow struct {
	ID           string  `json:"id"`
	FriendlyName string  `json:"friendly_name"`
	Hostname     *string `json:"hostname"`
}

func (q *Queries) GetHostsForPackageTrends(ctx context.Context) ([]GetHostsForPackageTrendsRow, error) {
	rows, err := q.db.Query(ctx, getHostsForPackageTrends)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHostsForPackageTrendsRow
	for rows.Next() {
		var i GetHostsForPackageTrendsRow
		if err := rows.Scan(&i.ID, &i.FriendlyName, &i.Hostname); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHostsWithCounts = `-- name: GetHostsWithCounts :many
WITH base_hosts AS (
    SELECT h.id, h.machine_id, h.friendly_name, h.hostname, h.ip, h.os_type, h.os_version,
        h.status, h.agent_version, h.auto_update, h.notes, h.api_id,
        h.needs_reboot, h.reboot_reason, h.system_uptime, h.boot_time, h.docker_enabled, h.compliance_enabled, h.compliance_on_demand_only,
        h.last_update,
        h.compliance_scanner_status->'scanner_info'->>'ssg_version' as ssg_version,
        COALESCE((
            SELECT MIN(hg.name)
            FROM host_group_memberships hgm
            JOIN host_groups hg ON hg.id = hgm.host_group_id
            WHERE hgm.host_id = h.id
        ), '')::text AS first_group_name
    FROM hosts h
    WHERE ($5::text IS NULL OR h.friendly_name ILIKE '%' || $5 || '%' OR h.hostname ILIKE '%' || $5 || '%' OR h.ip ILIKE '%' || $5 || '%' OR h.os_type ILIKE '%' || $5 || '%' OR h.notes ILIKE '%' || $5 || '%')
    AND (
        $6::text IS NULL
        OR ($6 = 'ungrouped' AND NOT EXISTS (SELECT 1 FROM host_group_memberships hgm WHERE hgm.host_id = h.id))
        OR ($6 != 'ungrouped' AND EXISTS (SELECT 1 FROM host_group_memberships hgm WHERE hgm.host_id = h.id AND hgm.host_group_id = $6))
    )
    AND ($7::text IS NULL OR h.status = $7)
    AND ($8::text IS NULL OR h.os_type ILIKE $8)
    AND ($9::text IS NULL OR h.os_version ILIKE $9)
    AND (
        $10::text IS DISTINCT FROM 'selected'
        OR h.id = ANY($11::text[])
    )
),
hp_counts AS (
    SELECT hp.host_id,
           COUNT(*) FILTER (WHERE hp.needs_update)::int                                AS updates_count,
           COUNT(*) FILTER (WHERE hp.needs_update AND hp.is_security_update)::int       AS security_count,
           COUNT(*)::int                                                               AS total_count
    FROM host_packages hp
    JOIN base_hosts bh ON bh.id = hp.host_id
    GROUP BY hp.host_id
),
enriched_hosts AS (
    SELECT bh.id, bh.machine_id, bh.friendly_name, bh.hostname, bh.ip, bh.os_type, bh.os_version, bh.status, bh.agent_version, bh.auto_update, bh.notes, bh.api_id, bh.needs_reboot, bh.reboot_reason, bh.system_uptime, bh.boot_time, bh.docker_enabled, bh.compliance_enabled, bh.compliance_on_demand_only, bh.last_update, bh.ssg_version, bh.first_group_name,
           COALESCE(hp.updates_count, 0)::int AS updates_count,
           COALESCE(hp.security_count, 0)::int AS security_updates_count,
           COALESCE(hp.total_count, 0)::int AS total_packages_count,
           (bh.status = 'active' AND bh.last_update < $12::timestamp) AS is_stale,
           CASE
               WHEN bh.status = 'active' AND bh.last_update < $12::timestamp THEN 'inactive'
               ELSE bh.status
           END AS effective_status,
           ((CASE WHEN bh.docker_enabled THEN 1 ELSE 0 END) + (CASE WHEN bh.compliance_enabled THEN 1 ELSE 0 END))::int AS integrations_count,
           CASE
               WHEN bh.last_update IS NULL THEN 'stale'
               WHEN bh.last_update >= $13::timestamp THEN 'reporting'
               WHEN bh.last_update >= $12::timestamp THEN 'overdue'
               ELSE 'stale'
           END AS reporting_state,
           CASE
               WHEN COALESCE(hp.security_count, 0) > 0 THEN 'security_required'
               WHEN COALESCE(hp.updates_count, 0) > 0 THEN 'updates_pending'
               ELSE 'up_to_date'
           END AS update_state
    FROM base_hosts bh
    LEFT JOIN hp_counts hp ON hp.host_id = bh.id
),
filtered_hosts AS (
    SELECT id, machine_id, friendly_name, hostname, ip, os_type, os_version, status, agent_version, auto_update, notes, api_id, needs_reboot, reboot_reason, system_uptime, boot_time, docker_enabled, compliance_enabled, compliance_on_demand_only, last_update, ssg_version, first_group_name, updates_count, security_updates_count, total_packages_count, is_stale, effective_status, integrations_count, reporting_state, update_state
    FROM enriched_hosts
    WHERE (
        $10::text IS NULL
        OR ($10 = 'needsUpdates' AND updates_count > 0)
        OR ($10 = 'inactive' AND effective_status = 'inactive')
        -- "Up to date" requires package data. A host we have never received
        -- packages from is not healthy, it is unknown: see filter 'awaitingData'.
        OR ($10 = 'upToDate' AND is_stale = false AND total_packages_count > 0 AND updates_count = 0)
        OR ($10 = 'awaitingData' AND total_packages_count = 0)
        OR ($10 = 'stale' AND is_stale = true)
        OR ($10 = 'selected')
    )
    AND ($14::boolean = false OR needs_reboot = true)
    AND ($15::boolean = false OR is_stale = false)
)
SELECT id, machine_id, friendly_name, hostname, ip, os_type, os_version,
    status, agent_version, auto_update, notes, api_id,
    needs_reboot, reboot_reason, system_uptime, boot_time, docker_enabled, compliance_enabled, compliance_on_demand_only,
    last_update, ssg_version, updates_count, security_updates_count, total_packages_count,
    reporting_state, update_state
FROM filtered_hosts
ORDER BY
    CASE WHEN $1::text = 'friendly_name'      AND $2::text = 'asc'  THEN friendly_name END ASC,
    CASE WHEN $1::text = 'friendly_name'      AND $2::text = 'desc' THEN friendly_name END DESC,
    CASE WHEN $1::text = 'hostname'           AND $2::text = 'asc'  THEN hostname END ASC NULLS LAST,
    CASE WHEN $1::text = 'hostname'           AND $2::text = 'desc' THEN hostname END DESC NULLS LAST,
    CASE WHEN $1::text = 'ip'                 AND $2::text = 'asc'  THEN ip END ASC NULLS LAST,
    CASE WHEN $1::text = 'ip'                 AND $2::text = 'desc' THEN ip END DESC NULLS LAST,
    CASE WHEN $1::text = 'group'              AND $2::text = 'asc'  THEN first_group_name END ASC,
    CASE WHEN $1::text = 'group'              AND $2::text = 'desc' THEN first_group_name END DESC,
    CASE WHEN $1::text = 'os_type'            AND $2::text = 'asc'  THEN os_type END ASC,
    CASE WHEN $1::text = 'os_type'            AND $2::text = 'desc' THEN os_type END DESC,
    CASE WHEN $1::text = 'os_version'         AND $2::text = 'asc'  THEN os_version END ASC,
    CASE WHEN $1::text = 'os_version'         AND $2::text = 'desc' THEN os_version END DESC,
    CASE WHEN $1::text = 'agent_version'      AND $2::text = 'asc'  THEN agent_version END ASC NULLS LAST,
    CASE WHEN $1::text = 'agent_version'      AND $2::text = 'desc' THEN agent_version END DESC NULLS LAST,
    CASE WHEN $1::text = 'status'             AND $2::text = 'asc'  THEN effective_status END ASC,
    CASE WHEN $1::text = 'status'             AND $2::text = 'desc' THEN effective_status END DESC,
    CASE WHEN $1::text = 'updates'            AND $2::text = 'asc'  THEN updates_count END ASC,
    CASE WHEN $1::text = 'updates'            AND $2::text = 'desc' THEN updates_count END DESC,
    CASE WHEN $1::text = 'security_updates'   AND $2::text = 'asc'  THEN security_updates_count END ASC,
    CASE WHEN $1::text = 'security_updates'   AND $2::text = 'desc' THEN security_updates_count END DESC,
    CASE WHEN $1::text = 'needs_reboot'       AND $2::text = 'asc'  THEN needs_reboot END ASC,
    CASE WHEN $1::text = 'needs_reboot'       AND $2::text = 'desc' THEN needs_reboot END DESC,
    -- 'uptime' sorts by boot_time with the direction inverted: longest uptime
    -- means earliest boot_time, so a "longest first" (desc) request maps to
    -- ORDER BY boot_time ASC. NULLS LAST keeps unreported hosts at the bottom
    -- regardless of direction.
    CASE WHEN $1::text = 'uptime'             AND $2::text = 'asc'  THEN boot_time END DESC NULLS LAST,
    CASE WHEN $1::text = 'uptime'             AND $2::text = 'desc' THEN boot_time END ASC  NULLS LAST,
    CASE WHEN $1::text = 'last_update'        AND $2::text = 'asc'  THEN last_update END ASC NULLS LAST,
    CASE WHEN $1::text = 'last_update'        AND $2::text = 'desc' THEN last_update END DESC NULLS LAST,
    CASE WHEN $1::text = 'ssg_version'        AND $2::text = 'asc'  THEN ssg_version END ASC NULLS LAST,
    CASE WHEN $1::text = 'ssg_version'        AND $2::text = 'desc' THEN ssg_version END DESC NULLS LAST,
    CASE WHEN $1::text = 'notes'              AND $2::text = 'asc'  THEN notes END ASC NULLS LAST,
    CASE WHEN $1::text = 'notes'              AND $2::text = 'desc' THEN notes END DESC NULLS LAST,
    CASE WHEN $1::text = 'integrations'       AND $2::text = 'asc'  THEN integrations_count END ASC,
    CASE WHEN $1::text = 'integrations'       AND $2::text = 'desc' THEN integrations_count END DESC,
    -- Default sort (also the tiebreaker for every key above): newest activity first.
    last_update DESC NULLS LAST,
    id ASC -- stable ordering across paginated requests
LIMIT  $4::int
OFFSET $3::int
`

type GetHostsWithCountsParams struct {
	SortKey          string           `json:"sort_key"`
	SortDir          string           `json:"sort_dir"`
	RowOffset        int32            `json:"row_offset"`
	RowLimit         int32            `json:"row_limit"`
	Search           *string          `json:"search"`
	Group            *string          `json:"group"`
	Status           *string          `json:"status"`
	Os               *string          `json:"os"`
	OsVersion        *string          `json:"os_version"`
	Filter           *string          `json:"filter"`
	SelectedIds      []string         `json:"selected_ids"`
	StaleThreshold   pgtype.Timestamp `json:"stale_threshold"`
	OverdueThreshold pgtype.Timestamp `json:"overdue_threshold"`
	RebootOnly       bool             `json:"reboot_only"`
	HideStale        bool             `json:"hide_stale"`
}

type GetHostsWithCountsRow struct {
	ID                     string             `json:"id"`
	MachineID              *string            `json:"machine_id"`
	FriendlyName           string             `json:"friendly_name"`
	Hostname               *string            `json:"hostname"`
	Ip                     *string            `json:"ip"`
	OsType                 string             `json:"os_type"`
	OsVersion              string             `json:"os_version"`
	Status                 string             `json:"status"`
	AgentVersion           *string            `json:"agent_version"`
	AutoUpdate             bool               `json:"auto_update"`
	Notes                  *string            `json:"notes"`
	ApiID                  string             `json:"api_id"`
	NeedsReboot            *bool              `json:"needs_reboot"`
	RebootReason           *string            `json:"reboot_reason"`
	SystemUptime           *string            `json:"system_uptime"`
	BootTime               pgtype.Timestamptz `json:"boot_time"`
	DockerEnabled          bool               `json:"docker_enabled"`
	ComplianceEnabled      bool               `json:"compliance_enabled"`
	ComplianceOnDemandOnly bool               `json:"compliance_on_demand_only"`
	LastUpdate             pgtype.Timestamp   `json:"last_update"`
	SsgVersion             interface{}        `json:"ssg_version"`
	UpdatesCount           int32              `json:"updates_count"`
	SecurityUpdatesCount   int32              `json:"security_updates_count"`
	TotalPackagesCount     int32              `json:"total_packages_count"`
	ReportingState         string             `json:"reporting_state"`
	UpdateState            string             `json:"update_state"`
}

// Paginated host list for the Hosts UI. Filtering and ordering happen
// over the full matching set, then LIMIT/OFFSET selects the current page.
// That keeps header sorting correct across all hosts, not just the page
// already loaded in the browser.
func (q *Queries) GetHostsWithCounts(ctx context.Context, arg GetHostsWithCountsParams) ([]GetHostsWithCountsRow, error) {
	rows, err := q.db.Query(ctx, getHostsWithCounts,
		arg.SortKey,
		arg.SortDir,
		arg.RowOffset,
		arg.RowLimit,
		arg.Search,
		arg.Group,
		arg.Status,
		arg.Os,
		arg.OsVersion,
		arg.Filter,
		arg.SelectedIds,
		arg.StaleThreshold,
		arg.OverdueThreshold,
		arg.RebootOnly,
		arg.HideStale,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHostsWithCountsRow
	for rows.Next() {
		var i GetHostsWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.MachineID,
			&i.FriendlyName,
			&i.Hostname,
			&i.Ip,
			&i.OsType,
			&i.OsVersion,
			&i.Status,
			&i.AgentVersion,
			&i.AutoUpdate,
			&i.Notes,
			&i.ApiID,
			&i.NeedsReboot,
			&i.RebootReason,
			&i.SystemUptime,
			&i.BootTime,
			&i.DockerEnabled,
			&i.ComplianceEnabled,
			&i.ComplianceOnDemandOnly,
			&i.LastUpdate,
			&i.SsgVersion,
			&i.UpdatesCount,
			&i.SecurityUpdatesCount,
			&i.TotalPackagesCount,
			&i.ReportingState,
			&i.UpdateState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHostsWithPageCounts = `-- name: GetHostsWithPageCounts :many
WITH base_hosts AS (
    SELECT h.id, h.machine_id, h.friendly_name, h.hostname, h.ip, h.os_type, h.os_version,
        h.status, h.agent_version, h.auto_update, h.notes, h.api_id,
        h.needs_reboot, h.reboot_reason, h.system_uptime, h.boot_time, h.docker_enabled, h.compliance_enabled, h.compliance_on_demand_only,
        h.last_update,
        h.compliance_scanner_status->'scanner_info'->>'ssg_version' as ssg_version,
        COALESCE((
            SELECT MIN(hg.name)
            FROM host_group_memberships hgm
            JOIN host_groups hg ON hg.id = hgm.host_group_id
            WHERE hgm.host_id = h.id
        ), '')::text AS first_group_name,
        (h.status = 'active' AND h.last_update < $3::timestamp) AS is_stale,
        CASE
            WHEN h.status = 'active' AND h.last_update < $3::timestamp THEN 'inactive'
            ELSE h.status
        END AS effective_status,
        ((CASE WHEN h.docker_enabled THEN 1 ELSE 0 END) + (CASE WHEN h.compliance_enabled THEN 1 ELSE 0 END))::int AS integrations_count,
        CASE
            WHEN h.last_update IS NULL THEN 'stale'
            WHEN h.last_update >= $4::timestamp THEN 'reporting'
            WHEN h.last_update >= $3::timestamp THEN 'overdue'
            ELSE 'stale'
        END AS reporting_state
    FROM hosts h
    WHERE ($5::text IS NULL OR h.friendly_name ILIKE '%' || $5 || '%' OR h.hostname ILIKE '%' || $5 || '%' OR h.ip ILIKE '%' || $5 || '%' OR h.os_type ILIKE '%' || $5 || '%' OR h.notes ILIKE '%' || $5 || '%')
    AND (
        $6::text IS NULL
        OR ($6 = 'ungrouped' AND NOT EXISTS (SELECT 1 FROM host_group_memberships hgm WHERE hgm.host_id = h.id))
        OR ($6 != 'ungrouped' AND EXISTS (SELECT 1 FROM host_group_memberships hgm WHERE hgm.host_id = h.id AND hgm.host_group_id = $6))
    )
    AND ($7::text IS NULL OR h.status = $7)
    AND ($8::text IS NULL OR h.os_type ILIKE $8)
    AND ($9::text IS NULL OR h.os_version ILIKE $9)
    AND (
        $10::text IS DISTINCT FROM 'selected'
        OR h.id = ANY($11::text[])
    )
),
filtered_hosts AS (
    SELECT id, machine_id, friendly_name, hostname, ip, os_type, os_version, status, agent_version, auto_update, notes, api_id, needs_reboot, reboot_reason, system_uptime, boot_time, docker_enabled, compliance_enabled, compliance_on_demand_only, last_update, ssg_version, first_group_name, is_stale, effective_status, integrations_count, reporting_state
    FROM base_hosts bh
    WHERE (
        $10::text IS NULL
        OR ($10 = 'needsUpdates' AND EXISTS (
            SELECT 1 FROM host_packages hp WHERE hp.host_id = bh.id AND hp.needs_update
        ))
        OR ($10 = 'inactive' AND bh.effective_status = 'inactive')
        OR ($10 = 'upToDate' AND bh.is_stale = false AND EXISTS (
            SELECT 1 FROM host_packages hp WHERE hp.host_id = bh.id
        ) AND NOT EXISTS (
            SELECT 1 FROM host_packages hp WHERE hp.host_id = bh.id AND hp.needs_update
        ))
        OR ($10 = 'awaitingData' AND NOT EXISTS (
            SELECT 1 FROM host_packages hp WHERE hp.host_id = bh.id
        ))
        OR ($10 = 'stale' AND bh.is_stale = true)
        OR ($10 = 'selected')
    )
    AND ($12::boolean = false OR bh.needs_reboot = true)
    AND ($13::boolean = false OR bh.is_stale = false)
),
ordered_page AS (
    SELECT id, machine_id, friendly_name, hostname, ip, os_type, os_version, status, agent_version, auto_update, notes, api_id, needs_reboot, reboot_reason, system_uptime, boot_time, docker_enabled, compliance_enabled, compliance_on_demand_only, last_update, ssg_version, first_group_name, is_stale, effective_status, integrations_count, reporting_state
    FROM filtered_hosts
    ORDER BY
        CASE WHEN $1::text = 'friendly_name'    AND $2::text = 'asc'  THEN friendly_name END ASC,
        CASE WHEN $1::text = 'friendly_name'    AND $2::text = 'desc' THEN friendly_name END DESC,
        CASE WHEN $1::text = 'hostname'         AND $2::text = 'asc'  THEN hostname END ASC NULLS LAST,
        CASE WHEN $1::text = 'hostname'         AND $2::text = 'desc' THEN hostname END DESC NULLS LAST,
        CASE WHEN $1::text = 'ip'               AND $2::text = 'asc'  THEN ip END ASC NULLS LAST,
        CASE WHEN $1::text = 'ip'               AND $2::text = 'desc' THEN ip END DESC NULLS LAST,
        CASE WHEN $1::text = 'group'            AND $2::text = 'asc'  THEN first_group_name END ASC,
        CASE WHEN $1::text = 'group'            AND $2::text = 'desc' THEN first_group_name END DESC,
        CASE WHEN $1::text = 'os_type'          AND $2::text = 'asc'  THEN os_type END ASC,
        CASE WHEN $1::text = 'os_type'          AND $2::text = 'desc' THEN os_type END DESC,
        CASE WHEN $1::text = 'os_version'       AND $2::text = 'asc'  THEN os_version END ASC,
        CASE WHEN $1::text = 'os_version'       AND $2::text = 'desc' THEN os_version END DESC,
        CASE WHEN $1::text = 'agent_version'    AND $2::text = 'asc'  THEN agent_version END ASC NULLS LAST,
        CASE WHEN $1::text = 'agent_version'    AND $2::text = 'desc' THEN agent_version END DESC NULLS LAST,
        CASE WHEN $1::text = 'status'           AND $2::text = 'asc'  THEN effective_status END ASC,
        CASE WHEN $1::text = 'status'           AND $2::text = 'desc' THEN effective_status END DESC,
        CASE WHEN $1::text = 'needs_reboot'     AND $2::text = 'asc'  THEN needs_reboot END ASC,
        CASE WHEN $1::text = 'needs_reboot'     AND $2::text = 'desc' THEN needs_reboot END DESC,
        -- See note above on the GetHostsWithCounts ORDER BY: 'uptime' sorts by
        -- boot_time with direction inverted (longest uptime = earliest boot).
        CASE WHEN $1::text = 'uptime'           AND $2::text = 'asc'  THEN boot_time END DESC NULLS LAST,
        CASE WHEN $1::text = 'uptime'           AND $2::text = 'desc' THEN boot_time END ASC  NULLS LAST,
        CASE WHEN $1::text = 'last_update'      AND $2::text = 'asc'  THEN last_update END ASC NULLS LAST,
        CASE WHEN $1::text = 'last_update'      AND $2::text = 'desc' THEN last_update END DESC NULLS LAST,
        CASE WHEN $1::text = 'ssg_version'      AND $2::text = 'asc'  THEN ssg_version END ASC NULLS LAST,
        CASE WHEN $1::text = 'ssg_version'      AND $2::text = 'desc' THEN ssg_version END DESC NULLS LAST,
        CASE WHEN $1::text = 'notes'            AND $2::text = 'asc'  THEN notes END ASC NULLS LAST,
        CASE WHEN $1::text = 'notes'            AND $2::text = 'desc' THEN notes END DESC NULLS LAST,
        CASE WHEN $1::text = 'integrations'     AND $2::text = 'asc'  THEN integrations_count END ASC,
        CASE WHEN $1::text = 'integrations'     AND $2::text = 'desc' THEN integrations_count END DESC,
        last_update DESC NULLS LAST,
        id ASC
    LIMIT  $15::int
    OFFSET $14::int
),
page_counts AS (
    SELECT hp.host_id,
           COUNT(*) FILTER (WHERE hp.needs_update)::int                          AS updates_count,
           COUNT(*) FILTER (WHERE hp.needs_update AND hp.is_security_update)::int AS security_count,
           COUNT(*)::int                                                         AS total_count
    FROM host_packages hp
    JOIN ordered_page op ON op.id = hp.host_id
    GROUP BY hp.host_id
)
SELECT op.id, op.machine_id, op.friendly_name, op.hostname, op.ip, op.os_type, op.os_version,
    op.status, op.agent_version, op.auto_update, op.notes, op.api_id,
    op.needs_reboot, op.reboot_reason, op.system_uptime, op.boot_time, op.docker_enabled, op.compliance_enabled, op.compliance_on_demand_only,
    op.last_update, op.ssg_version,
    COALESCE(pc.updates_count, 0)::int AS updates_count,
    COALESCE(pc.security_count, 0)::int AS security_updates_count,
    COALESCE(pc.total_count, 0)::int AS total_packages_count,
    op.reporting_state,
    CASE
        WHEN COALESCE(pc.security_count, 0) > 0 THEN 'security_required'
        WHEN COALESCE(pc.updates_count, 0) > 0 THEN 'updates_pending'
        ELSE 'up_to_date'
    END AS update_state
FROM ordered_page op
LEFT JOIN page_counts pc ON pc.host_id = op.id
ORDER BY
    CASE WHEN $1::text = 'friendly_name'    AND $2::text = 'asc'  THEN op.friendly_name END ASC,
    CASE WHEN $1::text = 'friendly_name'    AND $2::text = 'desc' THEN op.friendly_name END DESC,
    CASE WHEN $1::text = 'hostname'         AND $2::text = 'asc'  THEN op.hostname END ASC NULLS LAST,
    CASE WHEN $1::text = 'hostname'         AND $2::text = 'desc' THEN op.hostname END DESC NULLS LAST,
    CASE WHEN $1::text = 'ip'               AND $2::text = 'asc'  THEN op.ip END ASC NULLS LAST,
    CASE WHEN $1::text = 'ip'               AND $2::text = 'desc' THEN op.ip END DESC NULLS LAST,
    CASE WHEN $1::text = 'group'            AND $2::text = 'asc'  THEN op.first_group_name END ASC,
    CASE WHEN $1::text = 'group'            AND $2::text = 'desc' THEN op.first_group_name END DESC,
    CASE WHEN $1::text = 'os_type'          AND $2::text = 'asc'  THEN op.os_type END ASC,
    CASE WHEN $1::text = 'os_type'          AND $2::text = 'desc' THEN op.os_type END DESC,
    CASE WHEN $1::text = 'os_version'       AND $2::text = 'asc'  THEN op.os_version END ASC,
    CASE WHEN $1::text = 'os_version'       AND $2::text = 'desc' THEN op.os_version END DESC,
    CASE WHEN $1::text = 'agent_version'    AND $2::text = 'asc'  THEN op.agent_version END ASC NULLS LAST,
    CASE WHEN $1::text = 'agent_version'    AND $2::text = 'desc' THEN op.agent_version END DESC NULLS LAST,
    CASE WHEN $1::text = 'status'           AND $2::text = 'asc'  THEN op.effective_status END ASC,
    CASE WHEN $1::text = 'status'           AND $2::text = 'desc' THEN op.effective_status END DESC,
    CASE WHEN $1::text = 'needs_reboot'     AND $2::text = 'asc'  THEN op.needs_reboot END ASC,
    CASE WHEN $1::text = 'needs_reboot'     AND $2::text = 'desc' THEN op.needs_reboot END DESC,
    -- Inverted direction: longest uptime = earliest boot_time.
    CASE WHEN $1::text = 'uptime'           AND $2::text = 'asc'  THEN op.boot_time END DESC NULLS LAST,
    CASE WHEN $1::text = 'uptime'           AND $2::text = 'desc' THEN op.boot_time END ASC  NULLS LAST,
    CASE WHEN $1::text = 'last_update'      AND $2::text = 'asc'  THEN op.last_update END ASC NULLS LAST,
    CASE WHEN $1::text = 'last_update'      AND $2::text = 'desc' THEN op.last_update END DESC NULLS LAST,
    CASE WHEN $1::text = 'ssg_version'      AND $2::text = 'asc'  THEN op.ssg_version END ASC NULLS LAST,
    CASE WHEN $1::text = 'ssg_version'      AND $2::text = 'desc' THEN op.ssg_version END DESC NULLS LAST,
    CASE WHEN $1::text = 'notes'            AND $2::text = 'asc'  THEN op.notes END ASC NULLS LAST,
    CASE WHEN $1::text = 'notes'            AND $2::text = 'desc' THEN op.notes END DESC NULLS LAST,
    CASE WHEN $1::text = 'integrations'     AND $2::text = 'asc'  THEN op.integrations_count END ASC,
    CASE WHEN $1::text = 'integrations'     AND $2::text = 'desc' THEN op.integrations_count END DESC,
    op.last_update DESC NULLS LAST,
    op.id ASC
`

type GetHostsWithPageCountsParams struct {
	SortKey          string           `json:"sort_key"`
	SortDir          string           `json:"sort_dir"`
	StaleThreshold   pgtype.Timestamp `json:"stale_threshold"`
	OverdueThreshold pgtype.Timestamp `json:"overdue_threshold"`
	Search           *string          `json:"search"`
	Group            *string          `json:"group"`
	Status           *string          `json:"status"`
	Os               *string          `json:"os"`
	OsVersion        *string          `json:"os_version"`
	Filter           *string          `json:"filter"`
	SelectedIds      []string         `json:"selected_ids"`
	RebootOnly       bool             `json:"reboot_only"`
	HideStale        bool             `json:"hide_stale"`
	RowOffset        int32            `json:"row_offset"`
	RowLimit         int32            `json:"row_limit"`
}

type GetHostsWithPageCountsRow struct {
	ID                     string             `json:"id"`
	MachineID              *string            `json:"machine_id"`
	FriendlyName           string             `json:"friendly_name"`
	Hostname               *string            `json:"hostname"`
	Ip                     *string            `json:"ip"`
	OsType                 string             `json:"os_type"`
	OsVersion              string             `json:"os_version"`
	Status                 string             `json:"status"`
	AgentVersion           *string            `json:"agent_version"`
	AutoUpdate             bool               `json:"auto_update"`
	Notes                  *string            `json:"notes"`
	ApiID                  string             `json:"api_id"`
	NeedsReboot            *bool              `json:"needs_reboot"`
	RebootReason           *string            `json:"reboot_reason"`
	SystemUptime           *string            `json:"system_uptime"`
	BootTime               pgtype.Timestamptz `json:"boot_time"`
	DockerEnabled          bool               `json:"docker_enabled"`
	ComplianceEnabled      bool               `json:"compliance_enabled"`
	ComplianceOnDemandOnly bool               `json:"compliance_on_demand_only"`
	LastUpdate             pgtype.Timestamp   `json:"last_update"`
	SsgVersion             interface{}        `json:"ssg_version"`
	UpdatesCount           int32              `json:"updates_count"`
	SecurityUpdatesCount   int32              `json:"security_updates_count"`
	TotalPackagesCount     int32              `json:"total_packages_count"`
	ReportingState         string             `json:"reporting_state"`
	UpdateState            string             `json:"update_state"`
}

// Fast path for host-column sorting: order/page hosts first, then aggregate
// package counts only for the visible page. Package-count sorting uses
// GetHostsWithCounts so the sort still applies across the full filtered set.
func (q *Queries) GetHostsWithPageCounts(ctx context.Context, arg GetHostsWithPageCountsParams) ([]GetHostsWithPageCountsRow, error) {
	rows, err := q.db.Query(ctx, getHostsWithPageCounts,
		arg.SortKey,
		arg.SortDir,
		arg.StaleThreshold,
		arg.OverdueThreshold,
		arg.Search,
		arg.Group,
		arg.Status,
		arg.Os,
		arg.OsVersion,
		arg.Filter,
		arg.SelectedIds,
		arg.RebootOnly,
		arg.HideStale,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHostsWithPageCountsRow
	for rows.Next() {
		var i GetHostsWithPageCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.MachineID,
			&i.FriendlyName,
			&i.Hostname,
			&i.Ip,
			&i.OsType,
			&i.OsVersion,
			&i.Status,
			&i.AgentVersion,
			&i.AutoUpdate,
			&i.Notes,
			&i.ApiID,
			&i.NeedsReboot,
			&i.RebootReason,
			&i.SystemUptime,
			&i.BootTime,
			&i.DockerEnabled,
			&i.ComplianceEnabled,
			&i.ComplianceOnDemandOnly,
			&i.LastUpdate,
			&i.SsgVersion,
			&i.UpdatesCount,
			&i.SecurityUpdatesCount,
			&i.TotalPackagesCount,
			&i.ReportingState,
			&i.UpdateState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNavigationStats = `-- name: GetNavigationStats :one
SELECT
    (SELECT COUNT(*)::int FROM hosts) AS total_hosts,
    (SELECT COUNT(*)::int FROM repositories) AS total_repos,
    COALESCE((
        SELECT unique_packages_count::int
        FROM system_statistics
        ORDER BY timestamp DESC
        LIMIT 1
    ), 0)::int AS total_outdated_packages,
    NOW()::timestamp AS last_updated
`

type GetNavigationStatsRow struct {
	TotalHosts            int32            `json:"total_hosts"`
	TotalRepos            int32            `json:"total_repos"`
	TotalOutdatedPackages int32            `json:"total_outdated_packages"`
	LastUpdated           pgtype.Timestamp `json:"last_updated"`
}

func (q *Queries) GetNavigationStats(ctx context.Context) (GetNavigationStatsRow, error) {
	row := q.db.QueryRow(ctx, getNavigationStats)
	var i GetNavigationStatsRow
	err := row.Scan(
		&i.TotalHosts,
		&i.TotalRepos,
		&i.TotalOutdatedPackages,
		&i.LastUpdated,
	)
	return i, err
}

const getOSDistribution = `-- name: GetOSDistribution :many
SELECT os_type as name, COUNT(*)::int as count FROM hosts WHERE status = 'active' GROUP BY os_type
`

type GetOSDistributionRow struct {
	Name  string `json:"name"`
	Count int32  `json:"count"`
}

func (q *Queries) GetOSDistribution(ctx context.Context) ([]GetOSDistributionRow, error) {
	rows, err := q.db.Query(ctx, getOSDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOSDistributionRow
	for rows.Next() {
		var i GetOSDistributionRow
		if err := rows.Scan(&i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOSDistributionByTypeAndVersion = `-- name: GetOSDistributionByTypeAndVersion :many
SELECT os_type, os_version,
    (os_type || ' ' || os_version)::text as name,
    COUNT(*)::int as count
FROM hosts
WHERE status = 'active'
GROUP BY os_type, os_version
ORDER BY count DESC, os_type, os_version
`

type GetOSDistributionByTypeAndVersionRow struct {
	OsType    string `json:"os_type"`
	OsVersion string `json:"os_version"`
	Name      string `json:"name"`
	Count     int32  `json:"count"`
}

func (q *Queries) GetOSDistributionByTypeAndVersion(ctx context.Context) ([]GetOSDistributionByTypeAndVersionRow, error) {
	rows, err := q.db.Query(ctx, getOSDistributionByTypeAndVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOSDistributionByTypeAndVersionRow
	for rows.Next() {
		var i GetOSDistributionByTypeAndVersionRow
		if err := rows.Scan(
			&i.OsType,
			&i.OsVersion,
			&i.Name,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentHosts = `-- name: GetRecentHosts :many
SELECT id, friendly_name, hostname, last_update, status
FROM hosts ORDER BY last_update DESC LIMIT $1
`

type GetRecentHostsRow struct {
	ID           string           `json:"id"`
	FriendlyName string           `json:"friendly_name"`
	Hostname     *string          `json:"hostname"`
	LastUpdate   pgtype.Timestamp `json:"last_update"`
	Status       string           `json:"status"`
}

func (q *Queries) GetRecentHosts(ctx context.Context, limit int32) ([]GetRecentHostsRow, error) {
	rows, err := q.db.Query(ctx, getRecentHosts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentHostsRow
	for rows.Next() {
		var i GetRecentHostsRow
		if err := rows.Scan(
			&i.ID,
			&i.FriendlyName,
			&i.Hostname,
			&i.LastUpdate,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentUsers = `-- name: GetRecentUsers :many
SELECT id, username, email, first_name, last_name, role, last_login, created_at, avatar_url
FROM users WHERE last_login IS NOT NULL ORDER BY last_login DESC LIMIT $1
`

type GetRecentUsersRow struct {
	ID        string           `json:"id"`
	Username  string           `json:"username"`
	Email     string           `json:"email"`
	FirstName *string          `json:"first_name"`
	LastName  *string          `json:"last_name"`
	Role      string           `json:"role"`
	LastLogin pgtype.Timestamp `json:"last_login"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	AvatarUrl *string          `json:"avatar_url"`
}

func (q *Queries) GetRecentUsers(ctx context.Context, limit int32) ([]GetRecentUsersRow, error) {
	rows, err := q.db.Query(ctx, getRecentUsers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentUsersRow
	for rows.Next() {
		var i GetRecentUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Role,
			&i.LastLogin,
			&i.CreatedAt,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpdateHistory = `-- name: GetUpdateHistory :many
SELECT id, host_id, packages_count, security_count, total_packages,
    payload_size_kb, execution_time, timestamp, status, error_message
FROM update_history
WHERE host_id = $1
  AND report_type IN ('full', 'partial')
ORDER BY timestamp DESC
LIMIT $2 OFFSET $3
`

type GetUpdateHistoryParams struct {
	HostID string `json:"host_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type GetUpdateHistoryRow struct {
	ID            string           `json:"id"`
	HostID        string           `json:"host_id"`
	PackagesCount int32            `json:"packages_count"`
	SecurityCount int32            `json:"security_count"`
	TotalPackages *int32           `json:"total_packages"`
	PayloadSizeKb *float64         `json:"payload_size_kb"`
	ExecutionTime *float64         `json:"execution_time"`
	Timestamp     pgtype.Timestamp `json:"timestamp"`
	Status        string           `json:"status"`
	ErrorMessage  *string          `json:"error_message"`
}

func (q *Queries) GetUpdateHistory(ctx context.Context, arg GetUpdateHistoryParams) ([]GetUpdateHistoryRow, error) {
	rows, err := q.db.Query(ctx, getUpdateHistory, arg.HostID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUpdateHistoryRow
	for rows.Next() {
		var i GetUpdateHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.PackagesCount,
			&i.SecurityCount,
			&i.TotalPackages,
			&i.PayloadSizeKb,
			&i.ExecutionTime,
			&i.Timestamp,
			&i.Status,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpdateHistoryDaily = `-- name: GetUpdateHistoryDaily :many
SELECT DATE(timestamp)::text as ts,
    MAX(packages_count)::int as packages_count,
    MAX(security_count)::int as security_count,
    MAX(COALESCE(total_packages, 0))::int as total_packages
FROM update_history
WHERE host_id = $1 AND timestamp >= $2 AND timestamp <= $3 AND status = 'success'
  AND report_type IN ('full', 'partial')
  AND COALESCE(total_packages, 0) >= 0
  AND packages_count >= 0
  AND security_count >= 0
  AND security_count <= packages_count
GROUP BY DATE(timestamp)
ORDER BY ts
`

type GetUpdateHistoryDailyParams struct {
	HostID      string           `json:"host_id"`
	Timestamp   pgtype.Timestamp `json:"timestamp"`
	Timestamp_2 pgtype.Timestamp `json:"timestamp_2"`
}

type GetUpdateHistoryDailyRow struct {
	Ts            string `json:"ts"`
	PackagesCount int32  `json:"packages_count"`
	SecurityCount int32  `json:"security_count"`
	TotalPackages int32  `json:"total_packages"`
}

func (q *Queries) GetUpdateHistoryDaily(ctx context.Context, arg GetUpdateHistoryDailyParams) ([]GetUpdateHistoryDailyRow, error) {
	rows, err := q.db.Query(ctx, getUpdateHistoryDaily, arg.HostID, arg.Timestamp, arg.Timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUpdateHistoryDailyRow
	for rows.Next() {
		var i GetUpdateHistoryDailyRow
		if err := rows.Scan(
			&i.Ts,
			&i.PackagesCount,
			&i.SecurityCount,
			&i.TotalPackages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpdateTrends = `-- name: GetUpdateTrends :many
SELECT DATE(timestamp) as ts, COUNT(*)::int as cnt,
    COALESCE(SUM(packages_count), 0)::int as pkg_sum,
    COALESCE(SUM(security_count), 0)::int as sec_sum
FROM update_history
WHERE timestamp >= $1
  AND report_type IN ('full', 'partial')
GROUP BY DATE(timestamp)
ORDER BY ts
`

type GetUpdateTrendsRow struct {
	Ts     pgtype.Date `json:"ts"`
	Cnt    int32       `json:"cnt"`
	PkgSum int32       `json:"pkg_sum"`
	SecSum int32       `json:"sec_sum"`
}

func (q *Queries) GetUpdateTrends(ctx context.Context, timestamp pgtype.Timestamp) ([]GetUpdateTrendsRow, error) {
	rows, err := q.db.Query(ctx, getUpdateTrends, timestamp)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUpdateTrendsRow
	for rows.Next() {
		var i GetUpdateTrendsRow
		if err := rows.Scan(
			&i.Ts,
			&i.Cnt,
			&i.PkgSum,
			&i.SecSum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpdateHistoryByDateRange = `-- name: ListUpdateHistoryByDateRange :many
SELECT id, host_id, packages_count, security_count, total_packages,
    payload_size_kb, execution_time, timestamp, status, error_message
FROM update_history
WHERE host_id = $1 AND timestamp >= $2 AND timestamp <= $3 AND status = 'success'
  AND report_type IN ('full', 'partial')
ORDER BY timestamp ASC
`

type ListUpdateHistoryByDateRangeParams struct {
	HostID      string           `json:"host_id"`
	Timestamp   pgtype.Timestamp `json:"timestamp"`
	Timestamp_2 pgtype.Timestamp `json:"timestamp_2"`
}

type ListUpdateHistoryByDateRangeRow struct {
	ID            string           `json:"id"`
	HostID        string           `json:"host_id"`
	PackagesCount int32            `json:"packages_count"`
	SecurityCount int32            `json:"security_count"`
	TotalPackages *int32           `json:"total_packages"`
	PayloadSizeKb *float64         `json:"payload_size_kb"`
	ExecutionTime *float64         `json:"execution_time"`
	Timestamp     pgtype.Timestamp `json:"timestamp"`
	Status        string           `json:"status"`
	ErrorMessage  *string          `json:"error_message"`
}

func (q *Queries) ListUpdateHistoryByDateRange(ctx context.Context, arg ListUpdateHistoryByDateRangeParams) ([]ListUpdateHistoryByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, listUpdateHistoryByDateRange, arg.HostID, arg.Timestamp, arg.Timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUpdateHistoryByDateRangeRow
	for rows.Next() {
		var i ListUpdateHistoryByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.PackagesCount,
			&i.SecurityCount,
			&i.TotalPackages,
			&i.PayloadSizeKb,
			&i.ExecutionTime,
			&i.Timestamp,
			&i.Status,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
