// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: host_groups.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHostGroup = `-- name: CreateHostGroup :exec
INSERT INTO host_groups (id, name, description, color, created_at, updated_at) VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateHostGroupParams struct {
	ID          string           `json:"id"`
	Name        string           `json:"name"`
	Description *string          `json:"description"`
	Color       *string          `json:"color"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateHostGroup(ctx context.Context, arg CreateHostGroupParams) error {
	_, err := q.db.Exec(ctx, createHostGroup,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteHostGroup = `-- name: DeleteHostGroup :exec
DELETE FROM host_groups WHERE id = $1
`

func (q *Queries) DeleteHostGroup(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteHostGroup, id)
	return err
}

const deleteHostGroupMemberships = `-- name: DeleteHostGroupMemberships :exec
DELETE FROM host_group_memberships WHERE host_id = $1
`

func (q *Queries) DeleteHostGroupMemberships(ctx context.Context, hostID string) error {
	_, err := q.db.Exec(ctx, deleteHostGroupMemberships, hostID)
	return err
}

const getHostGroupByID = `-- name: GetHostGroupByID :one
SELECT id, name, description, color, created_at, updated_at FROM host_groups WHERE id = $1
`

func (q *Queries) GetHostGroupByID(ctx context.Context, id string) (HostGroup, error) {
	row := q.db.QueryRow(ctx, getHostGroupByID, id)
	var i HostGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHostGroupsForHosts = `-- name: GetHostGroupsForHosts :many
SELECT hgm.host_id, hg.id, hg.name, hg.description, hg.color, hg.created_at, hg.updated_at
FROM host_group_memberships hgm
JOIN host_groups hg ON hg.id = hgm.host_group_id
WHERE hgm.host_id = ANY($1::text[])
ORDER BY hgm.host_id, hg.name
`

type GetHostGroupsForHostsRow struct {
	HostID      string           `json:"host_id"`
	ID          string           `json:"id"`
	Name        string           `json:"name"`
	Description *string          `json:"description"`
	Color       *string          `json:"color"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetHostGroupsForHosts(ctx context.Context, dollar_1 []string) ([]GetHostGroupsForHostsRow, error) {
	rows, err := q.db.Query(ctx, getHostGroupsForHosts, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHostGroupsForHostsRow
	for rows.Next() {
		var i GetHostGroupsForHostsRow
		if err := rows.Scan(
			&i.HostID,
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHostIDsByGroup = `-- name: GetHostIDsByGroup :many
SELECT host_id FROM host_group_memberships WHERE host_group_id = $1
`

func (q *Queries) GetHostIDsByGroup(ctx context.Context, hostGroupID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getHostIDsByGroup, hostGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var host_id string
		if err := rows.Scan(&host_id); err != nil {
			return nil, err
		}
		items = append(items, host_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHostIDsByGroupIDs = `-- name: GetHostIDsByGroupIDs :many
SELECT DISTINCT host_id FROM host_group_memberships WHERE host_group_id = ANY($1::text[])
`

func (q *Queries) GetHostIDsByGroupIDs(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, getHostIDsByGroupIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var host_id string
		if err := rows.Scan(&host_id); err != nil {
			return nil, err
		}
		items = append(items, host_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hostInHostGroup = `-- name: HostInHostGroup :one
SELECT EXISTS (
    SELECT 1 FROM host_group_memberships WHERE host_id = $1 AND host_group_id = $2
) AS exists
`

type HostInHostGroupParams struct {
	HostID      string `json:"host_id"`
	HostGroupID string `json:"host_group_id"`
}

func (q *Queries) HostInHostGroup(ctx context.Context, arg HostInHostGroupParams) (bool, error) {
	row := q.db.QueryRow(ctx, hostInHostGroup, arg.HostID, arg.HostGroupID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertHostGroupMembership = `-- name: InsertHostGroupMembership :exec
INSERT INTO host_group_memberships (id, host_id, host_group_id) VALUES ($1, $2, $3)
ON CONFLICT (host_id, host_group_id) DO NOTHING
`

type InsertHostGroupMembershipParams struct {
	ID          string `json:"id"`
	HostID      string `json:"host_id"`
	HostGroupID string `json:"host_group_id"`
}

// ON CONFLICT: callers may pass the same group id twice, and the delete has
// already run by then.
func (q *Queries) InsertHostGroupMembership(ctx context.Context, arg InsertHostGroupMembershipParams) error {
	_, err := q.db.Exec(ctx, insertHostGroupMembership, arg.ID, arg.HostID, arg.HostGroupID)
	return err
}

const listHostGroups = `-- name: ListHostGroups :many
SELECT id, name, description, color, created_at, updated_at FROM host_groups ORDER BY name
`

func (q *Queries) ListHostGroups(ctx context.Context) ([]HostGroup, error) {
	rows, err := q.db.Query(ctx, listHostGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HostGroup
	for rows.Next() {
		var i HostGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostGroupsWithHostCount = `-- name: ListHostGroupsWithHostCount :many
SELECT hg.id, hg.name, hg.description, hg.color, hg.created_at, hg.updated_at,
       COUNT(hgm.host_id)::int AS host_count
FROM host_groups hg
LEFT JOIN host_group_memberships hgm ON hgm.host_group_id = hg.id
GROUP BY hg.id, hg.name, hg.description, hg.color, hg.created_at, hg.updated_at
ORDER BY hg.name
`

type ListHostGroupsWithHostCountRow struct {
	ID          string           `json:"id"`
	Name        string           `json:"name"`
	Description *string          `json:"description"`
	Color       *string          `json:"color"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	HostCount   int32            `json:"host_count"`
}

func (q *Queries) ListHostGroupsWithHostCount(ctx context.Context) ([]ListHostGroupsWithHostCountRow, error) {
	rows, err := q.db.Query(ctx, listHostGroupsWithHostCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHostGroupsWithHostCountRow
	for rows.Next() {
		var i ListHostGroupsWithHostCountRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HostCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHostGroup = `-- name: UpdateHostGroup :exec
UPDATE host_groups SET name = $1, description = $2, color = $3, updated_at = $4 WHERE id = $5
`

type UpdateHostGroupParams struct {
	Name        string           `json:"name"`
	Description *string          `json:"description"`
	Color       *string          `json:"color"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	ID          string           `json:"id"`
}

func (q *Queries) UpdateHostGroup(ctx context.Context, arg UpdateHostGroupParams) error {
	_, err := q.db.Exec(ctx, updateHostGroup,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
