// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: host_report.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkInsertHostPackages = `-- name: BulkInsertHostPackages :exec
INSERT INTO host_packages (
    id, host_id, package_id, current_version, available_version,
    needs_update, is_security_update, source_repository_id,
    wua_guid, wua_kb, wua_severity, wua_categories,
    wua_description, wua_support_url, wua_revision_number,
    last_checked
)
SELECT
    id, host_id, package_id, current_version,
    NULLIF(available_version, '')        AS available_version,
    needs_update, is_security_update,
    NULLIF(source_repository_id, '')     AS source_repository_id,
    NULLIF(wua_guid, '')                 AS wua_guid,
    NULLIF(wua_kb, '')                   AS wua_kb,
    NULLIF(wua_severity, '')             AS wua_severity,
    wua_categories,
    NULLIF(wua_description, '')          AS wua_description,
    NULLIF(wua_support_url, '')          AS wua_support_url,
    NULLIF(wua_revision_number, 0)       AS wua_revision_number,
    NOW()
FROM jsonb_to_recordset($1::jsonb)
    AS t(
        id text, host_id text, package_id text, current_version text,
        available_version text,
        needs_update boolean, is_security_update boolean,
        source_repository_id text,
        wua_guid text, wua_kb text, wua_severity text,
        wua_categories jsonb,
        wua_description text, wua_support_url text,
        wua_revision_number int
    )
ORDER BY package_id
`

// Bulk insert N host_packages rows in a single statement. Replaces the legacy
// InsertHostPackage and InsertHostPackageWithWUA per-row inserts — one path
// now covers Linux/FreeBSD (all wua_* columns NULL) and Windows (wua_* set).
//
// DeleteHostPackagesByHostID has already cleared this host's rows, so no
// ON CONFLICT clause is needed: the (host_id, package_id) UNIQUE constraint
// cannot fire.
//
// Caller pre-sorts by package_id (defensive — host_packages rows for one host
// cannot cross-host-deadlock because of host-partitioning, but consistent
// ordering is cheap insurance and aids index locality on (host_id, package_id)).
//
// Input shape: a single jsonb array of objects with one key per column.
//
// We use `jsonb_to_recordset` with a typed column list rather than
// `jsonb_array_elements + elem->>'col'` per column. The recordset variant
// parses each input element ONCE into a typed tuple; the array_elements
// variant re-enters the JSON parser for each `->>` operator (15 columns ×
// per-row = 15 lookups/row). Benchmarks at 10k packages show roughly a
// 3x decode speedup, which matters for the report-heavy workload at 100+
// hosts. JSON nulls become SQL NULLs directly so callers do not need
// empty-string sentinels — but the Go side still emits empty strings for
// text fields, which the NULLIF wrappers below collapse to NULL. Both
// conventions remain valid; do not change one without the other.
//
// wua_categories is stored as jsonb and is declared as a jsonb column in
// the recordset spec, so it round-trips as a real JSON value (array or
// null) without going through text serialisation.
func (q *Queries) BulkInsertHostPackages(ctx context.Context, payload []byte) error {
	_, err := q.db.Exec(ctx, bulkInsertHostPackages, payload)
	return err
}

const bulkUpsertPackages = `-- name: BulkUpsertPackages :many
WITH upserted AS (
    INSERT INTO packages (id, name, description, category, latest_version, created_at, updated_at)
    SELECT t.id, t.name, t.description, t.category, t.latest_version, NOW(), NOW()
    FROM jsonb_to_recordset($1::jsonb)
        AS t(id text, name text, description text, category text, latest_version text)
    ORDER BY t.name
    ON CONFLICT (name) DO UPDATE SET
        latest_version = COALESCE(EXCLUDED.latest_version, packages.latest_version),
        description    = COALESCE(EXCLUDED.description,    packages.description),
        category       = COALESCE(EXCLUDED.category,       packages.category),
        updated_at     = NOW()
    WHERE
           packages.latest_version IS DISTINCT FROM COALESCE(EXCLUDED.latest_version, packages.latest_version)
        OR packages.description    IS DISTINCT FROM COALESCE(EXCLUDED.description,    packages.description)
        OR packages.category       IS DISTINCT FROM COALESCE(EXCLUDED.category,       packages.category)
    RETURNING id, name
)
SELECT id, name FROM upserted
UNION ALL
SELECT p.id, p.name
FROM packages p
JOIN jsonb_to_recordset($1::jsonb)
    AS i(name text) USING (name)
WHERE NOT EXISTS (SELECT 1 FROM upserted u WHERE u.name = i.name)
`

type BulkUpsertPackagesRow struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// Bulk upsert N packages in a single statement, eliminating per-row round-trips.
//
// Caller MUST pre-sort the input rows by name AND deduplicate by name
// (deterministic lock acquisition; ON CONFLICT cannot affect the same row
// twice in one statement — cardinality_violation 21000). The inner ORDER BY
// name in the `input` CTE is belt-and-braces: PostgreSQL's executor processes
// INSERT...SELECT tuples in plan order, and the explicit Sort node above
// jsonb_to_recordset guarantees that order even if the planner introduces
// parallel workers (unlikely at this row count). Both layers must remain —
// do not strip the ORDER BY thinking the Go-side sort is sufficient. Sorted
// lock acquisition prevents the cross-host 40P01 deadlocks reported in
// production.
//
// Input shape: a single jsonb array of objects, each with keys
//
//	{ id, name, description, category, latest_version }
//
// We use jsonb_to_recordset rather than parallel text[]+unnest because sqlc
// v1.x's static analyzer cannot resolve the multi-array unnest() overload
// ("function unnest(unknown, ...) does not exist"). jsonb_to_recordset gives
// the same per-row shape with one well-typed parameter and zero overload
// ambiguity.
//
// Description / category / latest_version are JSON nulls when the agent
// omits them, which jsonb_to_recordset emits as SQL NULL directly.
//
// The DO UPDATE WHERE clause skips no-op updates: when the agent reports the
// same description/category/latest_version that's already stored, no row
// update happens and no dead tuple is created. Steady-state production
// workloads with mostly-stable package catalogues see ~95% of upsert calls
// become no-ops, drastically reducing WAL volume and vacuum pressure.
//
// It does NOT avoid the row lock: the ON CONFLICT arbiter takes its
// FOR NO KEY UPDATE lock on the conflicting tuple BEFORE evaluating this
// WHERE, and holds it to end of transaction whether or not the update
// fires. Deadlock freedom comes from the sorted lock acquisition above, not
// from this clause.
//
// The UNION ALL fallback returns (id, name) for input rows that did NOT fire
// DO UPDATE (i.e. the values are unchanged), covering the single-threaded
// case where every input name resolves to an id.
//
// It is NOT complete under concurrency. The ON CONFLICT arbiter re-reads the
// conflicting row outside the statement snapshot, so it can see a row another
// transaction committed after this statement began; if that row's values are
// identical the skip-no-op WHERE suppresses RETURNING, while the fallback
// SELECT still reads `packages` at the (older) statement snapshot and cannot
// see the row either. That name is then absent from the result. The caller
// MUST detect missing names and resolve them with GetPackageIDsByNames, which
// runs as a separate statement and therefore takes a fresh snapshot.
//
// The DO UPDATE intentionally touches only NON-KEY columns
// (description / category / latest_version / updated_at). The row lock taken
// by ON CONFLICT is therefore FOR NO KEY UPDATE, which does NOT conflict
// with FOR KEY SHARE locks held by concurrent BulkInsertHostPackages FK
// checks on the same packages.id rows. Do not extend this DO UPDATE to
// touch id or name without re-evaluating the lock-compatibility analysis.
// Fallback: input rows whose values matched the existing row exactly (so the
// skip-no-op WHERE made the DO UPDATE a no-op and RETURNING omitted them).
// Re-parsing the JSON here is cheap (kilobytes, in-memory) and avoids a
// per-row round-trip — the alternative was a SELECT loop in Go.
func (q *Queries) BulkUpsertPackages(ctx context.Context, payload []byte) ([]BulkUpsertPackagesRow, error) {
	rows, err := q.db.Query(ctx, bulkUpsertPackages, payload)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BulkUpsertPackagesRow
	for rows.Next() {
		var i BulkUpsertPackagesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteHostPackagesByHostID = `-- name: DeleteHostPackagesByHostID :exec
DELETE FROM host_packages WHERE host_id = $1
`

func (q *Queries) DeleteHostPackagesByHostID(ctx context.Context, hostID string) error {
	_, err := q.db.Exec(ctx, deleteHostPackagesByHostID, hostID)
	return err
}

const getPackageByName = `-- name: GetPackageByName :one
SELECT id, name, description, category, latest_version, created_at, updated_at
FROM packages WHERE name = $1
`

func (q *Queries) GetPackageByName(ctx context.Context, name string) (Package, error) {
	row := q.db.QueryRow(ctx, getPackageByName, name)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.LatestVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPackageIDsByNames = `-- name: GetPackageIDsByNames :many
SELECT id, name FROM packages WHERE name = ANY($1::text[])
`

type GetPackageIDsByNamesRow struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// Off-fast-path resolver for names BulkUpsertPackages could not return (see
// the concurrency note there). Issued as its own statement so it reads at a
// fresh snapshot and observes rows committed by concurrent reports. Takes no
// row locks. The caller only runs this when a name is actually missing.
//
// REQUIRES READ COMMITTED. Only under READ COMMITTED does a new statement take
// a new snapshot; at REPEATABLE READ or SERIALIZABLE this reuses the
// transaction snapshot, resolves nothing, and the race it exists to close
// silently returns. The pool sets no TxOptions, so the server default applies
// — do not raise it without revisiting this.
func (q *Queries) GetPackageIDsByNames(ctx context.Context, names []string) ([]GetPackageIDsByNamesRow, error) {
	rows, err := q.db.Query(ctx, getPackageIDsByNames, names)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPackageIDsByNamesRow
	for rows.Next() {
		var i GetPackageIDsByNamesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUpdateHistory = `-- name: InsertUpdateHistory :exec
INSERT INTO update_history (
    id, host_id, packages_count, security_count, total_packages,
    payload_size_kb, execution_time, timestamp, status, error_message,
    report_type, sections_sent, sections_unchanged, agent_execution_ms
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, NOW(), $8, $9,
    $10, $11, $12, $13
)
`

type InsertUpdateHistoryParams struct {
	ID                string   `json:"id"`
	HostID            string   `json:"host_id"`
	PackagesCount     int32    `json:"packages_count"`
	SecurityCount     int32    `json:"security_count"`
	TotalPackages     *int32   `json:"total_packages"`
	PayloadSizeKb     *float64 `json:"payload_size_kb"`
	ExecutionTime     *float64 `json:"execution_time"`
	Status            string   `json:"status"`
	ErrorMessage      *string  `json:"error_message"`
	ReportType        string   `json:"report_type"`
	SectionsSent      []string `json:"sections_sent"`
	SectionsUnchanged []string `json:"sections_unchanged"`
	AgentExecutionMs  *int32   `json:"agent_execution_ms"`
}

// Persists a single agent activity row for the per-host Agent Activity feed.
// report_type discriminates 'full' / 'partial' / 'ping' / 'docker' / 'compliance'.
// sections_sent / sections_unchanged drive the "Updated / Skipped" chip pair in
// the UI (legacy rows pre-000043 stay at the column defaults so the UI shows
// "—" for them). agent_execution_ms is the agent-side data-collection time
// shipped on the wire; nullable for older agents.
func (q *Queries) InsertUpdateHistory(ctx context.Context, arg InsertUpdateHistoryParams) error {
	_, err := q.db.Exec(ctx, insertUpdateHistory,
		arg.ID,
		arg.HostID,
		arg.PackagesCount,
		arg.SecurityCount,
		arg.TotalPackages,
		arg.PayloadSizeKb,
		arg.ExecutionTime,
		arg.Status,
		arg.ErrorMessage,
		arg.ReportType,
		arg.SectionsSent,
		arg.SectionsUnchanged,
		arg.AgentExecutionMs,
	)
	return err
}

const updateHostFromReport = `-- name: UpdateHostFromReport :exec

UPDATE hosts SET
    last_update = NOW(),
    updated_at = NOW(),
    status = CASE WHEN status = 'pending' THEN 'active' ELSE status END,
    machine_id = COALESCE($1::text, machine_id),
    os_type = COALESCE($2::text, os_type),
    os_version = COALESCE($3::text, os_version),
    hostname = COALESCE($4::text, hostname),
    ip = COALESCE($5::text, ip),
    architecture = COALESCE($6::text, architecture),
    agent_version = COALESCE($7::text, agent_version),
    cpu_model = COALESCE($8::text, cpu_model),
    cpu_cores = COALESCE($9::int, cpu_cores),
    ram_installed = COALESCE($10::double precision, ram_installed),
    swap_size = COALESCE($11::double precision, swap_size),
    disk_details = COALESCE($12::jsonb, disk_details),
    gateway_ip = COALESCE($13::text, gateway_ip),
    dns_servers = COALESCE($14::jsonb, dns_servers),
    network_interfaces = COALESCE($15::jsonb, network_interfaces),
    kernel_version = COALESCE($16::text, kernel_version),
    installed_kernel_version = COALESCE($17::text, installed_kernel_version),
    selinux_status = COALESCE($18::text, selinux_status),
    system_uptime = COALESCE($19::text, system_uptime),
    boot_time = COALESCE($20::timestamptz, boot_time),
    load_average = COALESCE($21::jsonb, load_average),
    needs_reboot = COALESCE($22::boolean, needs_reboot),
    -- reboot_reason is only rewritten when this report also carries
    -- needs_reboot. A hash-gated partial report never carries either (the ping
    -- metrics path owns both fields), and reboot_reason has no COALESCE guard
    -- of its own, so without this CASE a partial would NULL out a reason the
    -- ping had just written correctly.
    -- Second arm: a report asserting needs_reboot without a reason must not
    -- blank a stored one; clearing the flag still clears both.
    reboot_reason = CASE
        WHEN $22::boolean IS NULL THEN reboot_reason
        WHEN $22::boolean IS TRUE
             AND $23::text IS NULL THEN reboot_reason
        ELSE $23::text
    END,
    package_manager = COALESCE($24::text, package_manager),
    packages_hash = COALESCE($25::text, packages_hash),
    repos_hash = COALESCE($26::text, repos_hash),
    interfaces_hash = COALESCE($27::text, interfaces_hash),
    hostname_hash = COALESCE($28::text, hostname_hash),
    last_full_report_at = COALESCE($29::timestamp, last_full_report_at),
    awaiting_post_patch_report_run_id = NULL
WHERE id = $30
`

type UpdateHostFromReportParams struct {
	MachineID              *string            `json:"machine_id"`
	OsType                 *string            `json:"os_type"`
	OsVersion              *string            `json:"os_version"`
	Hostname               *string            `json:"hostname"`
	Ip                     *string            `json:"ip"`
	Architecture           *string            `json:"architecture"`
	AgentVersion           *string            `json:"agent_version"`
	CpuModel               *string            `json:"cpu_model"`
	CpuCores               *int32             `json:"cpu_cores"`
	RamInstalled           *float64           `json:"ram_installed"`
	SwapSize               *float64           `json:"swap_size"`
	DiskDetails            []byte             `json:"disk_details"`
	GatewayIp              *string            `json:"gateway_ip"`
	DnsServers             []byte             `json:"dns_servers"`
	NetworkInterfaces      []byte             `json:"network_interfaces"`
	KernelVersion          *string            `json:"kernel_version"`
	InstalledKernelVersion *string            `json:"installed_kernel_version"`
	SelinuxStatus          *string            `json:"selinux_status"`
	SystemUptime           *string            `json:"system_uptime"`
	BootTime               pgtype.Timestamptz `json:"boot_time"`
	LoadAverage            []byte             `json:"load_average"`
	NeedsReboot            *bool              `json:"needs_reboot"`
	RebootReason           *string            `json:"reboot_reason"`
	PackageManager         *string            `json:"package_manager"`
	PackagesHash           *string            `json:"packages_hash"`
	ReposHash              *string            `json:"repos_hash"`
	InterfacesHash         *string            `json:"interfaces_hash"`
	HostnameHash           *string            `json:"hostname_hash"`
	LastFullReportAt       pgtype.Timestamp   `json:"last_full_report_at"`
	ID                     string             `json:"id"`
}

// Host report/update flow (agent sends package and system info)
func (q *Queries) UpdateHostFromReport(ctx context.Context, arg UpdateHostFromReportParams) error {
	_, err := q.db.Exec(ctx, updateHostFromReport,
		arg.MachineID,
		arg.OsType,
		arg.OsVersion,
		arg.Hostname,
		arg.Ip,
		arg.Architecture,
		arg.AgentVersion,
		arg.CpuModel,
		arg.CpuCores,
		arg.RamInstalled,
		arg.SwapSize,
		arg.DiskDetails,
		arg.GatewayIp,
		arg.DnsServers,
		arg.NetworkInterfaces,
		arg.KernelVersion,
		arg.InstalledKernelVersion,
		arg.SelinuxStatus,
		arg.SystemUptime,
		arg.BootTime,
		arg.LoadAverage,
		arg.NeedsReboot,
		arg.RebootReason,
		arg.PackageManager,
		arg.PackagesHash,
		arg.ReposHash,
		arg.InterfacesHash,
		arg.HostnameHash,
		arg.LastFullReportAt,
		arg.ID,
	)
	return err
}
