// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: packages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countHostsForPackage = `-- name: CountHostsForPackage :one
SELECT COUNT(*)::int FROM host_packages hp
JOIN hosts h ON h.id = hp.host_id
WHERE hp.package_id = $1
AND ($2::text IS NULL OR h.friendly_name ILIKE '%' || $2 || '%' OR h.hostname ILIKE '%' || $2 || '%' OR hp.current_version ILIKE '%' || $2 || '%' OR hp.available_version ILIKE '%' || $2 || '%')
AND ($3::bool IS NULL OR hp.needs_update = $3)
`

type CountHostsForPackageParams struct {
	PackageID   string  `json:"package_id"`
	Search      *string `json:"search"`
	NeedsUpdate *bool   `json:"needs_update"`
}

func (q *Queries) CountHostsForPackage(ctx context.Context, arg CountHostsForPackageParams) (int32, error) {
	row := q.db.QueryRow(ctx, countHostsForPackage, arg.PackageID, arg.Search, arg.NeedsUpdate)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deletePackagesByIDs = `-- name: DeletePackagesByIDs :exec
DELETE FROM packages WHERE id = ANY($1::text[])
`

func (q *Queries) DeletePackagesByIDs(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deletePackagesByIDs, dollar_1)
	return err
}

const getCategories = `-- name: GetCategories :many
SELECT DISTINCT category FROM packages WHERE category IS NOT NULL AND category != '' ORDER BY category
`

func (q *Queries) GetCategories(ctx context.Context) ([]*string, error) {
	rows, err := q.db.Query(ctx, getCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*string
	for rows.Next() {
		var category *string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHostPackageStatsByHostIDs = `-- name: GetHostPackageStatsByHostIDs :many
SELECT host_id,
    COUNT(*)::int AS total,
    SUM(CASE WHEN needs_update THEN 1 ELSE 0 END)::int AS outdated,
    SUM(CASE WHEN needs_update AND is_security_update THEN 1 ELSE 0 END)::int AS security
FROM host_packages
WHERE host_id = ANY($1::text[])
GROUP BY host_id
`

type GetHostPackageStatsByHostIDsRow struct {
	HostID   string `json:"host_id"`
	Total    int32  `json:"total"`
	Outdated int32  `json:"outdated"`
	Security int32  `json:"security"`
}

func (q *Queries) GetHostPackageStatsByHostIDs(ctx context.Context, dollar_1 []string) ([]GetHostPackageStatsByHostIDsRow, error) {
	rows, err := q.db.Query(ctx, getHostPackageStatsByHostIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHostPackageStatsByHostIDsRow
	for rows.Next() {
		var i GetHostPackageStatsByHostIDsRow
		if err := rows.Scan(
			&i.HostID,
			&i.Total,
			&i.Outdated,
			&i.Security,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHostPackagesWithHostsByPackageID = `-- name: GetHostPackagesWithHostsByPackageID :many


SELECT hp.id, hp.host_id, hp.package_id, hp.current_version, hp.available_version,
    hp.needs_update, hp.is_security_update, hp.last_checked,
    hp.source_repository_id,
    r.name as source_repo_name, r.url as source_repo_url,
    h.friendly_name as host_friendly_name, h.hostname as host_hostname, h.ip as host_ip,
    h.os_type as host_os_type, h.os_version as host_os_version,
    h.last_update as host_last_update, h.needs_reboot as host_needs_reboot
FROM host_packages hp
JOIN hosts h ON h.id = hp.host_id
LEFT JOIN repositories r ON r.id = hp.source_repository_id
WHERE hp.package_id = $1
ORDER BY hp.needs_update DESC
`

type GetHostPackagesWithHostsByPackageIDRow struct {
	ID                 string           `json:"id"`
	HostID             string           `json:"host_id"`
	PackageID          string           `json:"package_id"`
	CurrentVersion     string           `json:"current_version"`
	AvailableVersion   *string          `json:"available_version"`
	NeedsUpdate        bool             `json:"needs_update"`
	IsSecurityUpdate   bool             `json:"is_security_update"`
	LastChecked        pgtype.Timestamp `json:"last_checked"`
	SourceRepositoryID *string          `json:"source_repository_id"`
	SourceRepoName     *string          `json:"source_repo_name"`
	SourceRepoUrl      *string          `json:"source_repo_url"`
	HostFriendlyName   string           `json:"host_friendly_name"`
	HostHostname       *string          `json:"host_hostname"`
	HostIp             *string          `json:"host_ip"`
	HostOsType         string           `json:"host_os_type"`
	HostOsVersion      string           `json:"host_os_version"`
	HostLastUpdate     pgtype.Timestamp `json:"host_last_update"`
	HostNeedsReboot    *bool            `json:"host_needs_reboot"`
}

// ListPackages and CountPackages are intentionally NOT defined here.
// They live as raw SQL builders in internal/store/packages_list_sql.go.
//
// Why hand-rolled rather than sqlc:
//  1. ORDER BY needs a CASE-WHEN-per-sort-key dance to stay parameterised,
//     which forces a full sort over the entire filtered CTE before LIMIT
//     can fire — defeats any index-ordered scan + LIMIT pushdown.
//     Building "ORDER BY <whitelisted column> <dir>" in Go lets the
//     planner drive output from the existing btree on packages(name)
//     (and similar) for typical queries, killing the parallel-sort path
//     that blows Docker's default /dev/shm.
//  2. The host_packages EXISTS / NOT EXISTS branches are only relevant
//     when the corresponding filter param is set; emitting them
//     conditionally in Go produces a much tighter predicate that the
//     planner can prune cheaply.
//
// Per-package counters still come from mv_package_stats (refreshed every
// ~2 min by an asynq scheduler — see TypePackageStatsRefresh) so we avoid
// per-request aggregation over host_packages.
// (Removed) GetHostPackageStatsByPackageIDs / GetUpdatesCountByPackageIDs /
// GetSecurityCountByPackageIDs — superseded by mv_package_stats. The
// per-package counters returned to the Packages list page now come from
// ListPackages itself (which joins the matview), so the previous
// per-id aggregate round-trips are no longer needed.
func (q *Queries) GetHostPackagesWithHostsByPackageID(ctx context.Context, packageID string) ([]GetHostPackagesWithHostsByPackageIDRow, error) {
	rows, err := q.db.Query(ctx, getHostPackagesWithHostsByPackageID, packageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHostPackagesWithHostsByPackageIDRow
	for rows.Next() {
		var i GetHostPackagesWithHostsByPackageIDRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.PackageID,
			&i.CurrentVersion,
			&i.AvailableVersion,
			&i.NeedsUpdate,
			&i.IsSecurityUpdate,
			&i.LastChecked,
			&i.SourceRepositoryID,
			&i.SourceRepoName,
			&i.SourceRepoUrl,
			&i.HostFriendlyName,
			&i.HostHostname,
			&i.HostIp,
			&i.HostOsType,
			&i.HostOsVersion,
			&i.HostLastUpdate,
			&i.HostNeedsReboot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHostRefsForPackageIDs = `-- name: GetHostRefsForPackageIDs :many
WITH ranked_refs AS (
    SELECT hp.package_id, h.id as host_id, h.friendly_name, h.os_type,
        hp.current_version, hp.available_version, hp.needs_update, hp.is_security_update,
        row_number() OVER (
            PARTITION BY hp.package_id
            ORDER BY hp.needs_update DESC, h.friendly_name ASC, h.id ASC
        ) AS rn
    FROM host_packages hp
    JOIN hosts h ON h.id = hp.host_id
    WHERE hp.package_id = ANY($1::text[])
    AND ($2::text IS NULL OR hp.host_id = $2)
)
SELECT package_id, host_id, friendly_name, os_type, current_version, available_version, needs_update, is_security_update
FROM ranked_refs
WHERE rn <= 10
ORDER BY package_id, needs_update DESC, friendly_name ASC
`

type GetHostRefsForPackageIDsParams struct {
	Column1 []string `json:"column_1"`
	HostID  *string  `json:"host_id"`
}

type GetHostRefsForPackageIDsRow struct {
	PackageID        string  `json:"package_id"`
	HostID           string  `json:"host_id"`
	FriendlyName     string  `json:"friendly_name"`
	OsType           string  `json:"os_type"`
	CurrentVersion   string  `json:"current_version"`
	AvailableVersion *string `json:"available_version"`
	NeedsUpdate      bool    `json:"needs_update"`
	IsSecurityUpdate bool    `json:"is_security_update"`
}

func (q *Queries) GetHostRefsForPackageIDs(ctx context.Context, arg GetHostRefsForPackageIDsParams) ([]GetHostRefsForPackageIDsRow, error) {
	rows, err := q.db.Query(ctx, getHostRefsForPackageIDs, arg.Column1, arg.HostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHostRefsForPackageIDsRow
	for rows.Next() {
		var i GetHostRefsForPackageIDsRow
		if err := rows.Scan(
			&i.PackageID,
			&i.HostID,
			&i.FriendlyName,
			&i.OsType,
			&i.CurrentVersion,
			&i.AvailableVersion,
			&i.NeedsUpdate,
			&i.IsSecurityUpdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPackageByID = `-- name: GetPackageByID :one
SELECT id, name, description, category, latest_version, created_at, updated_at FROM packages WHERE id = $1
`

func (q *Queries) GetPackageByID(ctx context.Context, id string) (Package, error) {
	row := q.db.QueryRow(ctx, getPackageByID, id)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.LatestVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingUpdateCountsPerHost = `-- name: GetPendingUpdateCountsPerHost :many
SELECT
    hp.host_id,
    SUM(CASE WHEN hp.needs_update THEN 1 ELSE 0 END)::int AS pending_count,
    SUM(CASE WHEN hp.needs_update AND hp.is_security_update THEN 1 ELSE 0 END)::int AS security_count
FROM host_packages hp
JOIN hosts h ON h.id = hp.host_id AND h.status = 'active'
GROUP BY hp.host_id
`

type GetPendingUpdateCountsPerHostRow struct {
	HostID        string `json:"host_id"`
	PendingCount  int32  `json:"pending_count"`
	SecurityCount int32  `json:"security_count"`
}

func (q *Queries) GetPendingUpdateCountsPerHost(ctx context.Context) ([]GetPendingUpdateCountsPerHostRow, error) {
	rows, err := q.db.Query(ctx, getPendingUpdateCountsPerHost)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingUpdateCountsPerHostRow
	for rows.Next() {
		var i GetPendingUpdateCountsPerHostRow
		if err := rows.Scan(&i.HostID, &i.PendingCount, &i.SecurityCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSourceReposByPackageIDs = `-- name: GetSourceReposByPackageIDs :many
SELECT DISTINCT hp.package_id, r.id as repo_id, r.name as repo_name, r.url as repo_url, r.repo_type
FROM host_packages hp
JOIN repositories r ON r.id = hp.source_repository_id
WHERE hp.package_id = ANY($1::text[])
AND ($2::text IS NULL OR hp.host_id = $2)
ORDER BY hp.package_id, r.name
`

type GetSourceReposByPackageIDsParams struct {
	Column1 []string `json:"column_1"`
	HostID  *string  `json:"host_id"`
}

type GetSourceReposByPackageIDsRow struct {
	PackageID string `json:"package_id"`
	RepoID    string `json:"repo_id"`
	RepoName  string `json:"repo_name"`
	RepoUrl   string `json:"repo_url"`
	RepoType  string `json:"repo_type"`
}

func (q *Queries) GetSourceReposByPackageIDs(ctx context.Context, arg GetSourceReposByPackageIDsParams) ([]GetSourceReposByPackageIDsRow, error) {
	rows, err := q.db.Query(ctx, getSourceReposByPackageIDs, arg.Column1, arg.HostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSourceReposByPackageIDsRow
	for rows.Next() {
		var i GetSourceReposByPackageIDsRow
		if err := rows.Scan(
			&i.PackageID,
			&i.RepoID,
			&i.RepoName,
			&i.RepoUrl,
			&i.RepoType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostsForPackage = `-- name: ListHostsForPackage :many
SELECT h.id, h.friendly_name, h.hostname, h.os_type, h.os_version, h.last_update, h.needs_reboot, h.reboot_reason,
    hp.current_version, hp.available_version, hp.needs_update, hp.is_security_update, hp.last_checked,
    hp.source_repository_id, r.name as source_repo_name
FROM host_packages hp
JOIN hosts h ON h.id = hp.host_id
LEFT JOIN repositories r ON r.id = hp.source_repository_id
WHERE hp.package_id = $1
AND ($2::text IS NULL OR h.friendly_name ILIKE '%' || $2 || '%' OR h.hostname ILIKE '%' || $2 || '%' OR hp.current_version ILIKE '%' || $2 || '%' OR hp.available_version ILIKE '%' || $2 || '%')
AND ($3::bool IS NULL OR hp.needs_update = $3)
ORDER BY hp.needs_update DESC, h.friendly_name ASC
LIMIT $5 OFFSET $4
`

type ListHostsForPackageParams struct {
	PackageID   string  `json:"package_id"`
	Search      *string `json:"search"`
	NeedsUpdate *bool   `json:"needs_update"`
	Offset      int32   `json:"offset"`
	Limit       int32   `json:"limit"`
}

type ListHostsForPackageRow struct {
	ID                 string           `json:"id"`
	FriendlyName       string           `json:"friendly_name"`
	Hostname           *string          `json:"hostname"`
	OsType             string           `json:"os_type"`
	OsVersion          string           `json:"os_version"`
	LastUpdate         pgtype.Timestamp `json:"last_update"`
	NeedsReboot        *bool            `json:"needs_reboot"`
	RebootReason       *string          `json:"reboot_reason"`
	CurrentVersion     string           `json:"current_version"`
	AvailableVersion   *string          `json:"available_version"`
	NeedsUpdate        bool             `json:"needs_update"`
	IsSecurityUpdate   bool             `json:"is_security_update"`
	LastChecked        pgtype.Timestamp `json:"last_checked"`
	SourceRepositoryID *string          `json:"source_repository_id"`
	SourceRepoName     *string          `json:"source_repo_name"`
}

func (q *Queries) ListHostsForPackage(ctx context.Context, arg ListHostsForPackageParams) ([]ListHostsForPackageRow, error) {
	rows, err := q.db.Query(ctx, listHostsForPackage,
		arg.PackageID,
		arg.Search,
		arg.NeedsUpdate,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHostsForPackageRow
	for rows.Next() {
		var i ListHostsForPackageRow
		if err := rows.Scan(
			&i.ID,
			&i.FriendlyName,
			&i.Hostname,
			&i.OsType,
			&i.OsVersion,
			&i.LastUpdate,
			&i.NeedsReboot,
			&i.RebootReason,
			&i.CurrentVersion,
			&i.AvailableVersion,
			&i.NeedsUpdate,
			&i.IsSecurityUpdate,
			&i.LastChecked,
			&i.SourceRepositoryID,
			&i.SourceRepoName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNeedingUpdates = `-- name: ListNeedingUpdates :many
SELECT p.id as pkg_id, p.name as pkg_name, p.description, p.category, p.latest_version,
    hp.current_version, hp.available_version, hp.is_security_update,
    h.id as host_id, h.friendly_name, h.os_type
FROM packages p
JOIN host_packages hp ON hp.package_id = p.id AND hp.needs_update = true
JOIN hosts h ON h.id = hp.host_id
ORDER BY p.name
`

type ListNeedingUpdatesRow struct {
	PkgID            string  `json:"pkg_id"`
	PkgName          string  `json:"pkg_name"`
	Description      *string `json:"description"`
	Category         *string `json:"category"`
	LatestVersion    *string `json:"latest_version"`
	CurrentVersion   string  `json:"current_version"`
	AvailableVersion *string `json:"available_version"`
	IsSecurityUpdate bool    `json:"is_security_update"`
	HostID           string  `json:"host_id"`
	FriendlyName     string  `json:"friendly_name"`
	OsType           string  `json:"os_type"`
}

func (q *Queries) ListNeedingUpdates(ctx context.Context) ([]ListNeedingUpdatesRow, error) {
	rows, err := q.db.Query(ctx, listNeedingUpdates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNeedingUpdatesRow
	for rows.Next() {
		var i ListNeedingUpdatesRow
		if err := rows.Scan(
			&i.PkgID,
			&i.PkgName,
			&i.Description,
			&i.Category,
			&i.LatestVersion,
			&i.CurrentVersion,
			&i.AvailableVersion,
			&i.IsSecurityUpdate,
			&i.HostID,
			&i.FriendlyName,
			&i.OsType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrphanedPackages = `-- name: ListOrphanedPackages :many
SELECT id, name, description, category, latest_version FROM packages p
WHERE NOT EXISTS (SELECT 1 FROM host_packages hp WHERE hp.package_id = p.id)
`

type ListOrphanedPackagesRow struct {
	ID            string  `json:"id"`
	Name          string  `json:"name"`
	Description   *string `json:"description"`
	Category      *string `json:"category"`
	LatestVersion *string `json:"latest_version"`
}

func (q *Queries) ListOrphanedPackages(ctx context.Context) ([]ListOrphanedPackagesRow, error) {
	rows, err := q.db.Query(ctx, listOrphanedPackages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrphanedPackagesRow
	for rows.Next() {
		var i ListOrphanedPackagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.LatestVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
