// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: patching.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearScheduledAt = `-- name: ClearScheduledAt :exec
UPDATE patch_runs SET scheduled_at = NULL, updated_at = NOW() WHERE id = $1
`

func (q *Queries) ClearScheduledAt(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, clearScheduledAt, id)
	return err
}

const countPatchRuns = `-- name: CountPatchRuns :one
SELECT COUNT(*) FROM patch_runs
WHERE ($1::text = '' OR host_id = $1)
  AND (
    $2::text = ''
    OR ($2::text = 'active' AND status IN ('queued', 'running'))
    OR ($2::text <> 'active' AND status = $2)
  )
  AND ($3::text = '' OR patch_type = $3)
`

type CountPatchRunsParams struct {
	HostID    string `json:"host_id"`
	Status    string `json:"status"`
	PatchType string `json:"patch_type"`
}

func (q *Queries) CountPatchRuns(ctx context.Context, arg CountPatchRunsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPatchRuns, arg.HostID, arg.Status, arg.PatchType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPatchRunsTotal = `-- name: CountPatchRunsTotal :one
SELECT COUNT(*) FROM patch_runs WHERE (dry_run = false OR dry_run IS NULL)
`

func (q *Queries) CountPatchRunsTotal(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPatchRunsTotal)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPatchPolicy = `-- name: CreatePatchPolicy :exec
INSERT INTO patch_policies (id, name, description, patch_delay_type, delay_minutes, fixed_time_utc, timezone, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW(), NOW())
`

type CreatePatchPolicyParams struct {
	ID             string  `json:"id"`
	Name           string  `json:"name"`
	Description    *string `json:"description"`
	PatchDelayType string  `json:"patch_delay_type"`
	DelayMinutes   *int32  `json:"delay_minutes"`
	FixedTimeUtc   *string `json:"fixed_time_utc"`
	Timezone       *string `json:"timezone"`
}

func (q *Queries) CreatePatchPolicy(ctx context.Context, arg CreatePatchPolicyParams) error {
	_, err := q.db.Exec(ctx, createPatchPolicy,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PatchDelayType,
		arg.DelayMinutes,
		arg.FixedTimeUtc,
		arg.Timezone,
	)
	return err
}

const createPatchPolicyAssignment = `-- name: CreatePatchPolicyAssignment :exec
INSERT INTO patch_policy_assignments (id, patch_policy_id, target_type, target_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
`

type CreatePatchPolicyAssignmentParams struct {
	ID            string `json:"id"`
	PatchPolicyID string `json:"patch_policy_id"`
	TargetType    string `json:"target_type"`
	TargetID      string `json:"target_id"`
}

func (q *Queries) CreatePatchPolicyAssignment(ctx context.Context, arg CreatePatchPolicyAssignmentParams) error {
	_, err := q.db.Exec(ctx, createPatchPolicyAssignment,
		arg.ID,
		arg.PatchPolicyID,
		arg.TargetType,
		arg.TargetID,
	)
	return err
}

const createPatchPolicyExclusion = `-- name: CreatePatchPolicyExclusion :exec
INSERT INTO patch_policy_exclusions (id, patch_policy_id, host_id, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
`

type CreatePatchPolicyExclusionParams struct {
	ID            string `json:"id"`
	PatchPolicyID string `json:"patch_policy_id"`
	HostID        string `json:"host_id"`
}

func (q *Queries) CreatePatchPolicyExclusion(ctx context.Context, arg CreatePatchPolicyExclusionParams) error {
	_, err := q.db.Exec(ctx, createPatchPolicyExclusion, arg.ID, arg.PatchPolicyID, arg.HostID)
	return err
}

const createPatchRun = `-- name: CreatePatchRun :exec
INSERT INTO patch_runs (id, host_id, job_id, patch_type, package_name, package_names, status, shell_output, triggered_by_user_id, dry_run, scheduled_at, policy_id, policy_name, policy_snapshot, validation_run_id, approved_by_user_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, NOW(), NOW())
`

type CreatePatchRunParams struct {
	ID                string           `json:"id"`
	HostID            string           `json:"host_id"`
	JobID             string           `json:"job_id"`
	PatchType         string           `json:"patch_type"`
	PackageName       *string          `json:"package_name"`
	PackageNames      []byte           `json:"package_names"`
	Status            string           `json:"status"`
	ShellOutput       string           `json:"shell_output"`
	TriggeredByUserID *string          `json:"triggered_by_user_id"`
	DryRun            bool             `json:"dry_run"`
	ScheduledAt       pgtype.Timestamp `json:"scheduled_at"`
	PolicyID          *string          `json:"policy_id"`
	PolicyName        *string          `json:"policy_name"`
	PolicySnapshot    []byte           `json:"policy_snapshot"`
	ValidationRunID   *string          `json:"validation_run_id"`
	ApprovedByUserID  *string          `json:"approved_by_user_id"`
}

// patch_runs
func (q *Queries) CreatePatchRun(ctx context.Context, arg CreatePatchRunParams) error {
	_, err := q.db.Exec(ctx, createPatchRun,
		arg.ID,
		arg.HostID,
		arg.JobID,
		arg.PatchType,
		arg.PackageName,
		arg.PackageNames,
		arg.Status,
		arg.ShellOutput,
		arg.TriggeredByUserID,
		arg.DryRun,
		arg.ScheduledAt,
		arg.PolicyID,
		arg.PolicyName,
		arg.PolicySnapshot,
		arg.ValidationRunID,
		arg.ApprovedByUserID,
	)
	return err
}

const deletePatchPolicy = `-- name: DeletePatchPolicy :exec
DELETE FROM patch_policies WHERE id = $1
`

func (q *Queries) DeletePatchPolicy(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePatchPolicy, id)
	return err
}

const deletePatchPolicyAssignment = `-- name: DeletePatchPolicyAssignment :exec
DELETE FROM patch_policy_assignments WHERE id = $1
`

func (q *Queries) DeletePatchPolicyAssignment(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePatchPolicyAssignment, id)
	return err
}

const deletePatchPolicyExclusion = `-- name: DeletePatchPolicyExclusion :exec
DELETE FROM patch_policy_exclusions WHERE patch_policy_id = $1 AND host_id = $2
`

type DeletePatchPolicyExclusionParams struct {
	PatchPolicyID string `json:"patch_policy_id"`
	HostID        string `json:"host_id"`
}

func (q *Queries) DeletePatchPolicyExclusion(ctx context.Context, arg DeletePatchPolicyExclusionParams) error {
	_, err := q.db.Exec(ctx, deletePatchPolicyExclusion, arg.PatchPolicyID, arg.HostID)
	return err
}

const deletePatchRun = `-- name: DeletePatchRun :exec
DELETE FROM patch_runs WHERE id = $1
`

func (q *Queries) DeletePatchRun(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePatchRun, id)
	return err
}

const existsPatchPolicyExclusion = `-- name: ExistsPatchPolicyExclusion :one
SELECT EXISTS(SELECT 1 FROM patch_policy_exclusions WHERE patch_policy_id = $1 AND host_id = $2)
`

type ExistsPatchPolicyExclusionParams struct {
	PatchPolicyID string `json:"patch_policy_id"`
	HostID        string `json:"host_id"`
}

func (q *Queries) ExistsPatchPolicyExclusion(ctx context.Context, arg ExistsPatchPolicyExclusionParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsPatchPolicyExclusion, arg.PatchPolicyID, arg.HostID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getDirectPatchPolicyAssignment = `-- name: GetDirectPatchPolicyAssignment :one
SELECT pp.id, pp.name, pp.description, pp.patch_delay_type, pp.delay_minutes, pp.fixed_time_utc, pp.timezone, pp.created_at, pp.updated_at FROM patch_policy_assignments ppa
JOIN patch_policies pp ON ppa.patch_policy_id = pp.id
WHERE ppa.target_type = 'host' AND ppa.target_id = $1
ORDER BY ppa.created_at ASC
LIMIT 1
`

// patch_policy_assignments
func (q *Queries) GetDirectPatchPolicyAssignment(ctx context.Context, targetID string) (PatchPolicy, error) {
	row := q.db.QueryRow(ctx, getDirectPatchPolicyAssignment, targetID)
	var i PatchPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PatchDelayType,
		&i.DelayMinutes,
		&i.FixedTimeUtc,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHostGroupMemberships = `-- name: GetHostGroupMemberships :many
SELECT host_group_id FROM host_group_memberships WHERE host_id = $1
`

func (q *Queries) GetHostGroupMemberships(ctx context.Context, hostID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getHostGroupMemberships, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var host_group_id string
		if err := rows.Scan(&host_group_id); err != nil {
			return nil, err
		}
		items = append(items, host_group_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPatchPolicyAssignmentByID = `-- name: GetPatchPolicyAssignmentByID :one
SELECT id, patch_policy_id, target_type, target_id, created_at, updated_at FROM patch_policy_assignments WHERE id = $1
`

func (q *Queries) GetPatchPolicyAssignmentByID(ctx context.Context, id string) (PatchPolicyAssignment, error) {
	row := q.db.QueryRow(ctx, getPatchPolicyAssignmentByID, id)
	var i PatchPolicyAssignment
	err := row.Scan(
		&i.ID,
		&i.PatchPolicyID,
		&i.TargetType,
		&i.TargetID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPatchPolicyByGroupAssignment = `-- name: GetPatchPolicyByGroupAssignment :one
SELECT pp.id, pp.name, pp.description, pp.patch_delay_type, pp.delay_minutes, pp.fixed_time_utc, pp.timezone, pp.created_at, pp.updated_at FROM patch_policy_assignments ppa
JOIN patch_policies pp ON ppa.patch_policy_id = pp.id
WHERE ppa.target_type = 'host_group' AND ppa.target_id = $1
ORDER BY ppa.created_at ASC
LIMIT 1
`

func (q *Queries) GetPatchPolicyByGroupAssignment(ctx context.Context, targetID string) (PatchPolicy, error) {
	row := q.db.QueryRow(ctx, getPatchPolicyByGroupAssignment, targetID)
	var i PatchPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PatchDelayType,
		&i.DelayMinutes,
		&i.FixedTimeUtc,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPatchPolicyByID = `-- name: GetPatchPolicyByID :one
SELECT id, name, description, patch_delay_type, delay_minutes, fixed_time_utc, timezone, created_at, updated_at FROM patch_policies WHERE id = $1
`

func (q *Queries) GetPatchPolicyByID(ctx context.Context, id string) (PatchPolicy, error) {
	row := q.db.QueryRow(ctx, getPatchPolicyByID, id)
	var i PatchPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PatchDelayType,
		&i.DelayMinutes,
		&i.FixedTimeUtc,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPatchRunByID = `-- name: GetPatchRunByID :one
SELECT pr.id, pr.host_id, pr.job_id, pr.patch_type, pr.package_name, pr.package_names, pr.status, pr.shell_output, pr.error_message, pr.started_at, pr.completed_at, pr.scheduled_at, pr.triggered_by_user_id, pr.approved_by_user_id, pr.dry_run, pr.packages_affected, pr.policy_id, pr.policy_name, pr.policy_snapshot, pr.validation_run_id, pr.created_at, pr.updated_at, h.friendly_name AS host_friendly_name, h.hostname AS host_hostname, u.username AS triggered_by_username, au.username AS approved_by_username
FROM patch_runs pr
LEFT JOIN hosts h ON pr.host_id = h.id
LEFT JOIN users u ON pr.triggered_by_user_id = u.id
LEFT JOIN users au ON pr.approved_by_user_id = au.id
WHERE pr.id = $1
`

type GetPatchRunByIDRow struct {
	ID                  string           `json:"id"`
	HostID              string           `json:"host_id"`
	JobID               string           `json:"job_id"`
	PatchType           string           `json:"patch_type"`
	PackageName         *string          `json:"package_name"`
	PackageNames        []byte           `json:"package_names"`
	Status              string           `json:"status"`
	ShellOutput         string           `json:"shell_output"`
	ErrorMessage        *string          `json:"error_message"`
	StartedAt           pgtype.Timestamp `json:"started_at"`
	CompletedAt         pgtype.Timestamp `json:"completed_at"`
	ScheduledAt         pgtype.Timestamp `json:"scheduled_at"`
	TriggeredByUserID   *string          `json:"triggered_by_user_id"`
	ApprovedByUserID    *string          `json:"approved_by_user_id"`
	DryRun              bool             `json:"dry_run"`
	PackagesAffected    []byte           `json:"packages_affected"`
	PolicyID            *string          `json:"policy_id"`
	PolicyName          *string          `json:"policy_name"`
	PolicySnapshot      []byte           `json:"policy_snapshot"`
	ValidationRunID     *string          `json:"validation_run_id"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	HostFriendlyName    *string          `json:"host_friendly_name"`
	HostHostname        *string          `json:"host_hostname"`
	TriggeredByUsername *string          `json:"triggered_by_username"`
	ApprovedByUsername  *string          `json:"approved_by_username"`
}

func (q *Queries) GetPatchRunByID(ctx context.Context, id string) (GetPatchRunByIDRow, error) {
	row := q.db.QueryRow(ctx, getPatchRunByID, id)
	var i GetPatchRunByIDRow
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.JobID,
		&i.PatchType,
		&i.PackageName,
		&i.PackageNames,
		&i.Status,
		&i.ShellOutput,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ScheduledAt,
		&i.TriggeredByUserID,
		&i.ApprovedByUserID,
		&i.DryRun,
		&i.PackagesAffected,
		&i.PolicyID,
		&i.PolicyName,
		&i.PolicySnapshot,
		&i.ValidationRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HostFriendlyName,
		&i.HostHostname,
		&i.TriggeredByUsername,
		&i.ApprovedByUsername,
	)
	return i, err
}

const getPatchRunByIDSimple = `-- name: GetPatchRunByIDSimple :one
SELECT id, host_id, job_id, patch_type, package_name, package_names, status, shell_output, error_message, started_at, completed_at, scheduled_at, triggered_by_user_id, approved_by_user_id, dry_run, packages_affected, policy_id, policy_name, policy_snapshot, validation_run_id, created_at, updated_at FROM patch_runs WHERE id = $1
`

func (q *Queries) GetPatchRunByIDSimple(ctx context.Context, id string) (PatchRun, error) {
	row := q.db.QueryRow(ctx, getPatchRunByIDSimple, id)
	var i PatchRun
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.JobID,
		&i.PatchType,
		&i.PackageName,
		&i.PackageNames,
		&i.Status,
		&i.ShellOutput,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ScheduledAt,
		&i.TriggeredByUserID,
		&i.ApprovedByUserID,
		&i.DryRun,
		&i.PackagesAffected,
		&i.PolicyID,
		&i.PolicyName,
		&i.PolicySnapshot,
		&i.ValidationRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivePatchRuns = `-- name: ListActivePatchRuns :many
SELECT pr.id, pr.host_id, pr.job_id, pr.patch_type, pr.package_name, pr.package_names, pr.status, pr.shell_output, pr.error_message, pr.started_at, pr.completed_at, pr.scheduled_at, pr.triggered_by_user_id, pr.approved_by_user_id, pr.dry_run, pr.packages_affected, pr.policy_id, pr.policy_name, pr.policy_snapshot, pr.validation_run_id, pr.created_at, pr.updated_at, h.friendly_name AS host_friendly_name, h.hostname AS host_hostname, u.username AS triggered_by_username
FROM patch_runs pr
LEFT JOIN hosts h ON pr.host_id = h.id
LEFT JOIN users u ON pr.triggered_by_user_id = u.id
WHERE pr.status IN ('queued', 'running', 'pending_validation', 'pending_approval', 'validated') AND (pr.dry_run = false OR pr.dry_run IS NULL OR pr.status IN ('pending_validation', 'pending_approval', 'validated'))
ORDER BY pr.created_at ASC
`

type ListActivePatchRunsRow struct {
	ID                  string           `json:"id"`
	HostID              string           `json:"host_id"`
	JobID               string           `json:"job_id"`
	PatchType           string           `json:"patch_type"`
	PackageName         *string          `json:"package_name"`
	PackageNames        []byte           `json:"package_names"`
	Status              string           `json:"status"`
	ShellOutput         string           `json:"shell_output"`
	ErrorMessage        *string          `json:"error_message"`
	StartedAt           pgtype.Timestamp `json:"started_at"`
	CompletedAt         pgtype.Timestamp `json:"completed_at"`
	ScheduledAt         pgtype.Timestamp `json:"scheduled_at"`
	TriggeredByUserID   *string          `json:"triggered_by_user_id"`
	ApprovedByUserID    *string          `json:"approved_by_user_id"`
	DryRun              bool             `json:"dry_run"`
	PackagesAffected    []byte           `json:"packages_affected"`
	PolicyID            *string          `json:"policy_id"`
	PolicyName          *string          `json:"policy_name"`
	PolicySnapshot      []byte           `json:"policy_snapshot"`
	ValidationRunID     *string          `json:"validation_run_id"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	HostFriendlyName    *string          `json:"host_friendly_name"`
	HostHostname        *string          `json:"host_hostname"`
	TriggeredByUsername *string          `json:"triggered_by_username"`
}

func (q *Queries) ListActivePatchRuns(ctx context.Context) ([]ListActivePatchRunsRow, error) {
	rows, err := q.db.Query(ctx, listActivePatchRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivePatchRunsRow
	for rows.Next() {
		var i ListActivePatchRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.JobID,
			&i.PatchType,
			&i.PackageName,
			&i.PackageNames,
			&i.Status,
			&i.ShellOutput,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ScheduledAt,
			&i.TriggeredByUserID,
			&i.ApprovedByUserID,
			&i.DryRun,
			&i.PackagesAffected,
			&i.PolicyID,
			&i.PolicyName,
			&i.PolicySnapshot,
			&i.ValidationRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HostFriendlyName,
			&i.HostHostname,
			&i.TriggeredByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatchPolicies = `-- name: ListPatchPolicies :many
SELECT id, name, description, patch_delay_type, delay_minutes, fixed_time_utc, timezone, created_at, updated_at FROM patch_policies ORDER BY name ASC
`

// patch_policies
func (q *Queries) ListPatchPolicies(ctx context.Context) ([]PatchPolicy, error) {
	rows, err := q.db.Query(ctx, listPatchPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatchPolicy
	for rows.Next() {
		var i PatchPolicy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PatchDelayType,
			&i.DelayMinutes,
			&i.FixedTimeUtc,
			&i.Timezone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatchPolicyAssignments = `-- name: ListPatchPolicyAssignments :many
SELECT id, patch_policy_id, target_type, target_id, created_at, updated_at FROM patch_policy_assignments WHERE patch_policy_id = $1 AND target_type = $2 AND target_id = $3
`

type ListPatchPolicyAssignmentsParams struct {
	PatchPolicyID string `json:"patch_policy_id"`
	TargetType    string `json:"target_type"`
	TargetID      string `json:"target_id"`
}

func (q *Queries) ListPatchPolicyAssignments(ctx context.Context, arg ListPatchPolicyAssignmentsParams) ([]PatchPolicyAssignment, error) {
	rows, err := q.db.Query(ctx, listPatchPolicyAssignments, arg.PatchPolicyID, arg.TargetType, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatchPolicyAssignment
	for rows.Next() {
		var i PatchPolicyAssignment
		if err := rows.Scan(
			&i.ID,
			&i.PatchPolicyID,
			&i.TargetType,
			&i.TargetID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatchPolicyAssignmentsByPolicy = `-- name: ListPatchPolicyAssignmentsByPolicy :many
SELECT id, patch_policy_id, target_type, target_id, created_at, updated_at FROM patch_policy_assignments WHERE patch_policy_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListPatchPolicyAssignmentsByPolicy(ctx context.Context, patchPolicyID string) ([]PatchPolicyAssignment, error) {
	rows, err := q.db.Query(ctx, listPatchPolicyAssignmentsByPolicy, patchPolicyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatchPolicyAssignment
	for rows.Next() {
		var i PatchPolicyAssignment
		if err := rows.Scan(
			&i.ID,
			&i.PatchPolicyID,
			&i.TargetType,
			&i.TargetID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatchPolicyExclusions = `-- name: ListPatchPolicyExclusions :many
SELECT ppe.id, ppe.patch_policy_id, ppe.host_id, ppe.created_at, ppe.updated_at, h.friendly_name AS host_friendly_name, h.hostname AS host_hostname
FROM patch_policy_exclusions ppe
LEFT JOIN hosts h ON ppe.host_id = h.id
WHERE ppe.patch_policy_id = $1
`

type ListPatchPolicyExclusionsRow struct {
	ID               string           `json:"id"`
	PatchPolicyID    string           `json:"patch_policy_id"`
	HostID           string           `json:"host_id"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	HostFriendlyName *string          `json:"host_friendly_name"`
	HostHostname     *string          `json:"host_hostname"`
}

// patch_policy_exclusions
func (q *Queries) ListPatchPolicyExclusions(ctx context.Context, patchPolicyID string) ([]ListPatchPolicyExclusionsRow, error) {
	rows, err := q.db.Query(ctx, listPatchPolicyExclusions, patchPolicyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPatchPolicyExclusionsRow
	for rows.Next() {
		var i ListPatchPolicyExclusionsRow
		if err := rows.Scan(
			&i.ID,
			&i.PatchPolicyID,
			&i.HostID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HostFriendlyName,
			&i.HostHostname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatchRuns = `-- name: ListPatchRuns :many
SELECT pr.id, pr.host_id, pr.job_id, pr.patch_type, pr.package_name, pr.package_names, pr.status, pr.shell_output, pr.error_message, pr.started_at, pr.completed_at, pr.scheduled_at, pr.triggered_by_user_id, pr.approved_by_user_id, pr.dry_run, pr.packages_affected, pr.policy_id, pr.policy_name, pr.policy_snapshot, pr.validation_run_id, pr.created_at, pr.updated_at, h.friendly_name AS host_friendly_name, h.hostname AS host_hostname, u.username AS triggered_by_username
FROM patch_runs pr
LEFT JOIN hosts h ON pr.host_id = h.id
LEFT JOIN users u ON pr.triggered_by_user_id = u.id
WHERE ($1::text = '' OR pr.host_id = $1)
  AND (
    $2::text = ''
    OR ($2::text = 'active' AND pr.status IN ('queued', 'running'))
    OR ($2::text <> 'active' AND pr.status = $2)
  )
  AND ($3::text = '' OR pr.patch_type = $3)
ORDER BY pr.created_at DESC
LIMIT $5 OFFSET $4
`

type ListPatchRunsParams struct {
	HostID    string `json:"host_id"`
	Status    string `json:"status"`
	PatchType string `json:"patch_type"`
	OffsetArg int32  `json:"offset_arg"`
	LimitArg  int32  `json:"limit_arg"`
}

type ListPatchRunsRow struct {
	ID                  string           `json:"id"`
	HostID              string           `json:"host_id"`
	JobID               string           `json:"job_id"`
	PatchType           string           `json:"patch_type"`
	PackageName         *string          `json:"package_name"`
	PackageNames        []byte           `json:"package_names"`
	Status              string           `json:"status"`
	ShellOutput         string           `json:"shell_output"`
	ErrorMessage        *string          `json:"error_message"`
	StartedAt           pgtype.Timestamp `json:"started_at"`
	CompletedAt         pgtype.Timestamp `json:"completed_at"`
	ScheduledAt         pgtype.Timestamp `json:"scheduled_at"`
	TriggeredByUserID   *string          `json:"triggered_by_user_id"`
	ApprovedByUserID    *string          `json:"approved_by_user_id"`
	DryRun              bool             `json:"dry_run"`
	PackagesAffected    []byte           `json:"packages_affected"`
	PolicyID            *string          `json:"policy_id"`
	PolicyName          *string          `json:"policy_name"`
	PolicySnapshot      []byte           `json:"policy_snapshot"`
	ValidationRunID     *string          `json:"validation_run_id"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	HostFriendlyName    *string          `json:"host_friendly_name"`
	HostHostname        *string          `json:"host_hostname"`
	TriggeredByUsername *string          `json:"triggered_by_username"`
}

// The 'status' filter accepts an exact status value. The pseudo-value
// 'active' matches any in-flight run (queued or running) so UI widgets
// that aggregate those two states can link to a single filter.
func (q *Queries) ListPatchRuns(ctx context.Context, arg ListPatchRunsParams) ([]ListPatchRunsRow, error) {
	rows, err := q.db.Query(ctx, listPatchRuns,
		arg.HostID,
		arg.Status,
		arg.PatchType,
		arg.OffsetArg,
		arg.LimitArg,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPatchRunsRow
	for rows.Next() {
		var i ListPatchRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.JobID,
			&i.PatchType,
			&i.PackageName,
			&i.PackageNames,
			&i.Status,
			&i.ShellOutput,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ScheduledAt,
			&i.TriggeredByUserID,
			&i.ApprovedByUserID,
			&i.DryRun,
			&i.PackagesAffected,
			&i.PolicyID,
			&i.PolicyName,
			&i.PolicySnapshot,
			&i.ValidationRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HostFriendlyName,
			&i.HostHostname,
			&i.TriggeredByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatchRunsByPackage = `-- name: ListPatchRunsByPackage :many
SELECT pr.id, pr.host_id, pr.completed_at, h.friendly_name AS host_friendly_name, h.hostname AS host_hostname
FROM patch_runs pr
LEFT JOIN hosts h ON pr.host_id = h.id
WHERE pr.status = 'completed'
  AND (pr.dry_run = false OR pr.dry_run IS NULL)
  AND (
    pr.package_name = $1
    OR (pr.package_names IS NOT NULL AND pr.package_names @> jsonb_build_array($1::text))
    OR (pr.packages_affected IS NOT NULL AND pr.packages_affected @> jsonb_build_array($1::text))
  )
ORDER BY pr.completed_at DESC NULLS LAST, pr.created_at DESC
LIMIT $3 OFFSET $2
`

type ListPatchRunsByPackageParams struct {
	PackageName *string `json:"package_name"`
	OffsetArg   int32   `json:"offset_arg"`
	LimitArg    int32   `json:"limit_arg"`
}

type ListPatchRunsByPackageRow struct {
	ID               string           `json:"id"`
	HostID           string           `json:"host_id"`
	CompletedAt      pgtype.Timestamp `json:"completed_at"`
	HostFriendlyName *string          `json:"host_friendly_name"`
	HostHostname     *string          `json:"host_hostname"`
}

func (q *Queries) ListPatchRunsByPackage(ctx context.Context, arg ListPatchRunsByPackageParams) ([]ListPatchRunsByPackageRow, error) {
	rows, err := q.db.Query(ctx, listPatchRunsByPackage, arg.PackageName, arg.OffsetArg, arg.LimitArg)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPatchRunsByPackageRow
	for rows.Next() {
		var i ListPatchRunsByPackageRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.CompletedAt,
			&i.HostFriendlyName,
			&i.HostHostname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatchRunsByStatus = `-- name: ListPatchRunsByStatus :many
SELECT status, COUNT(*)::int AS count FROM patch_runs WHERE (dry_run = false OR dry_run IS NULL) OR status IN ('pending_validation', 'pending_approval', 'validated') GROUP BY status
`

type ListPatchRunsByStatusRow struct {
	Status string `json:"status"`
	Count  int32  `json:"count"`
}

func (q *Queries) ListPatchRunsByStatus(ctx context.Context) ([]ListPatchRunsByStatusRow, error) {
	rows, err := q.db.Query(ctx, listPatchRunsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPatchRunsByStatusRow
	for rows.Next() {
		var i ListPatchRunsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatchRunsOrderByCompletedAt = `-- name: ListPatchRunsOrderByCompletedAt :many
SELECT pr.id, pr.host_id, pr.job_id, pr.patch_type, pr.package_name, pr.package_names, pr.status, pr.shell_output, pr.error_message, pr.started_at, pr.completed_at, pr.scheduled_at, pr.triggered_by_user_id, pr.approved_by_user_id, pr.dry_run, pr.packages_affected, pr.policy_id, pr.policy_name, pr.policy_snapshot, pr.validation_run_id, pr.created_at, pr.updated_at, h.friendly_name AS host_friendly_name, h.hostname AS host_hostname, u.username AS triggered_by_username
FROM patch_runs pr
LEFT JOIN hosts h ON pr.host_id = h.id
LEFT JOIN users u ON pr.triggered_by_user_id = u.id
WHERE ($1::text = '' OR pr.host_id = $1)
  AND (
    $2::text = ''
    OR ($2::text = 'active' AND pr.status IN ('queued', 'running'))
    OR ($2::text <> 'active' AND pr.status = $2)
  )
  AND ($3::text = '' OR pr.patch_type = $3)
ORDER BY COALESCE(pr.completed_at, pr.created_at) DESC NULLS LAST, pr.created_at DESC
LIMIT $5 OFFSET $4
`

type ListPatchRunsOrderByCompletedAtParams struct {
	HostID    string `json:"host_id"`
	Status    string `json:"status"`
	PatchType string `json:"patch_type"`
	OffsetArg int32  `json:"offset_arg"`
	LimitArg  int32  `json:"limit_arg"`
}

type ListPatchRunsOrderByCompletedAtRow struct {
	ID                  string           `json:"id"`
	HostID              string           `json:"host_id"`
	JobID               string           `json:"job_id"`
	PatchType           string           `json:"patch_type"`
	PackageName         *string          `json:"package_name"`
	PackageNames        []byte           `json:"package_names"`
	Status              string           `json:"status"`
	ShellOutput         string           `json:"shell_output"`
	ErrorMessage        *string          `json:"error_message"`
	StartedAt           pgtype.Timestamp `json:"started_at"`
	CompletedAt         pgtype.Timestamp `json:"completed_at"`
	ScheduledAt         pgtype.Timestamp `json:"scheduled_at"`
	TriggeredByUserID   *string          `json:"triggered_by_user_id"`
	ApprovedByUserID    *string          `json:"approved_by_user_id"`
	DryRun              bool             `json:"dry_run"`
	PackagesAffected    []byte           `json:"packages_affected"`
	PolicyID            *string          `json:"policy_id"`
	PolicyName          *string          `json:"policy_name"`
	PolicySnapshot      []byte           `json:"policy_snapshot"`
	ValidationRunID     *string          `json:"validation_run_id"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	HostFriendlyName    *string          `json:"host_friendly_name"`
	HostHostname        *string          `json:"host_hostname"`
	TriggeredByUsername *string          `json:"triggered_by_username"`
}

func (q *Queries) ListPatchRunsOrderByCompletedAt(ctx context.Context, arg ListPatchRunsOrderByCompletedAtParams) ([]ListPatchRunsOrderByCompletedAtRow, error) {
	rows, err := q.db.Query(ctx, listPatchRunsOrderByCompletedAt,
		arg.HostID,
		arg.Status,
		arg.PatchType,
		arg.OffsetArg,
		arg.LimitArg,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPatchRunsOrderByCompletedAtRow
	for rows.Next() {
		var i ListPatchRunsOrderByCompletedAtRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.JobID,
			&i.PatchType,
			&i.PackageName,
			&i.PackageNames,
			&i.Status,
			&i.ShellOutput,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ScheduledAt,
			&i.TriggeredByUserID,
			&i.ApprovedByUserID,
			&i.DryRun,
			&i.PackagesAffected,
			&i.PolicyID,
			&i.PolicyName,
			&i.PolicySnapshot,
			&i.ValidationRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HostFriendlyName,
			&i.HostHostname,
			&i.TriggeredByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatchRunsOrderByCompletedAtAsc = `-- name: ListPatchRunsOrderByCompletedAtAsc :many
SELECT pr.id, pr.host_id, pr.job_id, pr.patch_type, pr.package_name, pr.package_names, pr.status, pr.shell_output, pr.error_message, pr.started_at, pr.completed_at, pr.scheduled_at, pr.triggered_by_user_id, pr.approved_by_user_id, pr.dry_run, pr.packages_affected, pr.policy_id, pr.policy_name, pr.policy_snapshot, pr.validation_run_id, pr.created_at, pr.updated_at, h.friendly_name AS host_friendly_name, h.hostname AS host_hostname, u.username AS triggered_by_username
FROM patch_runs pr
LEFT JOIN hosts h ON pr.host_id = h.id
LEFT JOIN users u ON pr.triggered_by_user_id = u.id
WHERE ($1::text = '' OR pr.host_id = $1)
  AND (
    $2::text = ''
    OR ($2::text = 'active' AND pr.status IN ('queued', 'running'))
    OR ($2::text <> 'active' AND pr.status = $2)
  )
  AND ($3::text = '' OR pr.patch_type = $3)
ORDER BY COALESCE(pr.completed_at, pr.created_at) ASC NULLS LAST, pr.created_at DESC
LIMIT $5 OFFSET $4
`

type ListPatchRunsOrderByCompletedAtAscParams struct {
	HostID    string `json:"host_id"`
	Status    string `json:"status"`
	PatchType string `json:"patch_type"`
	OffsetArg int32  `json:"offset_arg"`
	LimitArg  int32  `json:"limit_arg"`
}

type ListPatchRunsOrderByCompletedAtAscRow struct {
	ID                  string           `json:"id"`
	HostID              string           `json:"host_id"`
	JobID               string           `json:"job_id"`
	PatchType           string           `json:"patch_type"`
	PackageName         *string          `json:"package_name"`
	PackageNames        []byte           `json:"package_names"`
	Status              string           `json:"status"`
	ShellOutput         string           `json:"shell_output"`
	ErrorMessage        *string          `json:"error_message"`
	StartedAt           pgtype.Timestamp `json:"started_at"`
	CompletedAt         pgtype.Timestamp `json:"completed_at"`
	ScheduledAt         pgtype.Timestamp `json:"scheduled_at"`
	TriggeredByUserID   *string          `json:"triggered_by_user_id"`
	ApprovedByUserID    *string          `json:"approved_by_user_id"`
	DryRun              bool             `json:"dry_run"`
	PackagesAffected    []byte           `json:"packages_affected"`
	PolicyID            *string          `json:"policy_id"`
	PolicyName          *string          `json:"policy_name"`
	PolicySnapshot      []byte           `json:"policy_snapshot"`
	ValidationRunID     *string          `json:"validation_run_id"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	HostFriendlyName    *string          `json:"host_friendly_name"`
	HostHostname        *string          `json:"host_hostname"`
	TriggeredByUsername *string          `json:"triggered_by_username"`
}

func (q *Queries) ListPatchRunsOrderByCompletedAtAsc(ctx context.Context, arg ListPatchRunsOrderByCompletedAtAscParams) ([]ListPatchRunsOrderByCompletedAtAscRow, error) {
	rows, err := q.db.Query(ctx, listPatchRunsOrderByCompletedAtAsc,
		arg.HostID,
		arg.Status,
		arg.PatchType,
		arg.OffsetArg,
		arg.LimitArg,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPatchRunsOrderByCompletedAtAscRow
	for rows.Next() {
		var i ListPatchRunsOrderByCompletedAtAscRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.JobID,
			&i.PatchType,
			&i.PackageName,
			&i.PackageNames,
			&i.Status,
			&i.ShellOutput,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ScheduledAt,
			&i.TriggeredByUserID,
			&i.ApprovedByUserID,
			&i.DryRun,
			&i.PackagesAffected,
			&i.PolicyID,
			&i.PolicyName,
			&i.PolicySnapshot,
			&i.ValidationRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HostFriendlyName,
			&i.HostHostname,
			&i.TriggeredByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatchRunsOrderByCreatedAtAsc = `-- name: ListPatchRunsOrderByCreatedAtAsc :many
SELECT pr.id, pr.host_id, pr.job_id, pr.patch_type, pr.package_name, pr.package_names, pr.status, pr.shell_output, pr.error_message, pr.started_at, pr.completed_at, pr.scheduled_at, pr.triggered_by_user_id, pr.approved_by_user_id, pr.dry_run, pr.packages_affected, pr.policy_id, pr.policy_name, pr.policy_snapshot, pr.validation_run_id, pr.created_at, pr.updated_at, h.friendly_name AS host_friendly_name, h.hostname AS host_hostname, u.username AS triggered_by_username
FROM patch_runs pr
LEFT JOIN hosts h ON pr.host_id = h.id
LEFT JOIN users u ON pr.triggered_by_user_id = u.id
WHERE ($1::text = '' OR pr.host_id = $1)
  AND (
    $2::text = ''
    OR ($2::text = 'active' AND pr.status IN ('queued', 'running'))
    OR ($2::text <> 'active' AND pr.status = $2)
  )
  AND ($3::text = '' OR pr.patch_type = $3)
ORDER BY pr.created_at ASC
LIMIT $5 OFFSET $4
`

type ListPatchRunsOrderByCreatedAtAscParams struct {
	HostID    string `json:"host_id"`
	Status    string `json:"status"`
	PatchType string `json:"patch_type"`
	OffsetArg int32  `json:"offset_arg"`
	LimitArg  int32  `json:"limit_arg"`
}

type ListPatchRunsOrderByCreatedAtAscRow struct {
	ID                  string           `json:"id"`
	HostID              string           `json:"host_id"`
	JobID               string           `json:"job_id"`
	PatchType           string           `json:"patch_type"`
	PackageName         *string          `json:"package_name"`
	PackageNames        []byte           `json:"package_names"`
	Status              string           `json:"status"`
	ShellOutput         string           `json:"shell_output"`
	ErrorMessage        *string          `json:"error_message"`
	StartedAt           pgtype.Timestamp `json:"started_at"`
	CompletedAt         pgtype.Timestamp `json:"completed_at"`
	ScheduledAt         pgtype.Timestamp `json:"scheduled_at"`
	TriggeredByUserID   *string          `json:"triggered_by_user_id"`
	ApprovedByUserID    *string          `json:"approved_by_user_id"`
	DryRun              bool             `json:"dry_run"`
	PackagesAffected    []byte           `json:"packages_affected"`
	PolicyID            *string          `json:"policy_id"`
	PolicyName          *string          `json:"policy_name"`
	PolicySnapshot      []byte           `json:"policy_snapshot"`
	ValidationRunID     *string          `json:"validation_run_id"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	HostFriendlyName    *string          `json:"host_friendly_name"`
	HostHostname        *string          `json:"host_hostname"`
	TriggeredByUsername *string          `json:"triggered_by_username"`
}

func (q *Queries) ListPatchRunsOrderByCreatedAtAsc(ctx context.Context, arg ListPatchRunsOrderByCreatedAtAscParams) ([]ListPatchRunsOrderByCreatedAtAscRow, error) {
	rows, err := q.db.Query(ctx, listPatchRunsOrderByCreatedAtAsc,
		arg.HostID,
		arg.Status,
		arg.PatchType,
		arg.OffsetArg,
		arg.LimitArg,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPatchRunsOrderByCreatedAtAscRow
	for rows.Next() {
		var i ListPatchRunsOrderByCreatedAtAscRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.JobID,
			&i.PatchType,
			&i.PackageName,
			&i.PackageNames,
			&i.Status,
			&i.ShellOutput,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ScheduledAt,
			&i.TriggeredByUserID,
			&i.ApprovedByUserID,
			&i.DryRun,
			&i.PackagesAffected,
			&i.PolicyID,
			&i.PolicyName,
			&i.PolicySnapshot,
			&i.ValidationRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HostFriendlyName,
			&i.HostHostname,
			&i.TriggeredByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatchRunsOrderByStartedAt = `-- name: ListPatchRunsOrderByStartedAt :many
SELECT pr.id, pr.host_id, pr.job_id, pr.patch_type, pr.package_name, pr.package_names, pr.status, pr.shell_output, pr.error_message, pr.started_at, pr.completed_at, pr.scheduled_at, pr.triggered_by_user_id, pr.approved_by_user_id, pr.dry_run, pr.packages_affected, pr.policy_id, pr.policy_name, pr.policy_snapshot, pr.validation_run_id, pr.created_at, pr.updated_at, h.friendly_name AS host_friendly_name, h.hostname AS host_hostname, u.username AS triggered_by_username
FROM patch_runs pr
LEFT JOIN hosts h ON pr.host_id = h.id
LEFT JOIN users u ON pr.triggered_by_user_id = u.id
WHERE ($1::text = '' OR pr.host_id = $1)
  AND (
    $2::text = ''
    OR ($2::text = 'active' AND pr.status IN ('queued', 'running'))
    OR ($2::text <> 'active' AND pr.status = $2)
  )
  AND ($3::text = '' OR pr.patch_type = $3)
ORDER BY COALESCE(pr.started_at, pr.created_at) DESC NULLS LAST, pr.created_at DESC
LIMIT $5 OFFSET $4
`

type ListPatchRunsOrderByStartedAtParams struct {
	HostID    string `json:"host_id"`
	Status    string `json:"status"`
	PatchType string `json:"patch_type"`
	OffsetArg int32  `json:"offset_arg"`
	LimitArg  int32  `json:"limit_arg"`
}

type ListPatchRunsOrderByStartedAtRow struct {
	ID                  string           `json:"id"`
	HostID              string           `json:"host_id"`
	JobID               string           `json:"job_id"`
	PatchType           string           `json:"patch_type"`
	PackageName         *string          `json:"package_name"`
	PackageNames        []byte           `json:"package_names"`
	Status              string           `json:"status"`
	ShellOutput         string           `json:"shell_output"`
	ErrorMessage        *string          `json:"error_message"`
	StartedAt           pgtype.Timestamp `json:"started_at"`
	CompletedAt         pgtype.Timestamp `json:"completed_at"`
	ScheduledAt         pgtype.Timestamp `json:"scheduled_at"`
	TriggeredByUserID   *string          `json:"triggered_by_user_id"`
	ApprovedByUserID    *string          `json:"approved_by_user_id"`
	DryRun              bool             `json:"dry_run"`
	PackagesAffected    []byte           `json:"packages_affected"`
	PolicyID            *string          `json:"policy_id"`
	PolicyName          *string          `json:"policy_name"`
	PolicySnapshot      []byte           `json:"policy_snapshot"`
	ValidationRunID     *string          `json:"validation_run_id"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	HostFriendlyName    *string          `json:"host_friendly_name"`
	HostHostname        *string          `json:"host_hostname"`
	TriggeredByUsername *string          `json:"triggered_by_username"`
}

func (q *Queries) ListPatchRunsOrderByStartedAt(ctx context.Context, arg ListPatchRunsOrderByStartedAtParams) ([]ListPatchRunsOrderByStartedAtRow, error) {
	rows, err := q.db.Query(ctx, listPatchRunsOrderByStartedAt,
		arg.HostID,
		arg.Status,
		arg.PatchType,
		arg.OffsetArg,
		arg.LimitArg,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPatchRunsOrderByStartedAtRow
	for rows.Next() {
		var i ListPatchRunsOrderByStartedAtRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.JobID,
			&i.PatchType,
			&i.PackageName,
			&i.PackageNames,
			&i.Status,
			&i.ShellOutput,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ScheduledAt,
			&i.TriggeredByUserID,
			&i.ApprovedByUserID,
			&i.DryRun,
			&i.PackagesAffected,
			&i.PolicyID,
			&i.PolicyName,
			&i.PolicySnapshot,
			&i.ValidationRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HostFriendlyName,
			&i.HostHostname,
			&i.TriggeredByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatchRunsOrderByStartedAtAsc = `-- name: ListPatchRunsOrderByStartedAtAsc :many
SELECT pr.id, pr.host_id, pr.job_id, pr.patch_type, pr.package_name, pr.package_names, pr.status, pr.shell_output, pr.error_message, pr.started_at, pr.completed_at, pr.scheduled_at, pr.triggered_by_user_id, pr.approved_by_user_id, pr.dry_run, pr.packages_affected, pr.policy_id, pr.policy_name, pr.policy_snapshot, pr.validation_run_id, pr.created_at, pr.updated_at, h.friendly_name AS host_friendly_name, h.hostname AS host_hostname, u.username AS triggered_by_username
FROM patch_runs pr
LEFT JOIN hosts h ON pr.host_id = h.id
LEFT JOIN users u ON pr.triggered_by_user_id = u.id
WHERE ($1::text = '' OR pr.host_id = $1)
  AND (
    $2::text = ''
    OR ($2::text = 'active' AND pr.status IN ('queued', 'running'))
    OR ($2::text <> 'active' AND pr.status = $2)
  )
  AND ($3::text = '' OR pr.patch_type = $3)
ORDER BY COALESCE(pr.started_at, pr.created_at) ASC NULLS LAST, pr.created_at DESC
LIMIT $5 OFFSET $4
`

type ListPatchRunsOrderByStartedAtAscParams struct {
	HostID    string `json:"host_id"`
	Status    string `json:"status"`
	PatchType string `json:"patch_type"`
	OffsetArg int32  `json:"offset_arg"`
	LimitArg  int32  `json:"limit_arg"`
}

type ListPatchRunsOrderByStartedAtAscRow struct {
	ID                  string           `json:"id"`
	HostID              string           `json:"host_id"`
	JobID               string           `json:"job_id"`
	PatchType           string           `json:"patch_type"`
	PackageName         *string          `json:"package_name"`
	PackageNames        []byte           `json:"package_names"`
	Status              string           `json:"status"`
	ShellOutput         string           `json:"shell_output"`
	ErrorMessage        *string          `json:"error_message"`
	StartedAt           pgtype.Timestamp `json:"started_at"`
	CompletedAt         pgtype.Timestamp `json:"completed_at"`
	ScheduledAt         pgtype.Timestamp `json:"scheduled_at"`
	TriggeredByUserID   *string          `json:"triggered_by_user_id"`
	ApprovedByUserID    *string          `json:"approved_by_user_id"`
	DryRun              bool             `json:"dry_run"`
	PackagesAffected    []byte           `json:"packages_affected"`
	PolicyID            *string          `json:"policy_id"`
	PolicyName          *string          `json:"policy_name"`
	PolicySnapshot      []byte           `json:"policy_snapshot"`
	ValidationRunID     *string          `json:"validation_run_id"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	HostFriendlyName    *string          `json:"host_friendly_name"`
	HostHostname        *string          `json:"host_hostname"`
	TriggeredByUsername *string          `json:"triggered_by_username"`
}

func (q *Queries) ListPatchRunsOrderByStartedAtAsc(ctx context.Context, arg ListPatchRunsOrderByStartedAtAscParams) ([]ListPatchRunsOrderByStartedAtAscRow, error) {
	rows, err := q.db.Query(ctx, listPatchRunsOrderByStartedAtAsc,
		arg.HostID,
		arg.Status,
		arg.PatchType,
		arg.OffsetArg,
		arg.LimitArg,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPatchRunsOrderByStartedAtAscRow
	for rows.Next() {
		var i ListPatchRunsOrderByStartedAtAscRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.JobID,
			&i.PatchType,
			&i.PackageName,
			&i.PackageNames,
			&i.Status,
			&i.ShellOutput,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ScheduledAt,
			&i.TriggeredByUserID,
			&i.ApprovedByUserID,
			&i.DryRun,
			&i.PackagesAffected,
			&i.PolicyID,
			&i.PolicyName,
			&i.PolicySnapshot,
			&i.ValidationRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HostFriendlyName,
			&i.HostHostname,
			&i.TriggeredByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatchRunsOrderByStatus = `-- name: ListPatchRunsOrderByStatus :many
SELECT pr.id, pr.host_id, pr.job_id, pr.patch_type, pr.package_name, pr.package_names, pr.status, pr.shell_output, pr.error_message, pr.started_at, pr.completed_at, pr.scheduled_at, pr.triggered_by_user_id, pr.approved_by_user_id, pr.dry_run, pr.packages_affected, pr.policy_id, pr.policy_name, pr.policy_snapshot, pr.validation_run_id, pr.created_at, pr.updated_at, h.friendly_name AS host_friendly_name, h.hostname AS host_hostname, u.username AS triggered_by_username
FROM patch_runs pr
LEFT JOIN hosts h ON pr.host_id = h.id
LEFT JOIN users u ON pr.triggered_by_user_id = u.id
WHERE ($1::text = '' OR pr.host_id = $1)
  AND (
    $2::text = ''
    OR ($2::text = 'active' AND pr.status IN ('queued', 'running'))
    OR ($2::text <> 'active' AND pr.status = $2)
  )
  AND ($3::text = '' OR pr.patch_type = $3)
ORDER BY pr.status ASC, pr.created_at DESC
LIMIT $5 OFFSET $4
`

type ListPatchRunsOrderByStatusParams struct {
	HostID    string `json:"host_id"`
	Status    string `json:"status"`
	PatchType string `json:"patch_type"`
	OffsetArg int32  `json:"offset_arg"`
	LimitArg  int32  `json:"limit_arg"`
}

type ListPatchRunsOrderByStatusRow struct {
	ID                  string           `json:"id"`
	HostID              string           `json:"host_id"`
	JobID               string           `json:"job_id"`
	PatchType           string           `json:"patch_type"`
	PackageName         *string          `json:"package_name"`
	PackageNames        []byte           `json:"package_names"`
	Status              string           `json:"status"`
	ShellOutput         string           `json:"shell_output"`
	ErrorMessage        *string          `json:"error_message"`
	StartedAt           pgtype.Timestamp `json:"started_at"`
	CompletedAt         pgtype.Timestamp `json:"completed_at"`
	ScheduledAt         pgtype.Timestamp `json:"scheduled_at"`
	TriggeredByUserID   *string          `json:"triggered_by_user_id"`
	ApprovedByUserID    *string          `json:"approved_by_user_id"`
	DryRun              bool             `json:"dry_run"`
	PackagesAffected    []byte           `json:"packages_affected"`
	PolicyID            *string          `json:"policy_id"`
	PolicyName          *string          `json:"policy_name"`
	PolicySnapshot      []byte           `json:"policy_snapshot"`
	ValidationRunID     *string          `json:"validation_run_id"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	HostFriendlyName    *string          `json:"host_friendly_name"`
	HostHostname        *string          `json:"host_hostname"`
	TriggeredByUsername *string          `json:"triggered_by_username"`
}

func (q *Queries) ListPatchRunsOrderByStatus(ctx context.Context, arg ListPatchRunsOrderByStatusParams) ([]ListPatchRunsOrderByStatusRow, error) {
	rows, err := q.db.Query(ctx, listPatchRunsOrderByStatus,
		arg.HostID,
		arg.Status,
		arg.PatchType,
		arg.OffsetArg,
		arg.LimitArg,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPatchRunsOrderByStatusRow
	for rows.Next() {
		var i ListPatchRunsOrderByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.JobID,
			&i.PatchType,
			&i.PackageName,
			&i.PackageNames,
			&i.Status,
			&i.ShellOutput,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ScheduledAt,
			&i.TriggeredByUserID,
			&i.ApprovedByUserID,
			&i.DryRun,
			&i.PackagesAffected,
			&i.PolicyID,
			&i.PolicyName,
			&i.PolicySnapshot,
			&i.ValidationRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HostFriendlyName,
			&i.HostHostname,
			&i.TriggeredByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatchRunsOrderByStatusDesc = `-- name: ListPatchRunsOrderByStatusDesc :many
SELECT pr.id, pr.host_id, pr.job_id, pr.patch_type, pr.package_name, pr.package_names, pr.status, pr.shell_output, pr.error_message, pr.started_at, pr.completed_at, pr.scheduled_at, pr.triggered_by_user_id, pr.approved_by_user_id, pr.dry_run, pr.packages_affected, pr.policy_id, pr.policy_name, pr.policy_snapshot, pr.validation_run_id, pr.created_at, pr.updated_at, h.friendly_name AS host_friendly_name, h.hostname AS host_hostname, u.username AS triggered_by_username
FROM patch_runs pr
LEFT JOIN hosts h ON pr.host_id = h.id
LEFT JOIN users u ON pr.triggered_by_user_id = u.id
WHERE ($1::text = '' OR pr.host_id = $1)
  AND (
    $2::text = ''
    OR ($2::text = 'active' AND pr.status IN ('queued', 'running'))
    OR ($2::text <> 'active' AND pr.status = $2)
  )
  AND ($3::text = '' OR pr.patch_type = $3)
ORDER BY pr.status DESC, pr.created_at DESC
LIMIT $5 OFFSET $4
`

type ListPatchRunsOrderByStatusDescParams struct {
	HostID    string `json:"host_id"`
	Status    string `json:"status"`
	PatchType string `json:"patch_type"`
	OffsetArg int32  `json:"offset_arg"`
	LimitArg  int32  `json:"limit_arg"`
}

type ListPatchRunsOrderByStatusDescRow struct {
	ID                  string           `json:"id"`
	HostID              string           `json:"host_id"`
	JobID               string           `json:"job_id"`
	PatchType           string           `json:"patch_type"`
	PackageName         *string          `json:"package_name"`
	PackageNames        []byte           `json:"package_names"`
	Status              string           `json:"status"`
	ShellOutput         string           `json:"shell_output"`
	ErrorMessage        *string          `json:"error_message"`
	StartedAt           pgtype.Timestamp `json:"started_at"`
	CompletedAt         pgtype.Timestamp `json:"completed_at"`
	ScheduledAt         pgtype.Timestamp `json:"scheduled_at"`
	TriggeredByUserID   *string          `json:"triggered_by_user_id"`
	ApprovedByUserID    *string          `json:"approved_by_user_id"`
	DryRun              bool             `json:"dry_run"`
	PackagesAffected    []byte           `json:"packages_affected"`
	PolicyID            *string          `json:"policy_id"`
	PolicyName          *string          `json:"policy_name"`
	PolicySnapshot      []byte           `json:"policy_snapshot"`
	ValidationRunID     *string          `json:"validation_run_id"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	HostFriendlyName    *string          `json:"host_friendly_name"`
	HostHostname        *string          `json:"host_hostname"`
	TriggeredByUsername *string          `json:"triggered_by_username"`
}

func (q *Queries) ListPatchRunsOrderByStatusDesc(ctx context.Context, arg ListPatchRunsOrderByStatusDescParams) ([]ListPatchRunsOrderByStatusDescRow, error) {
	rows, err := q.db.Query(ctx, listPatchRunsOrderByStatusDesc,
		arg.HostID,
		arg.Status,
		arg.PatchType,
		arg.OffsetArg,
		arg.LimitArg,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPatchRunsOrderByStatusDescRow
	for rows.Next() {
		var i ListPatchRunsOrderByStatusDescRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.JobID,
			&i.PatchType,
			&i.PackageName,
			&i.PackageNames,
			&i.Status,
			&i.ShellOutput,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ScheduledAt,
			&i.TriggeredByUserID,
			&i.ApprovedByUserID,
			&i.DryRun,
			&i.PackagesAffected,
			&i.PolicyID,
			&i.PolicyName,
			&i.PolicySnapshot,
			&i.ValidationRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HostFriendlyName,
			&i.HostHostname,
			&i.TriggeredByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentPatchRuns = `-- name: ListRecentPatchRuns :many
SELECT pr.id, pr.host_id, pr.job_id, pr.patch_type, pr.package_name, pr.package_names, pr.status, pr.shell_output, pr.error_message, pr.started_at, pr.completed_at, pr.scheduled_at, pr.triggered_by_user_id, pr.approved_by_user_id, pr.dry_run, pr.packages_affected, pr.policy_id, pr.policy_name, pr.policy_snapshot, pr.validation_run_id, pr.created_at, pr.updated_at, h.friendly_name AS host_friendly_name, h.hostname AS host_hostname, u.username AS triggered_by_username
FROM patch_runs pr
LEFT JOIN hosts h ON pr.host_id = h.id
LEFT JOIN users u ON pr.triggered_by_user_id = u.id
WHERE (pr.dry_run = false OR pr.dry_run IS NULL)
ORDER BY pr.created_at DESC
LIMIT $1
`

type ListRecentPatchRunsRow struct {
	ID                  string           `json:"id"`
	HostID              string           `json:"host_id"`
	JobID               string           `json:"job_id"`
	PatchType           string           `json:"patch_type"`
	PackageName         *string          `json:"package_name"`
	PackageNames        []byte           `json:"package_names"`
	Status              string           `json:"status"`
	ShellOutput         string           `json:"shell_output"`
	ErrorMessage        *string          `json:"error_message"`
	StartedAt           pgtype.Timestamp `json:"started_at"`
	CompletedAt         pgtype.Timestamp `json:"completed_at"`
	ScheduledAt         pgtype.Timestamp `json:"scheduled_at"`
	TriggeredByUserID   *string          `json:"triggered_by_user_id"`
	ApprovedByUserID    *string          `json:"approved_by_user_id"`
	DryRun              bool             `json:"dry_run"`
	PackagesAffected    []byte           `json:"packages_affected"`
	PolicyID            *string          `json:"policy_id"`
	PolicyName          *string          `json:"policy_name"`
	PolicySnapshot      []byte           `json:"policy_snapshot"`
	ValidationRunID     *string          `json:"validation_run_id"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	HostFriendlyName    *string          `json:"host_friendly_name"`
	HostHostname        *string          `json:"host_hostname"`
	TriggeredByUsername *string          `json:"triggered_by_username"`
}

func (q *Queries) ListRecentPatchRuns(ctx context.Context, limit int32) ([]ListRecentPatchRunsRow, error) {
	rows, err := q.db.Query(ctx, listRecentPatchRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentPatchRunsRow
	for rows.Next() {
		var i ListRecentPatchRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.JobID,
			&i.PatchType,
			&i.PackageName,
			&i.PackageNames,
			&i.Status,
			&i.ShellOutput,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ScheduledAt,
			&i.TriggeredByUserID,
			&i.ApprovedByUserID,
			&i.DryRun,
			&i.PackagesAffected,
			&i.PolicyID,
			&i.PolicyName,
			&i.PolicySnapshot,
			&i.ValidationRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HostFriendlyName,
			&i.HostHostname,
			&i.TriggeredByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPatchRunCancelledByUser = `-- name: MarkPatchRunCancelledByUser :execrows
UPDATE patch_runs SET status = 'cancelled', error_message = $2, completed_at = NOW(), updated_at = NOW()
WHERE id = $1
  AND status NOT IN ('cancelled','timed_out','completed','failed','validated','dry_run_completed')
`

type MarkPatchRunCancelledByUserParams struct {
	ID           string  `json:"id"`
	ErrorMessage *string `json:"error_message"`
}

// User-initiated cancel from StopRun. Deliberately does NOT touch shell_output
// so progress chunks the agent appended between our read and write are preserved.
// Same status guard as UpdatePatchRunCancelled.
func (q *Queries) MarkPatchRunCancelledByUser(ctx context.Context, arg MarkPatchRunCancelledByUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, markPatchRunCancelledByUser, arg.ID, arg.ErrorMessage)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markPatchRunsAgentDisconnected = `-- name: MarkPatchRunsAgentDisconnected :execrows
UPDATE patch_runs
SET status = 'agent_disconnected', error_message = $1, completed_at = NOW(), updated_at = NOW()
WHERE host_id = $2 AND status = 'running'
`

type MarkPatchRunsAgentDisconnectedParams struct {
	ErrorMessage *string `json:"error_message"`
	HostID       string  `json:"host_id"`
}

func (q *Queries) MarkPatchRunsAgentDisconnected(ctx context.Context, arg MarkPatchRunsAgentDisconnectedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markPatchRunsAgentDisconnected, arg.ErrorMessage, arg.HostID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markPatchRunsTimedOut = `-- name: MarkPatchRunsTimedOut :execrows
UPDATE patch_runs
SET status = 'timed_out', error_message = $1, completed_at = NOW(), updated_at = NOW()
WHERE status = 'running'
  AND updated_at < $2
`

type MarkPatchRunsTimedOutParams struct {
	ErrorMessage *string          `json:"error_message"`
	StaleBefore  pgtype.Timestamp `json:"stale_before"`
}

// Stall sweep. The predicate is deliberately "no activity since", NOT "started
// before": every progress chunk the agent streams bumps updated_at (see
// UpdatePatchRunProgress), so a long-but-healthy run (dist-upgrade on slow
// disk routinely exceeds 30 minutes) keeps refreshing its own liveness while a
// genuinely wedged run does not. Using elapsed-since-start here would mark
// every long run timed_out while it was still working and discard the real
// outcome the agent later reports.
func (q *Queries) MarkPatchRunsTimedOut(ctx context.Context, arg MarkPatchRunsTimedOutParams) (int64, error) {
	result, err := q.db.Exec(ctx, markPatchRunsTimedOut, arg.ErrorMessage, arg.StaleBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markValidationApproved = `-- name: MarkValidationApproved :execrows
UPDATE patch_runs SET status = 'approved', approved_by_user_id = $2, updated_at = NOW() WHERE id = $1 AND status IN ('validated', 'pending_validation', 'pending_approval')
`

type MarkValidationApprovedParams struct {
	ID               string  `json:"id"`
	ApprovedByUserID *string `json:"approved_by_user_id"`
}

// Declared :execrows, not :exec, because the status guard IS the concurrency
// control. Two approvals racing both pass the handler's Go-side status check;
// only one of them updates a row here, and the loser must be told so rather
// than going on to create a second patch run and enqueue a second task.
func (q *Queries) MarkValidationApproved(ctx context.Context, arg MarkValidationApprovedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markValidationApproved, arg.ID, arg.ApprovedByUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setPatchRunPolicySnapshot = `-- name: SetPatchRunPolicySnapshot :exec
UPDATE patch_runs SET policy_id = $2, policy_name = $3, policy_snapshot = $4, updated_at = NOW() WHERE id = $1
`

type SetPatchRunPolicySnapshotParams struct {
	ID             string  `json:"id"`
	PolicyID       *string `json:"policy_id"`
	PolicyName     *string `json:"policy_name"`
	PolicySnapshot []byte  `json:"policy_snapshot"`
}

func (q *Queries) SetPatchRunPolicySnapshot(ctx context.Context, arg SetPatchRunPolicySnapshotParams) error {
	_, err := q.db.Exec(ctx, setPatchRunPolicySnapshot,
		arg.ID,
		arg.PolicyID,
		arg.PolicyName,
		arg.PolicySnapshot,
	)
	return err
}

const updatePatchPolicy = `-- name: UpdatePatchPolicy :exec
UPDATE patch_policies
SET name = $2, description = $3, patch_delay_type = $4, delay_minutes = $5, fixed_time_utc = $6, timezone = $7, updated_at = NOW()
WHERE id = $1
`

type UpdatePatchPolicyParams struct {
	ID             string  `json:"id"`
	Name           string  `json:"name"`
	Description    *string `json:"description"`
	PatchDelayType string  `json:"patch_delay_type"`
	DelayMinutes   *int32  `json:"delay_minutes"`
	FixedTimeUtc   *string `json:"fixed_time_utc"`
	Timezone       *string `json:"timezone"`
}

func (q *Queries) UpdatePatchPolicy(ctx context.Context, arg UpdatePatchPolicyParams) error {
	_, err := q.db.Exec(ctx, updatePatchPolicy,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PatchDelayType,
		arg.DelayMinutes,
		arg.FixedTimeUtc,
		arg.Timezone,
	)
	return err
}

const updatePatchRunCancelled = `-- name: UpdatePatchRunCancelled :execrows
UPDATE patch_runs SET status = 'cancelled', shell_output = $2, error_message = $3, completed_at = NOW(), updated_at = NOW()
WHERE id = $1
  AND status NOT IN ('cancelled','completed','failed','validated','dry_run_completed')
`

type UpdatePatchRunCancelledParams struct {
	ID           string  `json:"id"`
	ShellOutput  string  `json:"shell_output"`
	ErrorMessage *string `json:"error_message"`
}

// Terminal cancelled state set by the agent's late "cancelled" stage report.
// Replaces shell_output with the full captured output so rollback/cleanup text is preserved.
// :execrows so the handler can detect concurrent termination (rows=0) cleanly.
// agent_disconnected and timed_out are intentionally NOT in the guard so a
// recovering agent that posts a late "cancelled" can still unwedge the row.
// 'cancelled' STAYS in the guard: a DB-first user cancel already owns the row,
// and the fields-only UpdatePatchRunCancelledOutput below is the path that
// lets the agent's authoritative output land on it without a status change.
func (q *Queries) UpdatePatchRunCancelled(ctx context.Context, arg UpdatePatchRunCancelledParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePatchRunCancelled, arg.ID, arg.ShellOutput, arg.ErrorMessage)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePatchRunCancelledOutput = `-- name: UpdatePatchRunCancelledOutput :execrows
UPDATE patch_runs
SET shell_output = $2,
    error_message = COALESCE(error_message, $3),
    updated_at = NOW()
WHERE id = $1
  AND status = 'cancelled'
`

type UpdatePatchRunCancelledOutputParams struct {
	ID           string  `json:"id"`
	ShellOutput  string  `json:"shell_output"`
	ErrorMessage *string `json:"error_message"`
}

// Fields-only follow-up for the DB-first user-cancel path
// (MarkPatchRunCancelledByUser sets status='cancelled' immediately, so the
// agent's subsequent "cancelled" stage report is blocked by the status guard
// on UpdatePatchRunCancelled). This id-scoped update writes ONLY the agent's
// authoritative captured output; it never changes status, so a 'completed'
// report can still not overwrite a cancelled run. error_message is preserved
// when already set (the user-initiated reason is the more informative one)
// and filled in from the agent only when the column is still NULL.
func (q *Queries) UpdatePatchRunCancelledOutput(ctx context.Context, arg UpdatePatchRunCancelledOutputParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePatchRunCancelledOutput, arg.ID, arg.ShellOutput, arg.ErrorMessage)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePatchRunCompleted = `-- name: UpdatePatchRunCompleted :exec
UPDATE patch_runs SET status = 'completed', shell_output = $2, completed_at = NOW(), updated_at = NOW()
WHERE id = $1
  AND status NOT IN ('cancelled','completed','failed','validated','dry_run_completed')
`

type UpdatePatchRunCompletedParams struct {
	ID          string `json:"id"`
	ShellOutput string `json:"shell_output"`
}

// REPLACE (not append) - agent streams progress chunks then sends final full output.
// agent_disconnected and timed_out are intentionally NOT in the guard: both are
// server-side "we gave up waiting" markers, so a recovering agent posting a late
// genuine "completed" must be able to unwedge the row and deliver the real output.
func (q *Queries) UpdatePatchRunCompleted(ctx context.Context, arg UpdatePatchRunCompletedParams) error {
	_, err := q.db.Exec(ctx, updatePatchRunCompleted, arg.ID, arg.ShellOutput)
	return err
}

const updatePatchRunFailed = `-- name: UpdatePatchRunFailed :exec
UPDATE patch_runs SET status = 'failed', shell_output = $2, error_message = $3, completed_at = NOW(), updated_at = NOW()
WHERE id = $1
  AND status NOT IN ('cancelled','completed','failed','validated','dry_run_completed')
`

type UpdatePatchRunFailedParams struct {
	ID           string  `json:"id"`
	ShellOutput  string  `json:"shell_output"`
	ErrorMessage *string `json:"error_message"`
}

// REPLACE (not append) - agent streams progress chunks then sends final full output.
// agent_disconnected and timed_out are intentionally NOT in the guard so a
// recovering agent that posts a late "failed" can still unwedge the row.
func (q *Queries) UpdatePatchRunFailed(ctx context.Context, arg UpdatePatchRunFailedParams) error {
	_, err := q.db.Exec(ctx, updatePatchRunFailed, arg.ID, arg.ShellOutput, arg.ErrorMessage)
	return err
}

const updatePatchRunPackagesAffected = `-- name: UpdatePatchRunPackagesAffected :exec
UPDATE patch_runs SET packages_affected = $2, updated_at = NOW() WHERE id = $1
`

type UpdatePatchRunPackagesAffectedParams struct {
	ID               string `json:"id"`
	PackagesAffected []byte `json:"packages_affected"`
}

func (q *Queries) UpdatePatchRunPackagesAffected(ctx context.Context, arg UpdatePatchRunPackagesAffectedParams) error {
	_, err := q.db.Exec(ctx, updatePatchRunPackagesAffected, arg.ID, arg.PackagesAffected)
	return err
}

const updatePatchRunProgress = `-- name: UpdatePatchRunProgress :exec
UPDATE patch_runs SET shell_output = shell_output || $2, updated_at = NOW() WHERE id = $1
`

type UpdatePatchRunProgressParams struct {
	ID          string `json:"id"`
	ShellOutput string `json:"shell_output"`
}

func (q *Queries) UpdatePatchRunProgress(ctx context.Context, arg UpdatePatchRunProgressParams) error {
	_, err := q.db.Exec(ctx, updatePatchRunProgress, arg.ID, arg.ShellOutput)
	return err
}

const updatePatchRunScheduledAt = `-- name: UpdatePatchRunScheduledAt :exec
UPDATE patch_runs SET scheduled_at = $2, updated_at = NOW() WHERE id = $1
`

type UpdatePatchRunScheduledAtParams struct {
	ID          string           `json:"id"`
	ScheduledAt pgtype.Timestamp `json:"scheduled_at"`
}

func (q *Queries) UpdatePatchRunScheduledAt(ctx context.Context, arg UpdatePatchRunScheduledAtParams) error {
	_, err := q.db.Exec(ctx, updatePatchRunScheduledAt, arg.ID, arg.ScheduledAt)
	return err
}

const updatePatchRunStarted = `-- name: UpdatePatchRunStarted :exec
UPDATE patch_runs SET status = 'running', started_at = NOW(), completed_at = NULL,
    shell_output = '', packages_affected = NULL, error_message = NULL, updated_at = NOW()
WHERE id = $1
  AND status NOT IN ('cancelled','timed_out','completed','failed','validated','dry_run_completed')
`

// Clear dry-run output fields so real-run output starts fresh.
// Status guard prevents an in-flight agent message from clobbering an
// already-terminated run (cancelled/timed_out/etc.). agent_disconnected is
// intentionally NOT in the guard so a recovering agent can unwedge the row.
func (q *Queries) UpdatePatchRunStarted(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updatePatchRunStarted, id)
	return err
}

const updatePatchRunStatus = `-- name: UpdatePatchRunStatus :exec
UPDATE patch_runs SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdatePatchRunStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdatePatchRunStatus(ctx context.Context, arg UpdatePatchRunStatusParams) error {
	_, err := q.db.Exec(ctx, updatePatchRunStatus, arg.ID, arg.Status)
	return err
}

const updatePatchRunValidated = `-- name: UpdatePatchRunValidated :exec
UPDATE patch_runs SET status = 'validated', shell_output = $2, packages_affected = $3, completed_at = NOW(), updated_at = NOW() WHERE id = $1
`

type UpdatePatchRunValidatedParams struct {
	ID               string `json:"id"`
	ShellOutput      string `json:"shell_output"`
	PackagesAffected []byte `json:"packages_affected"`
}

// Agent streams progress chunks during the run, then sends the final authoritative
// output on the terminal stage; REPLACE (not append) so the final record is never
// a duplicate of the streamed progress.
func (q *Queries) UpdatePatchRunValidated(ctx context.Context, arg UpdatePatchRunValidatedParams) error {
	_, err := q.db.Exec(ctx, updatePatchRunValidated, arg.ID, arg.ShellOutput, arg.PackagesAffected)
	return err
}
