// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Bulk insert N host_packages rows in a single statement. Replaces the legacy
	// InsertHostPackage and InsertHostPackageWithWUA per-row inserts — one path
	// now covers Linux/FreeBSD (all wua_* columns NULL) and Windows (wua_* set).
	//
	// DeleteHostPackagesByHostID has already cleared this host's rows, so no
	// ON CONFLICT clause is needed: the (host_id, package_id) UNIQUE constraint
	// cannot fire.
	//
	// Caller pre-sorts by package_id (defensive — host_packages rows for one host
	// cannot cross-host-deadlock because of host-partitioning, but consistent
	// ordering is cheap insurance and aids index locality on (host_id, package_id)).
	//
	// Input shape: a single jsonb array of objects with one key per column.
	//
	// We use `jsonb_to_recordset` with a typed column list rather than
	// `jsonb_array_elements + elem->>'col'` per column. The recordset variant
	// parses each input element ONCE into a typed tuple; the array_elements
	// variant re-enters the JSON parser for each `->>` operator (15 columns ×
	// per-row = 15 lookups/row). Benchmarks at 10k packages show roughly a
	// 3x decode speedup, which matters for the report-heavy workload at 100+
	// hosts. JSON nulls become SQL NULLs directly so callers do not need
	// empty-string sentinels — but the Go side still emits empty strings for
	// text fields, which the NULLIF wrappers below collapse to NULL. Both
	// conventions remain valid; do not change one without the other.
	//
	// wua_categories is stored as jsonb and is declared as a jsonb column in
	// the recordset spec, so it round-trips as a real JSON value (array or
	// null) without going through text serialisation.
	BulkInsertHostPackages(ctx context.Context, payload []byte) error
	// Bulk upsert N packages in a single statement, eliminating per-row round-trips.
	//
	// Caller MUST pre-sort the input rows by name AND deduplicate by name
	// (deterministic lock acquisition; ON CONFLICT cannot affect the same row
	// twice in one statement — cardinality_violation 21000). The inner ORDER BY
	// name in the `input` CTE is belt-and-braces: PostgreSQL's executor processes
	// INSERT...SELECT tuples in plan order, and the explicit Sort node above
	// jsonb_to_recordset guarantees that order even if the planner introduces
	// parallel workers (unlikely at this row count). Both layers must remain —
	// do not strip the ORDER BY thinking the Go-side sort is sufficient. Sorted
	// lock acquisition prevents the cross-host 40P01 deadlocks reported in
	// production.
	//
	// Input shape: a single jsonb array of objects, each with keys
	//   { id, name, description, category, latest_version }
	// We use jsonb_to_recordset rather than parallel text[]+unnest because sqlc
	// v1.x's static analyzer cannot resolve the multi-array unnest() overload
	// ("function unnest(unknown, ...) does not exist"). jsonb_to_recordset gives
	// the same per-row shape with one well-typed parameter and zero overload
	// ambiguity.
	//
	// Description / category / latest_version are JSON nulls when the agent
	// omits them, which jsonb_to_recordset emits as SQL NULL directly.
	//
	// The DO UPDATE WHERE clause skips no-op updates: when the agent reports the
	// same description/category/latest_version that's already stored, no row
	// update happens and no dead tuple is created. Steady-state production
	// workloads with mostly-stable package catalogues see ~95% of upsert calls
	// become no-ops, drastically reducing WAL volume and vacuum pressure.
	//
	// It does NOT avoid the row lock: the ON CONFLICT arbiter takes its
	// FOR NO KEY UPDATE lock on the conflicting tuple BEFORE evaluating this
	// WHERE, and holds it to end of transaction whether or not the update
	// fires. Deadlock freedom comes from the sorted lock acquisition above, not
	// from this clause.
	//
	// The UNION ALL fallback returns (id, name) for input rows that did NOT fire
	// DO UPDATE (i.e. the values are unchanged), covering the single-threaded
	// case where every input name resolves to an id.
	//
	// It is NOT complete under concurrency. The ON CONFLICT arbiter re-reads the
	// conflicting row outside the statement snapshot, so it can see a row another
	// transaction committed after this statement began; if that row's values are
	// identical the skip-no-op WHERE suppresses RETURNING, while the fallback
	// SELECT still reads `packages` at the (older) statement snapshot and cannot
	// see the row either. That name is then absent from the result. The caller
	// MUST detect missing names and resolve them with GetPackageIDsByNames, which
	// runs as a separate statement and therefore takes a fresh snapshot.
	//
	// The DO UPDATE intentionally touches only NON-KEY columns
	// (description / category / latest_version / updated_at). The row lock taken
	// by ON CONFLICT is therefore FOR NO KEY UPDATE, which does NOT conflict
	// with FOR KEY SHARE locks held by concurrent BulkInsertHostPackages FK
	// checks on the same packages.id rows. Do not extend this DO UPDATE to
	// touch id or name without re-evaluating the lock-compatibility analysis.
	// Fallback: input rows whose values matched the existing row exactly (so the
	// skip-no-op WHERE made the DO UPDATE a no-op and RETURNING omitted them).
	// Re-parsing the JSON here is cheap (kilobytes, in-memory) and avoids a
	// per-row round-trip — the alternative was a SELECT loop in Go.
	BulkUpsertPackages(ctx context.Context, payload []byte) ([]BulkUpsertPackagesRow, error)
	ClearHostComplianceHashOnEnable(ctx context.Context, arg ClearHostComplianceHashOnEnableParams) error
	// Force a fresh docker payload on next check-in by NULLing the hash whenever
	// the operator re-enables docker. If the agent was already streaming docker
	// data (docker_enabled stays true) the hash is left alone.
	ClearHostDockerHashOnEnable(ctx context.Context, arg ClearHostDockerHashOnEnableParams) error
	ClearScheduledAt(ctx context.Context, id string) error
	CountActiveAdmins(ctx context.Context) (int64, error)
	CountActiveRepositories(ctx context.Context) (int32, error)
	CountAdmins(ctx context.Context) (int64, error)
	// Agent Activity feed. Returns the merged time-ordered stream of agent comm
	// rows for a given host: inbound reports (update_history) AND outbound jobs
	// (job_history). The two source tables have different shapes; this query
	// normalises them to one column set and discriminates via the `kind` column
	// ('report' or 'job'). Caller passes the host_id, optional direction / type /
	// status filters, optional search string (ILIKE on error_message and job
	// output), optional time-range / limit / offset for pagination.
	//
	// CountAgentActivity returns the filtered total separately so stale/deep-linked
	// pages beyond the end can still report the real total.
	//
	// The since_ts arg uses sqlc.narg (nullable) on both branches; pgx encodes
	// pgtype.Timestamp{Valid:false} as SQL NULL, which the IS NULL guard catches.
	CountAgentActivity(ctx context.Context, arg CountAgentActivityParams) (int32, error)
	CountComplianceResultsByScan(ctx context.Context, arg CountComplianceResultsByScanParams) (int64, error)
	CountComplianceScansByHost(ctx context.Context, hostID string) (int64, error)
	CountComplianceScansHistory(ctx context.Context, arg CountComplianceScansHistoryParams) (int64, error)
	CountContainers(ctx context.Context, arg CountContainersParams) (int32, error)
	CountContainersByImageID(ctx context.Context, imageID *string) (int32, error)
	// Dashboard stats
	CountDockerHosts(ctx context.Context) (int32, error)
	CountEnabledHostRepositories(ctx context.Context) (int32, error)
	CountHosts(ctx context.Context) (int64, error)
	// Total count matching the same filter set as GetHostsWithCounts. Used by
	// the paginated UI so it can render "Showing X-Y of Z" and a correct page
	// count.
	CountHostsForList(ctx context.Context, arg CountHostsForListParams) (int32, error)
	CountHostsForPackage(ctx context.Context, arg CountHostsForPackageParams) (int32, error)
	CountImages(ctx context.Context, arg CountImagesParams) (int32, error)
	CountNetworks(ctx context.Context, arg CountNetworksParams) (int32, error)
	CountNetworksByHostID(ctx context.Context, hostID string) (int32, error)
	CountPatchRuns(ctx context.Context, arg CountPatchRunsParams) (int64, error)
	CountPatchRunsTotal(ctx context.Context) (int64, error)
	CountRepositories(ctx context.Context) (int32, error)
	CountRepositoriesForList(ctx context.Context, arg CountRepositoriesForListParams) (int32, error)
	CountSecureRepositories(ctx context.Context) (int32, error)
	CountSuperadmins(ctx context.Context) (int64, error)
	CountTfaRememberSessionsByUser(ctx context.Context, userID string) (int64, error)
	CountUnscannedHosts(ctx context.Context) (int64, error)
	CountUpdateHistory(ctx context.Context, hostID string) (int32, error)
	CountUsers(ctx context.Context) (int64, error)
	CountUsersByRole(ctx context.Context, role string) (int64, error)
	CountVolumes(ctx context.Context, arg CountVolumesParams) (int32, error)
	CountVolumesByHostID(ctx context.Context, hostID string) (int32, error)
	// Counts pending Windows Updates for a host (for dashboard/stats).
	CountWindowsUpdatesByHostID(ctx context.Context, hostID string) (CountWindowsUpdatesByHostIDRow, error)
	CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error)
	CreateAutoEnrollmentToken(ctx context.Context, arg CreateAutoEnrollmentTokenParams) error
	CreateComplianceProfile(ctx context.Context, arg CreateComplianceProfileParams) (ComplianceProfile, error)
	CreateComplianceResult(ctx context.Context, arg CreateComplianceResultParams) (ComplianceResult, error)
	CreateComplianceRule(ctx context.Context, arg CreateComplianceRuleParams) (ComplianceRule, error)
	CreateComplianceScan(ctx context.Context, arg CreateComplianceScanParams) (ComplianceScan, error)
	CreateDiscordUser(ctx context.Context, arg CreateDiscordUserParams) error
	CreateHost(ctx context.Context, arg CreateHostParams) error
	CreateHostGroup(ctx context.Context, arg CreateHostGroupParams) error
	CreateNotificationDestination(ctx context.Context, arg CreateNotificationDestinationParams) (NotificationDestination, error)
	CreateNotificationRoute(ctx context.Context, arg CreateNotificationRouteParams) (NotificationRoute, error)
	CreateOidcUser(ctx context.Context, arg CreateOidcUserParams) error
	CreatePatchPolicy(ctx context.Context, arg CreatePatchPolicyParams) error
	CreatePatchPolicyAssignment(ctx context.Context, arg CreatePatchPolicyAssignmentParams) error
	CreatePatchPolicyExclusion(ctx context.Context, arg CreatePatchPolicyExclusionParams) error
	// patch_runs
	CreatePatchRun(ctx context.Context, arg CreatePatchRunParams) error
	CreateScheduledReport(ctx context.Context, arg CreateScheduledReportParams) (ScheduledReport, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateTrustedDevice(ctx context.Context, arg CreateTrustedDeviceParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteAlert(ctx context.Context, id string) error
	DeleteAlertsByIDs(ctx context.Context, dollar_1 []string) error
	DeleteAutoEnrollmentToken(ctx context.Context, id string) error
	DeleteComplianceResultsByScan(ctx context.Context, scanID string) error
	DeleteContainer(ctx context.Context, id string) error
	DeleteContainersByIDs(ctx context.Context, dollar_1 []string) error
	DeleteDashboardPreferencesByUserID(ctx context.Context, userID string) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteExpiredTrustedDevices(ctx context.Context) error
	DeleteHost(ctx context.Context, id string) error
	DeleteHostGroup(ctx context.Context, id string) error
	DeleteHostGroupMemberships(ctx context.Context, hostID string) error
	// Removes a host_package row that was reported as superseded by the agent.
	DeleteHostPackageByWUAGUID(ctx context.Context, arg DeleteHostPackageByWUAGUIDParams) error
	DeleteHostPackagesByHostID(ctx context.Context, hostID string) error
	// Bulk-removes superseded Windows Update entries for a host.
	DeleteHostPackagesByWUAGUIDs(ctx context.Context, arg DeleteHostPackagesByWUAGUIDsParams) error
	DeleteHostRepositoriesByHostID(ctx context.Context, hostID string) error
	DeleteHostsByIDs(ctx context.Context, dollar_1 []string) error
	DeleteImageByID(ctx context.Context, id string) error
	DeleteImageUpdatesByImageID(ctx context.Context, imageID string) error
	DeleteImagesByIDs(ctx context.Context, dollar_1 []string) error
	DeleteNetwork(ctx context.Context, id string) error
	DeleteNotificationDestination(ctx context.Context, id string) error
	DeleteNotificationRoute(ctx context.Context, id string) error
	// Retention sweep target, deliberately batched. Steady state deletes a day's
	// worth of rows, but the FIRST sweep after upgrading an existing install has
	// to clear the entire pre-2.0.3 update_history backlog, which was never pruned
	// before — millions of rows on a multi-year install. An unbounded single-
	// statement DELETE would hold one transaction (and its locks / WAL / dead
	// tuples) open for the whole thing. The worker calls this in a loop until it
	// returns 0, so each transaction stays small and interruptible.
	//
	// Returns the number of rows deleted so the worker can both log the volume and
	// decide whether to keep looping.
	DeleteOldUpdateHistoryBatch(ctx context.Context, arg DeleteOldUpdateHistoryBatchParams) (int64, error)
	DeleteOldestTfaRememberSession(ctx context.Context, userID string) error
	DeletePackagesByIDs(ctx context.Context, dollar_1 []string) error
	DeletePatchPolicy(ctx context.Context, id string) error
	DeletePatchPolicyAssignment(ctx context.Context, id string) error
	DeletePatchPolicyExclusion(ctx context.Context, arg DeletePatchPolicyExclusionParams) error
	DeletePatchRun(ctx context.Context, id string) error
	DeletePendingConfig(ctx context.Context, hostID string) error
	DeletePreviousCompletedScansByHostAndProfile(ctx context.Context, arg DeletePreviousCompletedScansByHostAndProfileParams) error
	DeleteRepositoriesByIDs(ctx context.Context, dollar_1 []string) error
	DeleteRepository(ctx context.Context, id string) error
	DeleteRolePermissions(ctx context.Context, role string) error
	DeleteRunningComplianceScansByHost(ctx context.Context, hostID string) error
	DeleteScheduledReport(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id string) error
	DeleteVolume(ctx context.Context, id string) error
	DisableTfa(ctx context.Context, id string) error
	ExistsByUsernameOrEmail(ctx context.Context, arg ExistsByUsernameOrEmailParams) (bool, error)
	ExistsPatchPolicyExclusion(ctx context.Context, arg ExistsPatchPolicyExclusionParams) (bool, error)
	FindSessionByUserAndDevice(ctx context.Context, arg FindSessionByUserAndDeviceParams) (UserSession, error)
	FindSessionByUserAndDeviceID(ctx context.Context, arg FindSessionByUserAndDeviceIDParams) (UserSession, error)
	FindSessionWithTfaBypass(ctx context.Context, arg FindSessionWithTfaBypassParams) (FindSessionWithTfaBypassRow, error)
	FindValidTrustedDevice(ctx context.Context, arg FindValidTrustedDeviceParams) (UserTrustedDevice, error)
	GetAcceptedVersionsByUserID(ctx context.Context, userID string) ([]string, error)
	GetAlertActionByName(ctx context.Context, name string) (AlertAction, error)
	GetAlertByID(ctx context.Context, id string) (GetAlertByIDRow, error)
	GetAlertConfigByType(ctx context.Context, alertType string) (GetAlertConfigByTypeRow, error)
	GetAlertStatsBySeverity(ctx context.Context) ([]GetAlertStatsBySeverityRow, error)
	GetAlertsForCleanup(ctx context.Context, arg GetAlertsForCleanupParams) ([]GetAlertsForCleanupRow, error)
	GetAlertsToAutoResolve(ctx context.Context, arg GetAlertsToAutoResolveParams) ([]GetAlertsToAutoResolveRow, error)
	GetAutoEnrollmentTokenByID(ctx context.Context, id string) (GetAutoEnrollmentTokenByIDRow, error)
	GetAutoEnrollmentTokenByKey(ctx context.Context, tokenKey string) (AutoEnrollmentToken, error)
	GetAutoEnrollmentTokenRaw(ctx context.Context, id string) (AutoEnrollmentToken, error)
	GetCategories(ctx context.Context) ([]*string, error)
	GetComplianceProfileByID(ctx context.Context, id string) (ComplianceProfile, error)
	GetComplianceProfileByName(ctx context.Context, name string) (ComplianceProfile, error)
	GetComplianceResultSeverityBreakdown(ctx context.Context, scanID string) ([]GetComplianceResultSeverityBreakdownRow, error)
	GetComplianceResultSeverityBreakdownForScans(ctx context.Context, dollar_1 []string) ([]GetComplianceResultSeverityBreakdownForScansRow, error)
	GetComplianceResultStatusBreakdown(ctx context.Context, scanID string) ([]GetComplianceResultStatusBreakdownRow, error)
	GetComplianceResultsForRuleFromScans(ctx context.Context, arg GetComplianceResultsForRuleFromScansParams) ([]GetComplianceResultsForRuleFromScansRow, error)
	GetComplianceRuleByID(ctx context.Context, id string) (GetComplianceRuleByIDRow, error)
	GetComplianceRuleByProfileAndRef(ctx context.Context, arg GetComplianceRuleByProfileAndRefParams) (ComplianceRule, error)
	GetComplianceScanByID(ctx context.Context, id string) (GetComplianceScanByIDRow, error)
	GetComplianceScansForTrends(ctx context.Context, arg GetComplianceScansForTrendsParams) ([]GetComplianceScansForTrendsRow, error)
	// Containers
	GetContainerByID(ctx context.Context, id string) (DockerContainer, error)
	GetContainerCountsByImageIDs(ctx context.Context, dollar_1 []string) ([]GetContainerCountsByImageIDsRow, error)
	GetContainersByHostID(ctx context.Context, hostID string) ([]DockerContainer, error)
	GetContainersByImageID(ctx context.Context, arg GetContainersByImageIDParams) ([]DockerContainer, error)
	GetContainersByImageIDAll(ctx context.Context, imageID *string) ([]DockerContainer, error)
	GetContainersByStatus(ctx context.Context) ([]GetContainersByStatusRow, error)
	GetDashboardLayout(ctx context.Context, userID string) (DashboardLayout, error)
	GetDashboardStats(ctx context.Context, arg GetDashboardStatsParams) (GetDashboardStatsRow, error)
	// patch_policy_assignments
	GetDirectPatchPolicyAssignment(ctx context.Context, targetID string) (PatchPolicy, error)
	// Hosts (include hosts with containers, volumes, or networks)
	GetDistinctDockerHostIDs(ctx context.Context) ([]string, error)
	GetDockerDashboardStats(ctx context.Context) (GetDockerDashboardStatsRow, error)
	GetDockerHostsByIDs(ctx context.Context, dollar_1 []string) ([]GetDockerHostsByIDsRow, error)
	GetDockerHostsMinimalByIDs(ctx context.Context, dollar_1 []string) ([]GetDockerHostsMinimalByIDsRow, error)
	GetFirstComplianceProfileByType(ctx context.Context, type_ string) (ComplianceProfile, error)
	GetFirstSettings(ctx context.Context) (Setting, error)
	// The host counters here must match GetDashboardStats, otherwise a widget and
	// the dashboard card it mirrors report different numbers for the same fleet.
	// They previously filtered on status = 'active', which silently dropped hosts
	// that had been created but not yet enrolled. That filter also did not mean
	// what it appeared to: hosts.status is an enrolment lifecycle column and never
	// becomes 'inactive', so a host that stopped reporting was counted regardless.
	// Distinct counts are expressed as GROUP BY subqueries, not COUNT(DISTINCT),
	// and must stay that way. COUNT(DISTINCT) cannot stream: it sorts the whole
	// matching set, which at 3.7M host_packages rows spills multiple megabytes to
	// disk and costs ~3x what the identical aggregates cost in GetDashboardStats,
	// which already uses this shape. GROUP BY reads straight off the partial
	// covering indexes (idx_host_packages_needs_update_host_cover and the
	// _package / _security_package pair) and sorts nothing worth spilling.
	//
	// Exact, not approximate: the two forms differ only on NULL handling, and
	// host_id and package_id are both NOT NULL.
	GetHomepageStats(ctx context.Context, since pgtype.Timestamp) (GetHomepageStatsRow, error)
	GetHostByApiID(ctx context.Context, apiID string) (Host, error)
	GetHostByID(ctx context.Context, id string) (Host, error)
	// Single-row read used on the per-ping hot path. Returns the host's identity
	// and the six per-section hashes the server compares against incoming agent
	// hashes.
	GetHostCheckin(ctx context.Context, apiID string) (GetHostCheckinRow, error)
	// Cheap host-only counts for the sidebar / navbar widgets. Replaces the
	// old pattern of fetching the entire host list and computing counts in
	// the browser. $1 = stale threshold, $2 = down threshold (timestamps).
	GetHostCounts(ctx context.Context, arg GetHostCountsParams) (GetHostCountsRow, error)
	GetHostCountsForRepos(ctx context.Context, dollar_1 []string) ([]GetHostCountsForReposRow, error)
	GetHostDockerStats(ctx context.Context, hostID string) (GetHostDockerStatsRow, error)
	GetHostGroupByID(ctx context.Context, id string) (HostGroup, error)
	GetHostGroupMemberships(ctx context.Context, hostID string) ([]string, error)
	GetHostGroupsForHosts(ctx context.Context, dollar_1 []string) ([]GetHostGroupsForHostsRow, error)
	GetHostIDsByGroup(ctx context.Context, hostGroupID string) ([]string, error)
	GetHostIDsByGroupIDs(ctx context.Context, dollar_1 []string) ([]string, error)
	GetHostPackageStats(ctx context.Context, hostID string) (GetHostPackageStatsRow, error)
	GetHostPackageStatsByHostIDs(ctx context.Context, dollar_1 []string) ([]GetHostPackageStatsByHostIDsRow, error)
	GetHostPackagesForScopedApi(ctx context.Context, hostID string) ([]GetHostPackagesForScopedApiRow, error)
	// ListPackages and CountPackages are intentionally NOT defined here.
	// They live as raw SQL builders in internal/store/packages_list_sql.go.
	//
	// Why hand-rolled rather than sqlc:
	//   1. ORDER BY needs a CASE-WHEN-per-sort-key dance to stay parameterised,
	//      which forces a full sort over the entire filtered CTE before LIMIT
	//      can fire — defeats any index-ordered scan + LIMIT pushdown.
	//      Building "ORDER BY <whitelisted column> <dir>" in Go lets the
	//      planner drive output from the existing btree on packages(name)
	//      (and similar) for typical queries, killing the parallel-sort path
	//      that blows Docker's default /dev/shm.
	//   2. The host_packages EXISTS / NOT EXISTS branches are only relevant
	//      when the corresponding filter param is set; emitting them
	//      conditionally in Go produces a much tighter predicate that the
	//      planner can prune cheaply.
	// Per-package counters still come from mv_package_stats (refreshed every
	// ~2 min by an asynq scheduler — see TypePackageStatsRefresh) so we avoid
	// per-request aggregation over host_packages.
	// (Removed) GetHostPackageStatsByPackageIDs / GetUpdatesCountByPackageIDs /
	// GetSecurityCountByPackageIDs — superseded by mv_package_stats. The
	// per-package counters returned to the Packages list page now come from
	// ListPackages itself (which joins the matview), so the previous
	// per-id aggregate round-trips are no longer needed.
	GetHostPackagesWithHostsByPackageID(ctx context.Context, packageID string) ([]GetHostPackagesWithHostsByPackageIDRow, error)
	GetHostPackagesWithPackages(ctx context.Context, hostID string) ([]GetHostPackagesWithPackagesRow, error)
	GetHostRefsForPackageIDs(ctx context.Context, arg GetHostRefsForPackageIDsParams) ([]GetHostRefsForPackageIDsRow, error)
	GetHostRepositoriesByHostID(ctx context.Context, hostID string) ([]GetHostRepositoriesByHostIDRow, error)
	GetHostRepositoriesForRepo(ctx context.Context, repositoryID string) ([]GetHostRepositoriesForRepoRow, error)
	GetHostRepositoryCountByHostIDs(ctx context.Context, dollar_1 []string) ([]GetHostRepositoryCountByHostIDsRow, error)
	// Windows Update (WUA) specific queries
	// These operate on host_packages rows where category='Windows Update' and wua_guid IS NOT NULL
	// Returns all Windows Update entries for a host, most recently checked first.
	GetHostWindowsUpdates(ctx context.Context, hostID string) ([]GetHostWindowsUpdatesRow, error)
	GetHostsByIDs(ctx context.Context, dollar_1 []string) ([]Host, error)
	GetHostsForPackageTrends(ctx context.Context) ([]GetHostsForPackageTrendsRow, error)
	// Paginated host list for the Hosts UI. Filtering and ordering happen
	// over the full matching set, then LIMIT/OFFSET selects the current page.
	// That keeps header sorting correct across all hosts, not just the page
	// already loaded in the browser.
	GetHostsWithCounts(ctx context.Context, arg GetHostsWithCountsParams) ([]GetHostsWithCountsRow, error)
	// Fast path for host-column sorting: order/page hosts first, then aggregate
	// package counts only for the visible page. Package-count sorting uses
	// GetHostsWithCounts so the sort still applies across the full filtered set.
	GetHostsWithPageCounts(ctx context.Context, arg GetHostsWithPageCountsParams) ([]GetHostsWithPageCountsRow, error)
	// Images
	GetImageByID(ctx context.Context, id string) (DockerImage, error)
	GetImageIDByRepositoryTagImageID(ctx context.Context, arg GetImageIDByRepositoryTagImageIDParams) (string, error)
	GetImageUpdatesByImageID(ctx context.Context, imageID string) ([]DockerImageUpdate, error)
	GetImagesByIDs(ctx context.Context, dollar_1 []string) ([]DockerImage, error)
	GetImagesBySource(ctx context.Context) ([]GetImagesBySourceRow, error)
	GetLatestCompletedScans(ctx context.Context) ([]GetLatestCompletedScansRow, error)
	GetLatestCompletedScansByProfile(ctx context.Context, profileID string) ([]GetLatestCompletedScansByProfileRow, error)
	GetLatestComplianceScanByHost(ctx context.Context, hostID string) (GetLatestComplianceScanByHostRow, error)
	GetLatestComplianceScanByHostAndType(ctx context.Context, arg GetLatestComplianceScanByHostAndTypeParams) (GetLatestComplianceScanByHostAndTypeRow, error)
	GetLatestSystemStatistics(ctx context.Context) (GetLatestSystemStatisticsRow, error)
	GetNavigationStats(ctx context.Context) (GetNavigationStatsRow, error)
	// Networks
	GetNetworkByID(ctx context.Context, id string) (DockerNetwork, error)
	GetNetworksByHostID(ctx context.Context, hostID string) ([]DockerNetwork, error)
	GetNotificationDestinationByID(ctx context.Context, id string) (NotificationDestination, error)
	GetNotificationRouteByID(ctx context.Context, id string) (NotificationRoute, error)
	GetOSDistribution(ctx context.Context) ([]GetOSDistributionRow, error)
	GetOSDistributionByTypeAndVersion(ctx context.Context) ([]GetOSDistributionByTypeAndVersionRow, error)
	GetPackageByID(ctx context.Context, id string) (Package, error)
	GetPackageByName(ctx context.Context, name string) (Package, error)
	// Off-fast-path resolver for names BulkUpsertPackages could not return (see
	// the concurrency note there). Issued as its own statement so it reads at a
	// fresh snapshot and observes rows committed by concurrent reports. Takes no
	// row locks. The caller only runs this when a name is actually missing.
	//
	// REQUIRES READ COMMITTED. Only under READ COMMITTED does a new statement take
	// a new snapshot; at REPEATABLE READ or SERIALIZABLE this reuses the
	// transaction snapshot, resolves nothing, and the race it exists to close
	// silently returns. The pool sets no TxOptions, so the server default applies
	// — do not raise it without revisiting this.
	GetPackageIDsByNames(ctx context.Context, names []string) ([]GetPackageIDsByNamesRow, error)
	GetPatchPolicyAssignmentByID(ctx context.Context, id string) (PatchPolicyAssignment, error)
	GetPatchPolicyByGroupAssignment(ctx context.Context, targetID string) (PatchPolicy, error)
	GetPatchPolicyByID(ctx context.Context, id string) (PatchPolicy, error)
	GetPatchRunByID(ctx context.Context, id string) (GetPatchRunByIDRow, error)
	GetPatchRunByIDSimple(ctx context.Context, id string) (PatchRun, error)
	GetPendingConfig(ctx context.Context, hostID string) (HostPendingConfig, error)
	GetPendingUpdateCountsPerHost(ctx context.Context) ([]GetPendingUpdateCountsPerHostRow, error)
	// Returns WUA GUIDs that are still pending (needs_update=true, not yet installed) for a host.
	// Used by the server to tell the agent which updates to install.
	GetPendingWindowsUpdateGUIDs(ctx context.Context, hostID string) ([]*string, error)
	GetRecentComplianceScans(ctx context.Context) ([]GetRecentComplianceScansRow, error)
	GetRecentHosts(ctx context.Context, limit int32) ([]GetRecentHostsRow, error)
	GetRecentUsers(ctx context.Context, limit int32) ([]GetRecentUsersRow, error)
	GetRepoCountsForRepos(ctx context.Context, dollar_1 []string) ([]GetRepoCountsForReposRow, error)
	GetRepositoryByID(ctx context.Context, id string) (Repository, error)
	// Lock-free read on the (url, distribution, components) unique key. Serves
	// two purposes for the report path, both described on UpsertRepository:
	//   1. The pre-check that lets an unchanged report skip the upsert entirely,
	//      so it never takes the hot-row lock. Hence the projection is exactly
	//      the columns UpsertRepository's DO UPDATE would set.
	//   2. Resolving the id when that upsert skipped its no-op DO UPDATE and
	//      returned nothing. As a separate statement it reads at a fresh
	//      snapshot and sees rows committed by concurrent reports.
	//
	// Use (2) REQUIRES READ COMMITTED: only there does a new statement take a new
	// snapshot. At REPEATABLE READ or SERIALIZABLE it would reuse the transaction
	// snapshot and resolve nothing. The pool sets no TxOptions, so the server
	// default applies — do not raise it without revisiting this.
	GetRepositoryByURLDistComponents(ctx context.Context, arg GetRepositoryByURLDistComponentsParams) (GetRepositoryByURLDistComponentsRow, error)
	GetRepositoryForDelete(ctx context.Context, id string) (GetRepositoryForDeleteRow, error)
	GetRolePermissions(ctx context.Context, role string) (RolePermission, error)
	GetRuleAggregationsFromScans(ctx context.Context, arg GetRuleAggregationsFromScansParams) ([]GetRuleAggregationsFromScansRow, error)
	GetScheduledReportByID(ctx context.Context, id string) (ScheduledReport, error)
	GetSessionByID(ctx context.Context, arg GetSessionByIDParams) (UserSession, error)
	GetSessionByRefreshToken(ctx context.Context, refreshToken string) (UserSession, error)
	GetSourceReposByPackageIDs(ctx context.Context, arg GetSourceReposByPackageIDsParams) ([]GetSourceReposByPackageIDsRow, error)
	GetSystemStatisticsDaily(ctx context.Context, arg GetSystemStatisticsDailyParams) ([]GetSystemStatisticsDailyRow, error)
	GetSystemStatsForInsert(ctx context.Context) (GetSystemStatsForInsertRow, error)
	GetTopFailingRulesFromScans(ctx context.Context, dollar_1 []string) ([]GetTopFailingRulesFromScansRow, error)
	GetTopWarningRulesFromScans(ctx context.Context, dollar_1 []string) ([]GetTopWarningRulesFromScansRow, error)
	GetUpdateCountsByImageIDs(ctx context.Context, dollar_1 []string) ([]GetUpdateCountsByImageIDsRow, error)
	GetUpdateHistory(ctx context.Context, arg GetUpdateHistoryParams) ([]GetUpdateHistoryRow, error)
	GetUpdateHistoryDaily(ctx context.Context, arg GetUpdateHistoryDailyParams) ([]GetUpdateHistoryDailyRow, error)
	GetUpdateTrends(ctx context.Context, timestamp pgtype.Timestamp) ([]GetUpdateTrendsRow, error)
	GetUserByDiscordID(ctx context.Context, discordID *string) (User, error)
	GetUserByDiscordIDOrEmail(ctx context.Context, arg GetUserByDiscordIDOrEmailParams) (User, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserByOidcSub(ctx context.Context, oidcSub *string) (User, error)
	// The "$2 != ''" guard mirrors GetUserByDiscordIDOrEmail. Without it an IdP
	// asserting an empty email participates in the email branch, which is junk
	// input rather than a takeover (the oidc_sub cross-check blocks a second such
	// login) but should not reach account matching at all.
	GetUserByOidcSubOrEmail(ctx context.Context, arg GetUserByOidcSubOrEmailParams) (User, error)
	GetUserByUsername(ctx context.Context, lower string) (User, error)
	GetUserByUsernameOrEmail(ctx context.Context, lower string) (User, error)
	// Volumes
	GetVolumeByID(ctx context.Context, id string) (DockerVolume, error)
	GetVolumesByHostID(ctx context.Context, hostID string) ([]DockerVolume, error)
	GlobalSearch(ctx context.Context, search string) ([]GlobalSearchRow, error)
	HostInHostGroup(ctx context.Context, arg HostInHostGroupParams) (bool, error)
	IncrementAutoEnrollmentHostsCreated(ctx context.Context, id string) error
	InsertAlertHistory(ctx context.Context, arg InsertAlertHistoryParams) (AlertHistory, error)
	InsertDashboardPreference(ctx context.Context, arg InsertDashboardPreferenceParams) error
	// ON CONFLICT: callers may pass the same group id twice, and the delete has
	// already run by then.
	InsertHostGroupMembership(ctx context.Context, arg InsertHostGroupMembershipParams) error
	InsertHostRepository(ctx context.Context, arg InsertHostRepositoryParams) error
	InsertJobHistory(ctx context.Context, arg InsertJobHistoryParams) error
	InsertNotificationDeliveryLog(ctx context.Context, arg InsertNotificationDeliveryLogParams) (NotificationDeliveryLog, error)
	InsertReleaseNotesAcceptance(ctx context.Context, arg InsertReleaseNotesAcceptanceParams) (string, error)
	InsertScheduledReportRun(ctx context.Context, arg InsertScheduledReportRunParams) (ScheduledReportRun, error)
	InsertSystemStatistics(ctx context.Context, arg InsertSystemStatisticsParams) error
	// Persists a single agent activity row for the per-host Agent Activity feed.
	// report_type discriminates 'full' / 'partial' / 'ping' / 'docker' / 'compliance'.
	// sections_sent / sections_unchanged drive the "Updated / Skipped" chip pair in
	// the UI (legacy rows pre-000043 stay at the column defaults so the UI shows
	// "—" for them). agent_execution_ms is the agent-side data-collection time
	// shipped on the wire; nullable for older agents.
	InsertUpdateHistory(ctx context.Context, arg InsertUpdateHistoryParams) error
	ListActiveAlertsByType(ctx context.Context, type_ string) ([]ListActiveAlertsByTypeRow, error)
	ListActiveComplianceScans(ctx context.Context) ([]ListActiveComplianceScansRow, error)
	ListActivePatchRuns(ctx context.Context) ([]ListActivePatchRunsRow, error)
	ListActiveUsers(ctx context.Context) ([]User, error)
	ListAgentActivity(ctx context.Context, arg ListAgentActivityParams) ([]ListAgentActivityRow, error)
	ListAlertActions(ctx context.Context) ([]AlertAction, error)
	ListAlertConfig(ctx context.Context) ([]ListAlertConfigRow, error)
	ListAlertHistoryByAlertID(ctx context.Context, alertID string) ([]ListAlertHistoryByAlertIDRow, error)
	ListAutoEnrollmentTokens(ctx context.Context) ([]ListAutoEnrollmentTokensRow, error)
	ListComplianceProfiles(ctx context.Context) ([]ComplianceProfile, error)
	ListComplianceResultsByScan(ctx context.Context, arg ListComplianceResultsByScanParams) ([]ListComplianceResultsByScanRow, error)
	ListComplianceRulesByProfile(ctx context.Context, profileID string) ([]ComplianceRule, error)
	ListComplianceScansByHost(ctx context.Context, arg ListComplianceScansByHostParams) ([]ListComplianceScansByHostRow, error)
	ListComplianceScansHistory(ctx context.Context, arg ListComplianceScansHistoryParams) ([]ListComplianceScansHistoryRow, error)
	ListContainers(ctx context.Context, arg ListContainersParams) ([]DockerContainer, error)
	ListDashboardPreferencesByUserID(ctx context.Context, userID string) ([]DashboardPreference, error)
	ListDockerHostsPaginated(ctx context.Context, arg ListDockerHostsPaginatedParams) ([]ListDockerHostsPaginatedRow, error)
	ListExistingHostApiIDs(ctx context.Context, dollar_1 []string) ([]string, error)
	ListHostGroups(ctx context.Context) ([]HostGroup, error)
	ListHostGroupsWithHostCount(ctx context.Context) ([]ListHostGroupsWithHostCountRow, error)
	ListHostOptions(ctx context.Context, arg ListHostOptionsParams) ([]ListHostOptionsRow, error)
	ListHosts(ctx context.Context) ([]Host, error)
	ListHostsForComplianceDashboard(ctx context.Context) ([]ListHostsForComplianceDashboardRow, error)
	ListHostsForPackage(ctx context.Context, arg ListHostsForPackageParams) ([]ListHostsForPackageRow, error)
	ListHostsPaginated(ctx context.Context, arg ListHostsPaginatedParams) ([]ListHostsPaginatedRow, error)
	ListImages(ctx context.Context, arg ListImagesParams) ([]DockerImage, error)
	ListJobHistoryByApiID(ctx context.Context, arg ListJobHistoryByApiIDParams) ([]JobHistory, error)
	ListNeedingUpdates(ctx context.Context) ([]ListNeedingUpdatesRow, error)
	ListNetworks(ctx context.Context, arg ListNetworksParams) ([]DockerNetwork, error)
	ListNotificationDeliveryLog(ctx context.Context, arg ListNotificationDeliveryLogParams) ([]NotificationDeliveryLog, error)
	ListNotificationDestinations(ctx context.Context) ([]NotificationDestination, error)
	ListNotificationRoutes(ctx context.Context) ([]ListNotificationRoutesRow, error)
	ListNotificationRoutesForEvent(ctx context.Context, dollar_1 string) ([]ListNotificationRoutesForEventRow, error)
	ListOrphanedContainers(ctx context.Context) ([]ListOrphanedContainersRow, error)
	ListOrphanedImages(ctx context.Context) ([]ListOrphanedImagesRow, error)
	ListOrphanedPackages(ctx context.Context) ([]ListOrphanedPackagesRow, error)
	ListOrphanedRepositories(ctx context.Context) ([]ListOrphanedRepositoriesRow, error)
	// patch_policies
	ListPatchPolicies(ctx context.Context) ([]PatchPolicy, error)
	ListPatchPolicyAssignments(ctx context.Context, arg ListPatchPolicyAssignmentsParams) ([]PatchPolicyAssignment, error)
	ListPatchPolicyAssignmentsByPolicy(ctx context.Context, patchPolicyID string) ([]PatchPolicyAssignment, error)
	// patch_policy_exclusions
	ListPatchPolicyExclusions(ctx context.Context, patchPolicyID string) ([]ListPatchPolicyExclusionsRow, error)
	// The 'status' filter accepts an exact status value. The pseudo-value
	// 'active' matches any in-flight run (queued or running) so UI widgets
	// that aggregate those two states can link to a single filter.
	ListPatchRuns(ctx context.Context, arg ListPatchRunsParams) ([]ListPatchRunsRow, error)
	ListPatchRunsByPackage(ctx context.Context, arg ListPatchRunsByPackageParams) ([]ListPatchRunsByPackageRow, error)
	ListPatchRunsByStatus(ctx context.Context) ([]ListPatchRunsByStatusRow, error)
	ListPatchRunsOrderByCompletedAt(ctx context.Context, arg ListPatchRunsOrderByCompletedAtParams) ([]ListPatchRunsOrderByCompletedAtRow, error)
	ListPatchRunsOrderByCompletedAtAsc(ctx context.Context, arg ListPatchRunsOrderByCompletedAtAscParams) ([]ListPatchRunsOrderByCompletedAtAscRow, error)
	ListPatchRunsOrderByCreatedAtAsc(ctx context.Context, arg ListPatchRunsOrderByCreatedAtAscParams) ([]ListPatchRunsOrderByCreatedAtAscRow, error)
	ListPatchRunsOrderByStartedAt(ctx context.Context, arg ListPatchRunsOrderByStartedAtParams) ([]ListPatchRunsOrderByStartedAtRow, error)
	ListPatchRunsOrderByStartedAtAsc(ctx context.Context, arg ListPatchRunsOrderByStartedAtAscParams) ([]ListPatchRunsOrderByStartedAtAscRow, error)
	ListPatchRunsOrderByStatus(ctx context.Context, arg ListPatchRunsOrderByStatusParams) ([]ListPatchRunsOrderByStatusRow, error)
	ListPatchRunsOrderByStatusDesc(ctx context.Context, arg ListPatchRunsOrderByStatusDescParams) ([]ListPatchRunsOrderByStatusDescRow, error)
	ListRecentPatchRuns(ctx context.Context, limit int32) ([]ListRecentPatchRunsRow, error)
	ListRepositories(ctx context.Context, arg ListRepositoriesParams) ([]ListRepositoriesRow, error)
	ListRoles(ctx context.Context) ([]RolePermission, error)
	ListScheduledReports(ctx context.Context) ([]ScheduledReport, error)
	ListScheduledReportsDue(ctx context.Context, nextRunAt pgtype.Timestamp) ([]ScheduledReport, error)
	ListSessionsByUserID(ctx context.Context, userID string) ([]UserSession, error)
	ListStalledComplianceScans(ctx context.Context, startedAt pgtype.Timestamp) ([]ListStalledComplianceScansRow, error)
	ListStalledComplianceScansWithDetails(ctx context.Context, startedAt pgtype.Timestamp) ([]ListStalledComplianceScansWithDetailsRow, error)
	ListSystemStatisticsByDateRange(ctx context.Context, arg ListSystemStatisticsByDateRangeParams) ([]SystemStatistic, error)
	ListTrustedDevicesForUser(ctx context.Context, userID string) ([]UserTrustedDevice, error)
	ListUpdateHistoryByDateRange(ctx context.Context, arg ListUpdateHistoryByDateRangeParams) ([]ListUpdateHistoryByDateRangeRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListVolumes(ctx context.Context, arg ListVolumesParams) ([]DockerVolume, error)
	// User-initiated cancel from StopRun. Deliberately does NOT touch shell_output
	// so progress chunks the agent appended between our read and write are preserved.
	// Same status guard as UpdatePatchRunCancelled.
	MarkPatchRunCancelledByUser(ctx context.Context, arg MarkPatchRunCancelledByUserParams) (int64, error)
	MarkPatchRunsAgentDisconnected(ctx context.Context, arg MarkPatchRunsAgentDisconnectedParams) (int64, error)
	// Stall sweep. The predicate is deliberately "no activity since", NOT "started
	// before": every progress chunk the agent streams bumps updated_at (see
	// UpdatePatchRunProgress), so a long-but-healthy run (dist-upgrade on slow
	// disk routinely exceeds 30 minutes) keeps refreshing its own liveness while a
	// genuinely wedged run does not. Using elapsed-since-start here would mark
	// every long run timed_out while it was still working and discard the real
	// outcome the agent later reports.
	MarkPatchRunsTimedOut(ctx context.Context, arg MarkPatchRunsTimedOutParams) (int64, error)
	// Declared :execrows, not :exec, because the status guard IS the concurrency
	// control. Two approvals racing both pass the handler's Go-side status check;
	// only one of them updates a row here, and the loser must be told so rather
	// than going on to create a second patch run and enqueue a second task.
	MarkValidationApproved(ctx context.Context, arg MarkValidationApprovedParams) (int64, error)
	RevokeAllSessionsForUser(ctx context.Context, userID string) error
	RevokeAllSessionsForUserExcept(ctx context.Context, arg RevokeAllSessionsForUserExceptParams) error
	RevokeAllTrustedDevicesForUser(ctx context.Context, userID string) error
	RevokeSessionByID(ctx context.Context, arg RevokeSessionByIDParams) error
	RevokeTrustedDeviceByID(ctx context.Context, arg RevokeTrustedDeviceByIDParams) error
	SetHostAwaitingPostPatchReport(ctx context.Context, arg SetHostAwaitingPostPatchReportParams) error
	SetNewsletterSubscribed(ctx context.Context, id string) error
	SetPatchRunPolicySnapshot(ctx context.Context, arg SetPatchRunPolicySnapshotParams) error
	ToggleHostRepository(ctx context.Context, arg ToggleHostRepositoryParams) error
	TouchTrustedDeviceLastUsed(ctx context.Context, arg TouchTrustedDeviceLastUsedParams) error
	UpdateAlert(ctx context.Context, id string) error
	UpdateAlertAssignment(ctx context.Context, arg UpdateAlertAssignmentParams) error
	UpdateAlertResolved(ctx context.Context, arg UpdateAlertResolvedParams) error
	UpdateAlertUnassign(ctx context.Context, id string) error
	UpdateAlertUnresolve(ctx context.Context, id string) error
	UpdateAutoEnrollmentToken(ctx context.Context, arg UpdateAutoEnrollmentTokenParams) error
	UpdateAutoEnrollmentTokenLastUsedAt(ctx context.Context, id string) error
	UpdateComplianceRule(ctx context.Context, arg UpdateComplianceRuleParams) error
	UpdateHostApiCredentials(ctx context.Context, arg UpdateHostApiCredentialsParams) error
	UpdateHostAutoUpdate(ctx context.Context, arg UpdateHostAutoUpdateParams) error
	UpdateHostComplianceDefaultProfile(ctx context.Context, arg UpdateHostComplianceDefaultProfileParams) error
	UpdateHostComplianceEnabled(ctx context.Context, arg UpdateHostComplianceEnabledParams) error
	UpdateHostComplianceHash(ctx context.Context, arg UpdateHostComplianceHashParams) error
	UpdateHostComplianceMode(ctx context.Context, arg UpdateHostComplianceModeParams) error
	UpdateHostComplianceScannerStatus(ctx context.Context, arg UpdateHostComplianceScannerStatusParams) error
	UpdateHostComplianceScanners(ctx context.Context, arg UpdateHostComplianceScannersParams) error
	UpdateHostConnection(ctx context.Context, arg UpdateHostConnectionParams) error
	UpdateHostDockerEnabled(ctx context.Context, arg UpdateHostDockerEnabledParams) error
	UpdateHostDockerHash(ctx context.Context, arg UpdateHostDockerHashParams) error
	UpdateHostDownAlerts(ctx context.Context, arg UpdateHostDownAlertsParams) error
	UpdateHostFriendlyName(ctx context.Context, arg UpdateHostFriendlyNameParams) error
	// Host report/update flow (agent sends package and system info)
	UpdateHostFromReport(ctx context.Context, arg UpdateHostFromReportParams) error
	UpdateHostGroup(ctx context.Context, arg UpdateHostGroupParams) error
	// Ping-side write of volatile metrics. Every column is guarded so a ping that
	// omits a metric leaves the stored value intact.
	UpdateHostMetrics(ctx context.Context, arg UpdateHostMetricsParams) error
	UpdateHostNotes(ctx context.Context, arg UpdateHostNotesParams) error
	// Records the outcome of a Windows Update installation for a specific host+GUID combination.
	UpdateHostPackageWUAInstallResult(ctx context.Context, arg UpdateHostPackageWUAInstallResultParams) error
	UpdateHostPing(ctx context.Context, id string) error
	UpdateHostPrimaryInterface(ctx context.Context, arg UpdateHostPrimaryInterfaceParams) error
	UpdateHostRebootStatus(ctx context.Context, arg UpdateHostRebootStatusParams) error
	UpdateJobHistoryCompleted(ctx context.Context, jobID string) error
	UpdateJobHistoryDelayed(ctx context.Context, jobID string) error
	UpdateJobHistoryFailed(ctx context.Context, arg UpdateJobHistoryFailedParams) error
	UpdateLastLogin(ctx context.Context, arg UpdateLastLoginParams) error
	UpdateNotificationDestination(ctx context.Context, arg UpdateNotificationDestinationParams) (NotificationDestination, error)
	UpdateNotificationRoute(ctx context.Context, arg UpdateNotificationRouteParams) (NotificationRoute, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdatePatchPolicy(ctx context.Context, arg UpdatePatchPolicyParams) error
	// Terminal cancelled state set by the agent's late "cancelled" stage report.
	// Replaces shell_output with the full captured output so rollback/cleanup text is preserved.
	// :execrows so the handler can detect concurrent termination (rows=0) cleanly.
	// agent_disconnected and timed_out are intentionally NOT in the guard so a
	// recovering agent that posts a late "cancelled" can still unwedge the row.
	// 'cancelled' STAYS in the guard: a DB-first user cancel already owns the row,
	// and the fields-only UpdatePatchRunCancelledOutput below is the path that
	// lets the agent's authoritative output land on it without a status change.
	UpdatePatchRunCancelled(ctx context.Context, arg UpdatePatchRunCancelledParams) (int64, error)
	// Fields-only follow-up for the DB-first user-cancel path
	// (MarkPatchRunCancelledByUser sets status='cancelled' immediately, so the
	// agent's subsequent "cancelled" stage report is blocked by the status guard
	// on UpdatePatchRunCancelled). This id-scoped update writes ONLY the agent's
	// authoritative captured output; it never changes status, so a 'completed'
	// report can still not overwrite a cancelled run. error_message is preserved
	// when already set (the user-initiated reason is the more informative one)
	// and filled in from the agent only when the column is still NULL.
	UpdatePatchRunCancelledOutput(ctx context.Context, arg UpdatePatchRunCancelledOutputParams) (int64, error)
	// REPLACE (not append) - agent streams progress chunks then sends final full output.
	// agent_disconnected and timed_out are intentionally NOT in the guard: both are
	// server-side "we gave up waiting" markers, so a recovering agent posting a late
	// genuine "completed" must be able to unwedge the row and deliver the real output.
	UpdatePatchRunCompleted(ctx context.Context, arg UpdatePatchRunCompletedParams) error
	// REPLACE (not append) - agent streams progress chunks then sends final full output.
	// agent_disconnected and timed_out are intentionally NOT in the guard so a
	// recovering agent that posts a late "failed" can still unwedge the row.
	UpdatePatchRunFailed(ctx context.Context, arg UpdatePatchRunFailedParams) error
	UpdatePatchRunPackagesAffected(ctx context.Context, arg UpdatePatchRunPackagesAffectedParams) error
	UpdatePatchRunProgress(ctx context.Context, arg UpdatePatchRunProgressParams) error
	UpdatePatchRunScheduledAt(ctx context.Context, arg UpdatePatchRunScheduledAtParams) error
	// Clear dry-run output fields so real-run output starts fresh.
	// Status guard prevents an in-flight agent message from clobbering an
	// already-terminated run (cancelled/timed_out/etc.). agent_disconnected is
	// intentionally NOT in the guard so a recovering agent can unwedge the row.
	UpdatePatchRunStarted(ctx context.Context, id string) error
	UpdatePatchRunStatus(ctx context.Context, arg UpdatePatchRunStatusParams) error
	// Agent streams progress chunks during the run, then sends the final authoritative
	// output on the terminal stage; REPLACE (not append) so the final record is never
	// a duplicate of the streamed progress.
	UpdatePatchRunValidated(ctx context.Context, arg UpdatePatchRunValidatedParams) error
	UpdateRepository(ctx context.Context, arg UpdateRepositoryParams) error
	UpdateScheduledReport(ctx context.Context, arg UpdateScheduledReportParams) (ScheduledReport, error)
	UpdateScheduledReportRunTimes(ctx context.Context, arg UpdateScheduledReportRunTimesParams) error
	UpdateSessionActivity(ctx context.Context, id string) error
	UpdateSessionOnLogin(ctx context.Context, arg UpdateSessionOnLoginParams) error
	UpdateSettings(ctx context.Context, arg UpdateSettingsParams) error
	UpdateSettingsConfig(ctx context.Context, arg UpdateSettingsConfigParams) error
	UpdateStalledComplianceScans(ctx context.Context, arg UpdateStalledComplianceScansParams) error
	UpdateTfaBackupCodes(ctx context.Context, arg UpdateTfaBackupCodesParams) error
	UpdateTfaEnabled(ctx context.Context, arg UpdateTfaEnabledParams) error
	UpdateTfaSecret(ctx context.Context, arg UpdateTfaSecretParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserDiscordLink(ctx context.Context, arg UpdateUserDiscordLinkParams) error
	UpdateUserDiscordProfile(ctx context.Context, arg UpdateUserDiscordProfileParams) error
	UpdateUserDiscordUnlink(ctx context.Context, id string) error
	UpdateUserOidcLink(ctx context.Context, arg UpdateUserOidcLinkParams) error
	UpdateUserOidcProfile(ctx context.Context, arg UpdateUserOidcProfileParams) error
	UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) error
	UpsertAlertConfig(ctx context.Context, arg UpsertAlertConfigParams) (AlertConfig, error)
	// DO UPDATE rather than DO NOTHING so the row is always returned on conflict.
	// Deliberately does not touch type: an existing profile keeps the type it was
	// created with. Overwriting it flips which scanner toggle gates it in SubmitScan.
	UpsertComplianceProfile(ctx context.Context, arg UpsertComplianceProfileParams) (ComplianceProfile, error)
	// Metadata columns are COALESCE-guarded so a submission omitting a field does
	// not blank a stored value.
	//
	// title reads the raw parameter, not EXCLUDED: the column is NOT NULL so the
	// INSERT arm supplies a rule_ref fallback, which EXCLUDED would already hold.
	UpsertComplianceRule(ctx context.Context, arg UpsertComplianceRuleParams) (string, error)
	UpsertDashboardLayout(ctx context.Context, arg UpsertDashboardLayoutParams) error
	UpsertDockerContainer(ctx context.Context, arg UpsertDockerContainerParams) error
	UpsertDockerImage(ctx context.Context, arg UpsertDockerImageParams) (string, error)
	UpsertDockerImageUpdate(ctx context.Context, arg UpsertDockerImageUpdateParams) error
	UpsertDockerNetwork(ctx context.Context, arg UpsertDockerNetworkParams) error
	UpsertDockerVolume(ctx context.Context, arg UpsertDockerVolumeParams) error
	UpsertPendingConfig(ctx context.Context, arg UpsertPendingConfigParams) error
	// Replaces the previous GetRepositoryByURLDistComponents + InsertRepository
	// SELECT-then-INSERT pattern. Migration 000040 added a UNIQUE constraint on
	// (url, distribution, components), making this a true upsert and closing
	// the TOCTOU race where two concurrent host reports could both see "no row"
	// and both INSERT.
	//
	// DO UPDATE touches non-key columns only, so the row lock taken is FOR NO
	// KEY UPDATE — safe vs concurrent FK FOR KEY SHARE locks held by
	// host_packages inserts pointing at this row.
	//
	// Repository rows are shared across the whole fleet: every host on a distro
	// reports the same (url, distribution, components). Running this statement on
	// every report takes a FOR NO KEY UPDATE lock on ONE hot row and holds it
	// until the report transaction commits — which is after that transaction's
	// full host_packages delete and bulk insert. Contention scales with fleet
	// concurrency, not with the handful of repository rows per host, so at 64
	// concurrent reports they serialise behind the hot row until statement_timeout.
	//
	// The skip-no-op WHERE below does NOT prevent that lock. PostgreSQL's
	// ON CONFLICT arbiter locks the conflicting tuple BEFORE it evaluates the
	// DO UPDATE WHERE, so a skipped no-op still holds the row lock to end of
	// transaction (verified: holder reports INSERT 0 0 while a concurrent
	// FOR NO KEY UPDATE on the same row blocks). The WHERE earns its keep by
	// avoiding the heap write, dead tuple and WAL when two reports race on the
	// same genuine change — not by avoiding locks.
	//
	// Avoiding the lock is therefore the CALLER's job: upsertRepositoryResolvingID
	// reads the row first (a plain SELECT takes no lock) and only reaches this
	// statement when the row is absent or a column it would set actually differs.
	// Do not "simplify" the caller back to calling this unconditionally.
	//
	// Consequence of the WHERE: RETURNING is NOT always populated. A skipped
	// no-op returns zero rows and this is a :one query, so the caller gets
	// pgx.ErrNoRows and MUST resolve the id via GetRepositoryByURLDistComponents.
	// Do NOT "fix" this with a same-statement fallback SELECT — both halves would
	// read at the same statement snapshot and miss rows a concurrent transaction
	// committed after the statement began.
	UpsertRepository(ctx context.Context, arg UpsertRepositoryParams) (string, error)
	UpsertRolePermissions(ctx context.Context, arg UpsertRolePermissionsParams) (RolePermission, error)
}

var _ Querier = (*Queries)(nil)
