// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Bulk insert N host_packages rows in a single statement. Replaces the legacy
	// InsertHostPackage and InsertHostPackageWithWUA per-row inserts — one path
	// now covers Linux/FreeBSD (all wua_* columns NULL) and Windows (wua_* set).
	//
	// DeleteHostPackagesByHostID has already cleared this host's rows, so no
	// ON CONFLICT clause is needed: the (host_id, package_id) UNIQUE constraint
	// cannot fire.
	//
	// Caller pre-sorts by package_id (defensive — host_packages rows for one host
	// cannot cross-host-deadlock because of host-partitioning, but consistent
	// ordering is cheap insurance and aids index locality on (host_id, package_id)).
	//
	// Input shape: a single jsonb array of objects with one key per column.
	//
	// We use `jsonb_to_recordset` with a typed column list rather than
	// `jsonb_array_elements + elem->>'col'` per column. The recordset variant
	// parses each input element ONCE into a typed tuple; the array_elements
	// variant re-enters the JSON parser for each `->>` operator (15 columns ×
	// per-row = 15 lookups/row). Benchmarks at 10k packages show roughly a
	// 3x decode speedup, which matters for the report-heavy workload at 100+
	// hosts. JSON nulls become SQL NULLs directly so callers do not need
	// empty-string sentinels — but the Go side still emits empty strings for
	// text fields, which the NULLIF wrappers below collapse to NULL. Both
	// conventions remain valid; do not change one without the other.
	//
	// wua_categories is stored as jsonb and is declared as a jsonb column in
	// the recordset spec, so it round-trips as a real JSON value (array or
	// null) without going through text serialisation.
	BulkInsertHostPackages(ctx context.Context, payload []byte) error
	// Bulk upsert N packages in a single statement, eliminating per-row round-trips.
	//
	// Caller MUST pre-sort the input rows by name AND deduplicate by name
	// (deterministic lock acquisition; ON CONFLICT cannot affect the same row
	// twice in one statement — cardinality_violation 21000). The inner ORDER BY
	// name in the `input` CTE is belt-and-braces: PostgreSQL's executor processes
	// INSERT...SELECT tuples in plan order, and the explicit Sort node above
	// jsonb_to_recordset guarantees that order even if the planner introduces
	// parallel workers (unlikely at this row count). Both layers must remain —
	// do not strip the ORDER BY thinking the Go-side sort is sufficient. Sorted
	// lock acquisition prevents the cross-host 40P01 deadlocks reported in
	// production.
	//
	// Input shape: a single jsonb array of objects, each with keys
	//   { id, name, description, category, latest_version }
	// We use jsonb_to_recordset rather than parallel text[]+unnest because sqlc
	// v1.x's static analyzer cannot resolve the multi-array unnest() overload
	// ("function unnest(unknown, ...) does not exist"). jsonb_to_recordset gives
	// the same per-row shape with one well-typed parameter and zero overload
	// ambiguity.
	//
	// Description / category / latest_version are JSON nulls when the agent
	// omits them, which jsonb_to_recordset emits as SQL NULL directly.
	//
	// The DO UPDATE WHERE clause skips no-op updates: when the agent reports the
	// same description/category/latest_version that's already stored, no row
	// update happens, no dead tuple is created, and no FOR NO KEY UPDATE row
	// lock is taken. Steady-state production workloads with mostly-stable package
	// catalogues see ~95% of upsert calls become no-ops, drastically reducing
	// WAL volume, vacuum pressure, AND the lock-conflict surface that produced
	// the deadlocks.
	//
	// The UNION ALL fallback returns (id, name) for input rows that did NOT fire
	// DO UPDATE (i.e. the values are unchanged), so the caller's name → id map
	// is complete regardless of whether each row was newly inserted, updated, or
	// left unchanged. This is required: BulkInsertHostPackages depends on
	// knowing the package_id for every input package.
	//
	// The DO UPDATE intentionally touches only NON-KEY columns
	// (description / category / latest_version / updated_at). The row lock taken
	// by ON CONFLICT is therefore FOR NO KEY UPDATE, which does NOT conflict
	// with FOR KEY SHARE locks held by concurrent BulkInsertHostPackages FK
	// checks on the same packages.id rows. Do not extend this DO UPDATE to
	// touch id or name without re-evaluating the lock-compatibility analysis.
	// Fallback: input rows whose values matched the existing row exactly (so the
	// skip-no-op WHERE made the DO UPDATE a no-op and RETURNING omitted them).
	// Re-parsing the JSON here is cheap (kilobytes, in-memory) and avoids a
	// per-row round-trip — the alternative was a SELECT loop in Go.
	BulkUpsertPackages(ctx context.Context, payload []byte) ([]BulkUpsertPackagesRow, error)
	CancelStalledPatchRuns(ctx context.Context, arg CancelStalledPatchRunsParams) (int64, error)
	ClearScheduledAt(ctx context.Context, id string) error
	CountActiveAdmins(ctx context.Context) (int64, error)
	CountActiveRepositories(ctx context.Context) (int32, error)
	CountAdmins(ctx context.Context) (int64, error)
	CountComplianceResultsByScan(ctx context.Context, arg CountComplianceResultsByScanParams) (int64, error)
	CountComplianceScansByHost(ctx context.Context, hostID string) (int64, error)
	CountComplianceScansHistory(ctx context.Context, arg CountComplianceScansHistoryParams) (int64, error)
	CountContainers(ctx context.Context, arg CountContainersParams) (int32, error)
	CountContainersByImageID(ctx context.Context, imageID *string) (int32, error)
	// Dashboard stats
	CountDockerHosts(ctx context.Context) (int32, error)
	CountEnabledHostRepositories(ctx context.Context) (int32, error)
	CountHosts(ctx context.Context) (int64, error)
	CountHostsForPackage(ctx context.Context, arg CountHostsForPackageParams) (int32, error)
	CountImages(ctx context.Context, arg CountImagesParams) (int32, error)
	CountNetworks(ctx context.Context, arg CountNetworksParams) (int32, error)
	CountNetworksByHostID(ctx context.Context, hostID string) (int32, error)
	CountPackages(ctx context.Context, arg CountPackagesParams) (int32, error)
	CountPatchRuns(ctx context.Context, arg CountPatchRunsParams) (int64, error)
	CountPatchRunsTotal(ctx context.Context) (int64, error)
	CountRepositories(ctx context.Context) (int32, error)
	CountSecureRepositories(ctx context.Context) (int32, error)
	CountSuperadmins(ctx context.Context) (int64, error)
	CountTfaRememberSessionsByUser(ctx context.Context, userID string) (int64, error)
	CountUnscannedHosts(ctx context.Context) (int64, error)
	CountUpdateHistory(ctx context.Context, hostID string) (int32, error)
	CountUsers(ctx context.Context) (int64, error)
	CountUsersByRole(ctx context.Context, role string) (int64, error)
	CountVolumes(ctx context.Context, arg CountVolumesParams) (int32, error)
	CountVolumesByHostID(ctx context.Context, hostID string) (int32, error)
	// Counts pending Windows Updates for a host (for dashboard/stats).
	CountWindowsUpdatesByHostID(ctx context.Context, hostID string) (CountWindowsUpdatesByHostIDRow, error)
	CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error)
	CreateAutoEnrollmentToken(ctx context.Context, arg CreateAutoEnrollmentTokenParams) error
	CreateComplianceProfile(ctx context.Context, arg CreateComplianceProfileParams) (ComplianceProfile, error)
	CreateComplianceResult(ctx context.Context, arg CreateComplianceResultParams) (ComplianceResult, error)
	CreateComplianceRule(ctx context.Context, arg CreateComplianceRuleParams) (ComplianceRule, error)
	CreateComplianceScan(ctx context.Context, arg CreateComplianceScanParams) (ComplianceScan, error)
	CreateDiscordUser(ctx context.Context, arg CreateDiscordUserParams) error
	CreateHost(ctx context.Context, arg CreateHostParams) error
	CreateHostGroup(ctx context.Context, arg CreateHostGroupParams) error
	CreateNotificationDestination(ctx context.Context, arg CreateNotificationDestinationParams) (NotificationDestination, error)
	CreateNotificationRoute(ctx context.Context, arg CreateNotificationRouteParams) (NotificationRoute, error)
	CreateOidcUser(ctx context.Context, arg CreateOidcUserParams) error
	CreatePatchPolicy(ctx context.Context, arg CreatePatchPolicyParams) error
	CreatePatchPolicyAssignment(ctx context.Context, arg CreatePatchPolicyAssignmentParams) error
	CreatePatchPolicyExclusion(ctx context.Context, arg CreatePatchPolicyExclusionParams) error
	// patch_runs
	CreatePatchRun(ctx context.Context, arg CreatePatchRunParams) error
	CreateScheduledReport(ctx context.Context, arg CreateScheduledReportParams) (ScheduledReport, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateTrustedDevice(ctx context.Context, arg CreateTrustedDeviceParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteAlert(ctx context.Context, id string) error
	DeleteAlertsByIDs(ctx context.Context, dollar_1 []string) error
	DeleteAutoEnrollmentToken(ctx context.Context, id string) error
	DeleteComplianceResultsByScan(ctx context.Context, scanID string) error
	DeleteContainer(ctx context.Context, id string) error
	DeleteContainersByIDs(ctx context.Context, dollar_1 []string) error
	DeleteDashboardPreferencesByUserID(ctx context.Context, userID string) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteExpiredTrustedDevices(ctx context.Context) error
	DeleteHost(ctx context.Context, id string) error
	DeleteHostGroup(ctx context.Context, id string) error
	DeleteHostGroupMemberships(ctx context.Context, hostID string) error
	// Removes a host_package row that was reported as superseded by the agent.
	DeleteHostPackageByWUAGUID(ctx context.Context, arg DeleteHostPackageByWUAGUIDParams) error
	DeleteHostPackagesByHostID(ctx context.Context, hostID string) error
	// Bulk-removes superseded Windows Update entries for a host.
	DeleteHostPackagesByWUAGUIDs(ctx context.Context, arg DeleteHostPackagesByWUAGUIDsParams) error
	DeleteHostRepositoriesByHostID(ctx context.Context, hostID string) error
	DeleteHostsByIDs(ctx context.Context, dollar_1 []string) error
	DeleteImageByID(ctx context.Context, id string) error
	DeleteImageUpdatesByImageID(ctx context.Context, imageID string) error
	DeleteImagesByIDs(ctx context.Context, dollar_1 []string) error
	DeleteNetwork(ctx context.Context, id string) error
	DeleteNotificationDestination(ctx context.Context, id string) error
	DeleteNotificationRoute(ctx context.Context, id string) error
	DeleteOldestTfaRememberSession(ctx context.Context, userID string) error
	DeletePackagesByIDs(ctx context.Context, dollar_1 []string) error
	DeletePatchPolicy(ctx context.Context, id string) error
	DeletePatchPolicyAssignment(ctx context.Context, id string) error
	DeletePatchPolicyExclusion(ctx context.Context, arg DeletePatchPolicyExclusionParams) error
	DeletePatchRun(ctx context.Context, id string) error
	DeletePendingConfig(ctx context.Context, hostID string) error
	DeletePreviousCompletedScansByHostAndProfile(ctx context.Context, arg DeletePreviousCompletedScansByHostAndProfileParams) error
	DeleteRepositoriesByIDs(ctx context.Context, dollar_1 []string) error
	DeleteRepository(ctx context.Context, id string) error
	DeleteRolePermissions(ctx context.Context, role string) error
	DeleteRunningComplianceScansByHost(ctx context.Context, hostID string) error
	DeleteScheduledReport(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id string) error
	DeleteVolume(ctx context.Context, id string) error
	DisableTfa(ctx context.Context, id string) error
	ExistsByUsernameOrEmail(ctx context.Context, arg ExistsByUsernameOrEmailParams) (bool, error)
	ExistsPatchPolicyExclusion(ctx context.Context, arg ExistsPatchPolicyExclusionParams) (bool, error)
	FindSessionByUserAndDevice(ctx context.Context, arg FindSessionByUserAndDeviceParams) (UserSession, error)
	FindSessionByUserAndDeviceID(ctx context.Context, arg FindSessionByUserAndDeviceIDParams) (UserSession, error)
	FindSessionWithTfaBypass(ctx context.Context, arg FindSessionWithTfaBypassParams) (FindSessionWithTfaBypassRow, error)
	FindValidTrustedDevice(ctx context.Context, arg FindValidTrustedDeviceParams) (UserTrustedDevice, error)
	GetAcceptedVersionsByUserID(ctx context.Context, userID string) ([]string, error)
	GetAlertActionByName(ctx context.Context, name string) (AlertAction, error)
	GetAlertByID(ctx context.Context, id string) (GetAlertByIDRow, error)
	GetAlertConfigByType(ctx context.Context, alertType string) (GetAlertConfigByTypeRow, error)
	GetAlertStatsBySeverity(ctx context.Context) ([]GetAlertStatsBySeverityRow, error)
	GetAlertsForCleanup(ctx context.Context, arg GetAlertsForCleanupParams) ([]GetAlertsForCleanupRow, error)
	GetAlertsToAutoResolve(ctx context.Context, arg GetAlertsToAutoResolveParams) ([]GetAlertsToAutoResolveRow, error)
	GetAutoEnrollmentTokenByID(ctx context.Context, id string) (GetAutoEnrollmentTokenByIDRow, error)
	GetAutoEnrollmentTokenByKey(ctx context.Context, tokenKey string) (AutoEnrollmentToken, error)
	GetAutoEnrollmentTokenRaw(ctx context.Context, id string) (AutoEnrollmentToken, error)
	GetCategories(ctx context.Context) ([]*string, error)
	GetComplianceProfileByID(ctx context.Context, id string) (ComplianceProfile, error)
	GetComplianceProfileByName(ctx context.Context, name string) (ComplianceProfile, error)
	GetComplianceResultSeverityBreakdown(ctx context.Context, scanID string) ([]GetComplianceResultSeverityBreakdownRow, error)
	GetComplianceResultSeverityBreakdownForScans(ctx context.Context, dollar_1 []string) ([]GetComplianceResultSeverityBreakdownForScansRow, error)
	GetComplianceResultStatusBreakdown(ctx context.Context, scanID string) ([]GetComplianceResultStatusBreakdownRow, error)
	GetComplianceResultsForRuleFromScans(ctx context.Context, arg GetComplianceResultsForRuleFromScansParams) ([]GetComplianceResultsForRuleFromScansRow, error)
	GetComplianceRuleByID(ctx context.Context, id string) (GetComplianceRuleByIDRow, error)
	GetComplianceRuleByProfileAndRef(ctx context.Context, arg GetComplianceRuleByProfileAndRefParams) (ComplianceRule, error)
	GetComplianceScanByID(ctx context.Context, id string) (GetComplianceScanByIDRow, error)
	GetComplianceScansForTrends(ctx context.Context, arg GetComplianceScansForTrendsParams) ([]GetComplianceScansForTrendsRow, error)
	// Containers
	GetContainerByID(ctx context.Context, id string) (DockerContainer, error)
	GetContainerCountsByImageIDs(ctx context.Context, dollar_1 []string) ([]GetContainerCountsByImageIDsRow, error)
	GetContainersByHostID(ctx context.Context, hostID string) ([]DockerContainer, error)
	GetContainersByImageID(ctx context.Context, arg GetContainersByImageIDParams) ([]DockerContainer, error)
	GetContainersByImageIDAll(ctx context.Context, imageID *string) ([]DockerContainer, error)
	GetContainersByStatus(ctx context.Context) ([]GetContainersByStatusRow, error)
	GetDashboardLayout(ctx context.Context, userID string) (DashboardLayout, error)
	GetDashboardStats(ctx context.Context, arg GetDashboardStatsParams) (GetDashboardStatsRow, error)
	// patch_policy_assignments
	GetDirectPatchPolicyAssignment(ctx context.Context, targetID string) (PatchPolicy, error)
	// Hosts (include hosts with containers, volumes, or networks)
	GetDistinctDockerHostIDs(ctx context.Context) ([]string, error)
	GetDockerDashboardStats(ctx context.Context) (GetDockerDashboardStatsRow, error)
	GetDockerHostsByIDs(ctx context.Context, dollar_1 []string) ([]GetDockerHostsByIDsRow, error)
	GetDockerHostsMinimalByIDs(ctx context.Context, dollar_1 []string) ([]GetDockerHostsMinimalByIDsRow, error)
	GetFirstComplianceProfileByType(ctx context.Context, type_ string) (ComplianceProfile, error)
	GetFirstSettings(ctx context.Context) (Setting, error)
	GetHomepageStats(ctx context.Context, since pgtype.Timestamp) (GetHomepageStatsRow, error)
	GetHostByApiID(ctx context.Context, apiID string) (Host, error)
	GetHostByID(ctx context.Context, id string) (Host, error)
	GetHostCountsForRepos(ctx context.Context, dollar_1 []string) ([]GetHostCountsForReposRow, error)
	GetHostDockerStats(ctx context.Context, hostID string) (GetHostDockerStatsRow, error)
	GetHostGroupByID(ctx context.Context, id string) (HostGroup, error)
	GetHostGroupMemberships(ctx context.Context, hostID string) ([]string, error)
	GetHostGroupsForHosts(ctx context.Context, dollar_1 []string) ([]GetHostGroupsForHostsRow, error)
	GetHostIDsByGroup(ctx context.Context, hostGroupID string) ([]string, error)
	GetHostIDsByGroupIDs(ctx context.Context, dollar_1 []string) ([]string, error)
	GetHostPackageStats(ctx context.Context, hostID string) (GetHostPackageStatsRow, error)
	GetHostPackageStatsByHostIDs(ctx context.Context, dollar_1 []string) ([]GetHostPackageStatsByHostIDsRow, error)
	GetHostPackageStatsByPackageIDs(ctx context.Context, arg GetHostPackageStatsByPackageIDsParams) ([]GetHostPackageStatsByPackageIDsRow, error)
	GetHostPackagesForScopedApi(ctx context.Context, hostID string) ([]GetHostPackagesForScopedApiRow, error)
	GetHostPackagesWithHostsByPackageID(ctx context.Context, packageID string) ([]GetHostPackagesWithHostsByPackageIDRow, error)
	GetHostPackagesWithPackages(ctx context.Context, hostID string) ([]GetHostPackagesWithPackagesRow, error)
	GetHostRefsForPackageIDs(ctx context.Context, arg GetHostRefsForPackageIDsParams) ([]GetHostRefsForPackageIDsRow, error)
	GetHostRepositoriesByHostID(ctx context.Context, hostID string) ([]GetHostRepositoriesByHostIDRow, error)
	GetHostRepositoriesForRepo(ctx context.Context, repositoryID string) ([]GetHostRepositoriesForRepoRow, error)
	GetHostRepositoryCountByHostIDs(ctx context.Context, dollar_1 []string) ([]GetHostRepositoryCountByHostIDsRow, error)
	// Windows Update (WUA) specific queries
	// These operate on host_packages rows where category='Windows Update' and wua_guid IS NOT NULL
	// Returns all Windows Update entries for a host, most recently checked first.
	GetHostWindowsUpdates(ctx context.Context, hostID string) ([]GetHostWindowsUpdatesRow, error)
	GetHostsByIDs(ctx context.Context, dollar_1 []string) ([]Host, error)
	GetHostsForPackageTrends(ctx context.Context) ([]GetHostsForPackageTrendsRow, error)
	GetHostsWithCounts(ctx context.Context, arg GetHostsWithCountsParams) ([]GetHostsWithCountsRow, error)
	// Images
	GetImageByID(ctx context.Context, id string) (DockerImage, error)
	GetImageIDByRepositoryTagImageID(ctx context.Context, arg GetImageIDByRepositoryTagImageIDParams) (string, error)
	GetImageUpdatesByImageID(ctx context.Context, imageID string) ([]DockerImageUpdate, error)
	GetImagesByIDs(ctx context.Context, dollar_1 []string) ([]DockerImage, error)
	GetImagesBySource(ctx context.Context) ([]GetImagesBySourceRow, error)
	GetLatestAlertHistoryForAlerts(ctx context.Context, dollar_1 []string) ([]GetLatestAlertHistoryForAlertsRow, error)
	GetLatestCompletedScans(ctx context.Context) ([]GetLatestCompletedScansRow, error)
	GetLatestCompletedScansByProfile(ctx context.Context, profileID string) ([]GetLatestCompletedScansByProfileRow, error)
	GetLatestComplianceScanByHost(ctx context.Context, hostID string) (GetLatestComplianceScanByHostRow, error)
	GetLatestComplianceScanByHostAndType(ctx context.Context, arg GetLatestComplianceScanByHostAndTypeParams) (GetLatestComplianceScanByHostAndTypeRow, error)
	GetLatestSystemStatistics(ctx context.Context) (GetLatestSystemStatisticsRow, error)
	// Networks
	GetNetworkByID(ctx context.Context, id string) (DockerNetwork, error)
	GetNetworksByHostID(ctx context.Context, hostID string) ([]DockerNetwork, error)
	GetNotificationDestinationByID(ctx context.Context, id string) (NotificationDestination, error)
	GetNotificationRouteByID(ctx context.Context, id string) (NotificationRoute, error)
	GetOSDistribution(ctx context.Context) ([]GetOSDistributionRow, error)
	GetOSDistributionByTypeAndVersion(ctx context.Context) ([]GetOSDistributionByTypeAndVersionRow, error)
	GetPackageByID(ctx context.Context, id string) (Package, error)
	GetPackageByName(ctx context.Context, name string) (Package, error)
	GetPatchPolicyAssignmentByID(ctx context.Context, id string) (PatchPolicyAssignment, error)
	GetPatchPolicyByGroupAssignment(ctx context.Context, targetID string) (PatchPolicy, error)
	GetPatchPolicyByID(ctx context.Context, id string) (PatchPolicy, error)
	GetPatchRunByID(ctx context.Context, id string) (GetPatchRunByIDRow, error)
	GetPatchRunByIDSimple(ctx context.Context, id string) (PatchRun, error)
	GetPendingConfig(ctx context.Context, hostID string) (HostPendingConfig, error)
	GetPendingUpdateCountsPerHost(ctx context.Context) ([]GetPendingUpdateCountsPerHostRow, error)
	// Returns WUA GUIDs that are still pending (needs_update=true, not yet installed) for a host.
	// Used by the server to tell the agent which updates to install.
	GetPendingWindowsUpdateGUIDs(ctx context.Context, hostID string) ([]*string, error)
	GetRecentComplianceScans(ctx context.Context) ([]GetRecentComplianceScansRow, error)
	GetRecentHosts(ctx context.Context, limit int32) ([]GetRecentHostsRow, error)
	GetRecentUsers(ctx context.Context, limit int32) ([]GetRecentUsersRow, error)
	GetRepositoryByID(ctx context.Context, id string) (Repository, error)
	GetRepositoryForDelete(ctx context.Context, id string) (GetRepositoryForDeleteRow, error)
	GetRolePermissions(ctx context.Context, role string) (RolePermission, error)
	GetRuleAggregationsFromScans(ctx context.Context, arg GetRuleAggregationsFromScansParams) ([]GetRuleAggregationsFromScansRow, error)
	GetScheduledReportByID(ctx context.Context, id string) (ScheduledReport, error)
	GetSecurityCountByPackageIDs(ctx context.Context, arg GetSecurityCountByPackageIDsParams) ([]GetSecurityCountByPackageIDsRow, error)
	GetSessionByID(ctx context.Context, arg GetSessionByIDParams) (UserSession, error)
	GetSessionByRefreshToken(ctx context.Context, refreshToken string) (UserSession, error)
	GetSourceReposByPackageIDs(ctx context.Context, arg GetSourceReposByPackageIDsParams) ([]GetSourceReposByPackageIDsRow, error)
	GetSystemStatisticsDaily(ctx context.Context, arg GetSystemStatisticsDailyParams) ([]GetSystemStatisticsDailyRow, error)
	GetSystemStatsForInsert(ctx context.Context) (GetSystemStatsForInsertRow, error)
	GetTopFailingRulesFromScans(ctx context.Context, dollar_1 []string) ([]GetTopFailingRulesFromScansRow, error)
	GetTopWarningRulesFromScans(ctx context.Context, dollar_1 []string) ([]GetTopWarningRulesFromScansRow, error)
	GetUpdateCountsByImageIDs(ctx context.Context, dollar_1 []string) ([]GetUpdateCountsByImageIDsRow, error)
	GetUpdateHistory(ctx context.Context, arg GetUpdateHistoryParams) ([]UpdateHistory, error)
	GetUpdateHistoryDaily(ctx context.Context, arg GetUpdateHistoryDailyParams) ([]GetUpdateHistoryDailyRow, error)
	GetUpdateTrends(ctx context.Context, timestamp pgtype.Timestamp) ([]GetUpdateTrendsRow, error)
	GetUpdatesCountByPackageIDs(ctx context.Context, arg GetUpdatesCountByPackageIDsParams) ([]GetUpdatesCountByPackageIDsRow, error)
	GetUserByDiscordID(ctx context.Context, discordID *string) (User, error)
	GetUserByDiscordIDOrEmail(ctx context.Context, arg GetUserByDiscordIDOrEmailParams) (User, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserByOidcSub(ctx context.Context, oidcSub *string) (User, error)
	GetUserByOidcSubOrEmail(ctx context.Context, arg GetUserByOidcSubOrEmailParams) (User, error)
	GetUserByUsername(ctx context.Context, lower string) (User, error)
	GetUserByUsernameOrEmail(ctx context.Context, lower string) (User, error)
	// Volumes
	GetVolumeByID(ctx context.Context, id string) (DockerVolume, error)
	GetVolumesByHostID(ctx context.Context, hostID string) ([]DockerVolume, error)
	GlobalSearch(ctx context.Context, search string) ([]GlobalSearchRow, error)
	HostInHostGroup(ctx context.Context, arg HostInHostGroupParams) (bool, error)
	IncrementAutoEnrollmentHostsCreated(ctx context.Context, id string) error
	InsertAlertHistory(ctx context.Context, arg InsertAlertHistoryParams) (AlertHistory, error)
	InsertDashboardPreference(ctx context.Context, arg InsertDashboardPreferenceParams) error
	InsertHostGroupMembership(ctx context.Context, arg InsertHostGroupMembershipParams) error
	InsertHostRepository(ctx context.Context, arg InsertHostRepositoryParams) error
	InsertJobHistory(ctx context.Context, arg InsertJobHistoryParams) error
	InsertNotificationDeliveryLog(ctx context.Context, arg InsertNotificationDeliveryLogParams) (NotificationDeliveryLog, error)
	InsertReleaseNotesAcceptance(ctx context.Context, arg InsertReleaseNotesAcceptanceParams) (string, error)
	InsertScheduledReportRun(ctx context.Context, arg InsertScheduledReportRunParams) (ScheduledReportRun, error)
	InsertSystemStatistics(ctx context.Context, arg InsertSystemStatisticsParams) error
	InsertUpdateHistory(ctx context.Context, arg InsertUpdateHistoryParams) error
	ListActiveAlertsByType(ctx context.Context, type_ string) ([]ListActiveAlertsByTypeRow, error)
	ListActiveComplianceScans(ctx context.Context) ([]ListActiveComplianceScansRow, error)
	ListActivePatchRuns(ctx context.Context) ([]ListActivePatchRunsRow, error)
	ListActiveUsers(ctx context.Context) ([]User, error)
	ListAlertActions(ctx context.Context) ([]AlertAction, error)
	ListAlertConfig(ctx context.Context) ([]ListAlertConfigRow, error)
	ListAlertHistoryByAlertID(ctx context.Context, alertID string) ([]ListAlertHistoryByAlertIDRow, error)
	ListAlerts(ctx context.Context) ([]ListAlertsRow, error)
	ListAlertsAssignedTo(ctx context.Context, assignedToUserID *string) ([]ListAlertsAssignedToRow, error)
	ListAutoEnrollmentTokens(ctx context.Context) ([]ListAutoEnrollmentTokensRow, error)
	ListComplianceProfiles(ctx context.Context) ([]ComplianceProfile, error)
	ListComplianceResultsByScan(ctx context.Context, arg ListComplianceResultsByScanParams) ([]ListComplianceResultsByScanRow, error)
	ListComplianceRulesByProfile(ctx context.Context, profileID string) ([]ComplianceRule, error)
	ListComplianceScansByHost(ctx context.Context, arg ListComplianceScansByHostParams) ([]ListComplianceScansByHostRow, error)
	ListComplianceScansHistory(ctx context.Context, arg ListComplianceScansHistoryParams) ([]ListComplianceScansHistoryRow, error)
	ListContainers(ctx context.Context, arg ListContainersParams) ([]DockerContainer, error)
	ListDashboardPreferencesByUserID(ctx context.Context, userID string) ([]DashboardPreference, error)
	ListDockerHostsPaginated(ctx context.Context, arg ListDockerHostsPaginatedParams) ([]ListDockerHostsPaginatedRow, error)
	ListHostGroups(ctx context.Context) ([]HostGroup, error)
	ListHostGroupsWithHostCount(ctx context.Context) ([]ListHostGroupsWithHostCountRow, error)
	ListHosts(ctx context.Context) ([]Host, error)
	ListHostsForComplianceDashboard(ctx context.Context) ([]ListHostsForComplianceDashboardRow, error)
	ListHostsForPackage(ctx context.Context, arg ListHostsForPackageParams) ([]ListHostsForPackageRow, error)
	ListHostsPaginated(ctx context.Context, arg ListHostsPaginatedParams) ([]ListHostsPaginatedRow, error)
	ListImages(ctx context.Context, arg ListImagesParams) ([]DockerImage, error)
	ListJobHistoryByApiID(ctx context.Context, arg ListJobHistoryByApiIDParams) ([]JobHistory, error)
	ListNeedingUpdates(ctx context.Context) ([]ListNeedingUpdatesRow, error)
	ListNetworks(ctx context.Context, arg ListNetworksParams) ([]DockerNetwork, error)
	ListNotificationDeliveryLog(ctx context.Context, arg ListNotificationDeliveryLogParams) ([]NotificationDeliveryLog, error)
	ListNotificationDestinations(ctx context.Context) ([]NotificationDestination, error)
	ListNotificationRoutes(ctx context.Context) ([]ListNotificationRoutesRow, error)
	ListNotificationRoutesForEvent(ctx context.Context, dollar_1 string) ([]ListNotificationRoutesForEventRow, error)
	ListOrphanedContainers(ctx context.Context) ([]ListOrphanedContainersRow, error)
	ListOrphanedImages(ctx context.Context) ([]ListOrphanedImagesRow, error)
	ListOrphanedPackages(ctx context.Context) ([]ListOrphanedPackagesRow, error)
	ListOrphanedRepositories(ctx context.Context) ([]ListOrphanedRepositoriesRow, error)
	ListPackages(ctx context.Context, arg ListPackagesParams) ([]ListPackagesRow, error)
	// patch_policies
	ListPatchPolicies(ctx context.Context) ([]PatchPolicy, error)
	ListPatchPolicyAssignments(ctx context.Context, arg ListPatchPolicyAssignmentsParams) ([]PatchPolicyAssignment, error)
	ListPatchPolicyAssignmentsByPolicy(ctx context.Context, patchPolicyID string) ([]PatchPolicyAssignment, error)
	// patch_policy_exclusions
	ListPatchPolicyExclusions(ctx context.Context, patchPolicyID string) ([]ListPatchPolicyExclusionsRow, error)
	// The 'status' filter accepts an exact status value. The pseudo-value
	// 'active' matches any in-flight run (queued or running) so UI widgets
	// that aggregate those two states can link to a single filter.
	ListPatchRuns(ctx context.Context, arg ListPatchRunsParams) ([]ListPatchRunsRow, error)
	ListPatchRunsByPackage(ctx context.Context, arg ListPatchRunsByPackageParams) ([]ListPatchRunsByPackageRow, error)
	ListPatchRunsByStatus(ctx context.Context) ([]ListPatchRunsByStatusRow, error)
	ListPatchRunsOrderByCompletedAt(ctx context.Context, arg ListPatchRunsOrderByCompletedAtParams) ([]ListPatchRunsOrderByCompletedAtRow, error)
	ListPatchRunsOrderByCompletedAtAsc(ctx context.Context, arg ListPatchRunsOrderByCompletedAtAscParams) ([]ListPatchRunsOrderByCompletedAtAscRow, error)
	ListPatchRunsOrderByCreatedAtAsc(ctx context.Context, arg ListPatchRunsOrderByCreatedAtAscParams) ([]ListPatchRunsOrderByCreatedAtAscRow, error)
	ListPatchRunsOrderByStartedAt(ctx context.Context, arg ListPatchRunsOrderByStartedAtParams) ([]ListPatchRunsOrderByStartedAtRow, error)
	ListPatchRunsOrderByStartedAtAsc(ctx context.Context, arg ListPatchRunsOrderByStartedAtAscParams) ([]ListPatchRunsOrderByStartedAtAscRow, error)
	ListPatchRunsOrderByStatus(ctx context.Context, arg ListPatchRunsOrderByStatusParams) ([]ListPatchRunsOrderByStatusRow, error)
	ListPatchRunsOrderByStatusDesc(ctx context.Context, arg ListPatchRunsOrderByStatusDescParams) ([]ListPatchRunsOrderByStatusDescRow, error)
	ListRecentPatchRuns(ctx context.Context, limit int32) ([]ListRecentPatchRunsRow, error)
	ListRepositories(ctx context.Context, arg ListRepositoriesParams) ([]Repository, error)
	ListRoles(ctx context.Context) ([]RolePermission, error)
	ListScheduledReports(ctx context.Context) ([]ScheduledReport, error)
	ListScheduledReportsDue(ctx context.Context, nextRunAt pgtype.Timestamp) ([]ScheduledReport, error)
	ListSessionsByUserID(ctx context.Context, userID string) ([]UserSession, error)
	ListStalledComplianceScans(ctx context.Context, startedAt pgtype.Timestamp) ([]ListStalledComplianceScansRow, error)
	ListStalledComplianceScansWithDetails(ctx context.Context, startedAt pgtype.Timestamp) ([]ListStalledComplianceScansWithDetailsRow, error)
	ListSystemStatisticsByDateRange(ctx context.Context, arg ListSystemStatisticsByDateRangeParams) ([]SystemStatistic, error)
	ListTrustedDevicesForUser(ctx context.Context, userID string) ([]UserTrustedDevice, error)
	ListUpdateHistoryByDateRange(ctx context.Context, arg ListUpdateHistoryByDateRangeParams) ([]UpdateHistory, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListVolumes(ctx context.Context, arg ListVolumesParams) ([]DockerVolume, error)
	MarkValidationApproved(ctx context.Context, arg MarkValidationApprovedParams) error
	RevokeAllSessionsForUser(ctx context.Context, userID string) error
	RevokeAllSessionsForUserExcept(ctx context.Context, arg RevokeAllSessionsForUserExceptParams) error
	RevokeAllTrustedDevicesForUser(ctx context.Context, userID string) error
	RevokeSessionByID(ctx context.Context, arg RevokeSessionByIDParams) error
	RevokeTrustedDeviceByID(ctx context.Context, arg RevokeTrustedDeviceByIDParams) error
	SetHostAwaitingPostPatchReport(ctx context.Context, arg SetHostAwaitingPostPatchReportParams) error
	SetNewsletterSubscribed(ctx context.Context, id string) error
	SetPatchRunPolicySnapshot(ctx context.Context, arg SetPatchRunPolicySnapshotParams) error
	ToggleHostRepository(ctx context.Context, arg ToggleHostRepositoryParams) error
	TouchTrustedDeviceLastUsed(ctx context.Context, arg TouchTrustedDeviceLastUsedParams) error
	UpdateAlert(ctx context.Context, id string) error
	UpdateAlertAssignment(ctx context.Context, arg UpdateAlertAssignmentParams) error
	UpdateAlertResolved(ctx context.Context, arg UpdateAlertResolvedParams) error
	UpdateAlertUnassign(ctx context.Context, id string) error
	UpdateAlertUnresolve(ctx context.Context, id string) error
	UpdateAutoEnrollmentToken(ctx context.Context, arg UpdateAutoEnrollmentTokenParams) error
	UpdateAutoEnrollmentTokenLastUsedAt(ctx context.Context, id string) error
	UpdateComplianceRule(ctx context.Context, arg UpdateComplianceRuleParams) error
	UpdateHostApiCredentials(ctx context.Context, arg UpdateHostApiCredentialsParams) error
	UpdateHostAutoUpdate(ctx context.Context, arg UpdateHostAutoUpdateParams) error
	UpdateHostComplianceDefaultProfile(ctx context.Context, arg UpdateHostComplianceDefaultProfileParams) error
	UpdateHostComplianceEnabled(ctx context.Context, arg UpdateHostComplianceEnabledParams) error
	UpdateHostComplianceMode(ctx context.Context, arg UpdateHostComplianceModeParams) error
	UpdateHostComplianceScannerStatus(ctx context.Context, arg UpdateHostComplianceScannerStatusParams) error
	UpdateHostComplianceScanners(ctx context.Context, arg UpdateHostComplianceScannersParams) error
	UpdateHostConnection(ctx context.Context, arg UpdateHostConnectionParams) error
	UpdateHostDockerEnabled(ctx context.Context, arg UpdateHostDockerEnabledParams) error
	UpdateHostDownAlerts(ctx context.Context, arg UpdateHostDownAlertsParams) error
	UpdateHostFriendlyName(ctx context.Context, arg UpdateHostFriendlyNameParams) error
	// Host report/update flow (agent sends package and system info)
	UpdateHostFromReport(ctx context.Context, arg UpdateHostFromReportParams) error
	UpdateHostGroup(ctx context.Context, arg UpdateHostGroupParams) error
	UpdateHostNotes(ctx context.Context, arg UpdateHostNotesParams) error
	// Records the outcome of a Windows Update installation for a specific host+GUID combination.
	UpdateHostPackageWUAInstallResult(ctx context.Context, arg UpdateHostPackageWUAInstallResultParams) error
	UpdateHostPing(ctx context.Context, id string) error
	UpdateHostPrimaryInterface(ctx context.Context, arg UpdateHostPrimaryInterfaceParams) error
	UpdateHostRebootStatus(ctx context.Context, arg UpdateHostRebootStatusParams) error
	UpdateJobHistoryCompleted(ctx context.Context, jobID string) error
	UpdateJobHistoryDelayed(ctx context.Context, jobID string) error
	UpdateJobHistoryFailed(ctx context.Context, arg UpdateJobHistoryFailedParams) error
	UpdateNotificationDestination(ctx context.Context, arg UpdateNotificationDestinationParams) (NotificationDestination, error)
	UpdateNotificationRoute(ctx context.Context, arg UpdateNotificationRouteParams) (NotificationRoute, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdatePatchPolicy(ctx context.Context, arg UpdatePatchPolicyParams) error
	// Terminal cancelled state when a running patch is stopped via patch_run_stop.
	// Replaces shell_output with the full captured output so rollback/cleanup text is preserved.
	UpdatePatchRunCancelled(ctx context.Context, arg UpdatePatchRunCancelledParams) error
	// REPLACE (not append) - agent streams progress chunks then sends final full output.
	UpdatePatchRunCompleted(ctx context.Context, arg UpdatePatchRunCompletedParams) error
	// REPLACE (not append) - agent streams progress chunks then sends final full output.
	UpdatePatchRunFailed(ctx context.Context, arg UpdatePatchRunFailedParams) error
	UpdatePatchRunPackagesAffected(ctx context.Context, arg UpdatePatchRunPackagesAffectedParams) error
	UpdatePatchRunProgress(ctx context.Context, arg UpdatePatchRunProgressParams) error
	UpdatePatchRunScheduledAt(ctx context.Context, arg UpdatePatchRunScheduledAtParams) error
	// Clear dry-run output fields so real-run output starts fresh.
	UpdatePatchRunStarted(ctx context.Context, id string) error
	UpdatePatchRunStatus(ctx context.Context, arg UpdatePatchRunStatusParams) error
	// Agent streams progress chunks during the run, then sends the final authoritative
	// output on the terminal stage; REPLACE (not append) so the final record is never
	// a duplicate of the streamed progress.
	UpdatePatchRunValidated(ctx context.Context, arg UpdatePatchRunValidatedParams) error
	UpdateRepository(ctx context.Context, arg UpdateRepositoryParams) error
	UpdateScheduledReport(ctx context.Context, arg UpdateScheduledReportParams) (ScheduledReport, error)
	UpdateScheduledReportRunTimes(ctx context.Context, arg UpdateScheduledReportRunTimesParams) error
	UpdateSessionActivity(ctx context.Context, id string) error
	UpdateSessionOnLogin(ctx context.Context, arg UpdateSessionOnLoginParams) error
	UpdateSettings(ctx context.Context, arg UpdateSettingsParams) error
	UpdateSettingsConfig(ctx context.Context, arg UpdateSettingsConfigParams) error
	UpdateStalledComplianceScans(ctx context.Context, arg UpdateStalledComplianceScansParams) error
	UpdateTfaBackupCodes(ctx context.Context, arg UpdateTfaBackupCodesParams) error
	UpdateTfaEnabled(ctx context.Context, arg UpdateTfaEnabledParams) error
	UpdateTfaSecret(ctx context.Context, arg UpdateTfaSecretParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserDiscordLink(ctx context.Context, arg UpdateUserDiscordLinkParams) error
	UpdateUserDiscordProfile(ctx context.Context, arg UpdateUserDiscordProfileParams) error
	UpdateUserDiscordUnlink(ctx context.Context, id string) error
	UpdateUserOidcLink(ctx context.Context, arg UpdateUserOidcLinkParams) error
	UpdateUserOidcProfile(ctx context.Context, arg UpdateUserOidcProfileParams) error
	UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) error
	UpsertAlertConfig(ctx context.Context, arg UpsertAlertConfigParams) (AlertConfig, error)
	UpsertDashboardLayout(ctx context.Context, arg UpsertDashboardLayoutParams) error
	UpsertDockerContainer(ctx context.Context, arg UpsertDockerContainerParams) error
	UpsertDockerImage(ctx context.Context, arg UpsertDockerImageParams) (string, error)
	UpsertDockerImageUpdate(ctx context.Context, arg UpsertDockerImageUpdateParams) error
	UpsertDockerNetwork(ctx context.Context, arg UpsertDockerNetworkParams) error
	UpsertDockerVolume(ctx context.Context, arg UpsertDockerVolumeParams) error
	UpsertPendingConfig(ctx context.Context, arg UpsertPendingConfigParams) error
	// Replaces the previous GetRepositoryByURLDistComponents + InsertRepository
	// SELECT-then-INSERT pattern. Migration 000040 added a UNIQUE constraint on
	// (url, distribution, components), making this a true upsert and closing
	// the TOCTOU race where two concurrent host reports could both see "no row"
	// and both INSERT.
	//
	// DO UPDATE touches non-key columns only, so the row lock taken is FOR NO
	// KEY UPDATE — safe vs concurrent FK FOR KEY SHARE locks held by
	// host_packages inserts pointing at this row.
	//
	// Returns the canonical id whether the row was newly inserted, updated, or
	// (in the no-op case where every column matches) updated to identical
	// values. There is no skip-no-op WHERE here because reports rarely repeat
	// identical repository metadata across runs and the row count per host is
	// small (typically 1-10) — the WAL/lock cost of unconditional UPDATE is
	// negligible compared with packages, and avoiding the WHERE keeps RETURNING
	// always-populated for a simpler caller contract.
	UpsertRepository(ctx context.Context, arg UpsertRepositoryParams) (string, error)
	UpsertRolePermissions(ctx context.Context, arg UpsertRolePermissionsParams) (RolePermission, error)
	// User API tokens (long-lived bearer tokens for automation)
	ListUserApiTokens(ctx context.Context, userID string) ([]ListUserApiTokensRow, error)
	GetUserApiTokenByHash(ctx context.Context, tokenHash string) (GetUserApiTokenByHashRow, error)
	CreateUserApiToken(ctx context.Context, arg CreateUserApiTokenParams) (ListUserApiTokensRow, error)
	DeleteUserApiToken(ctx context.Context, id string) error
	UpdateUserApiTokenLastUsed(ctx context.Context, id string) error
}

var _ Querier = (*Queries)(nil)
