// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repositories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveRepositories = `-- name: CountActiveRepositories :one
SELECT COUNT(*)::int FROM repositories WHERE is_active = true
`

func (q *Queries) CountActiveRepositories(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveRepositories)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countEnabledHostRepositories = `-- name: CountEnabledHostRepositories :one
SELECT COUNT(*)::int FROM host_repositories WHERE is_enabled = true
`

func (q *Queries) CountEnabledHostRepositories(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countEnabledHostRepositories)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countRepositories = `-- name: CountRepositories :one
SELECT COUNT(*)::int FROM repositories
`

func (q *Queries) CountRepositories(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countRepositories)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countRepositoriesForList = `-- name: CountRepositoriesForList :one
SELECT COUNT(*)::int
FROM repositories r
WHERE ($1::text IS NULL OR EXISTS (SELECT 1 FROM host_repositories hr WHERE hr.repository_id = r.id AND hr.host_id = $1))
AND ($2::text IS NULL OR r.name ILIKE '%' || $2 || '%' OR r.url ILIKE '%' || $2 || '%' OR r.distribution ILIKE '%' || $2 || '%' OR COALESCE(r.description, '') ILIKE '%' || $2 || '%')
AND ($3::text IS NULL OR ($3 = 'active' AND r.is_active = true) OR ($3 = 'inactive' AND r.is_active = false))
AND ($4::text IS NULL OR ($4 = 'secure' AND r.is_secure = true) OR ($4 = 'insecure' AND r.is_secure = false))
`

type CountRepositoriesForListParams struct {
	HostID *string `json:"host_id"`
	Search *string `json:"search"`
	Status *string `json:"status"`
	Type   *string `json:"type"`
}

func (q *Queries) CountRepositoriesForList(ctx context.Context, arg CountRepositoriesForListParams) (int32, error) {
	row := q.db.QueryRow(ctx, countRepositoriesForList,
		arg.HostID,
		arg.Search,
		arg.Status,
		arg.Type,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countSecureRepositories = `-- name: CountSecureRepositories :one
SELECT COUNT(*)::int FROM repositories WHERE is_secure = true
`

func (q *Queries) CountSecureRepositories(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countSecureRepositories)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteHostRepositoriesByHostID = `-- name: DeleteHostRepositoriesByHostID :exec
DELETE FROM host_repositories WHERE host_id = $1
`

func (q *Queries) DeleteHostRepositoriesByHostID(ctx context.Context, hostID string) error {
	_, err := q.db.Exec(ctx, deleteHostRepositoriesByHostID, hostID)
	return err
}

const deleteRepositoriesByIDs = `-- name: DeleteRepositoriesByIDs :exec
DELETE FROM repositories WHERE id = ANY($1::text[])
`

func (q *Queries) DeleteRepositoriesByIDs(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteRepositoriesByIDs, dollar_1)
	return err
}

const deleteRepository = `-- name: DeleteRepository :exec
DELETE FROM repositories WHERE id = $1
`

func (q *Queries) DeleteRepository(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteRepository, id)
	return err
}

const getHostCountsForRepos = `-- name: GetHostCountsForRepos :many
SELECT hr.repository_id, h.id, h.friendly_name, h.status, hr.is_enabled, hr.last_checked
FROM host_repositories hr
JOIN hosts h ON h.id = hr.host_id
WHERE hr.repository_id = ANY($1::text[])
ORDER BY hr.repository_id, h.friendly_name
`

type GetHostCountsForReposRow struct {
	RepositoryID string           `json:"repository_id"`
	ID           string           `json:"id"`
	FriendlyName string           `json:"friendly_name"`
	Status       string           `json:"status"`
	IsEnabled    bool             `json:"is_enabled"`
	LastChecked  pgtype.Timestamp `json:"last_checked"`
}

func (q *Queries) GetHostCountsForRepos(ctx context.Context, dollar_1 []string) ([]GetHostCountsForReposRow, error) {
	rows, err := q.db.Query(ctx, getHostCountsForRepos, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHostCountsForReposRow
	for rows.Next() {
		var i GetHostCountsForReposRow
		if err := rows.Scan(
			&i.RepositoryID,
			&i.ID,
			&i.FriendlyName,
			&i.Status,
			&i.IsEnabled,
			&i.LastChecked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHostRepositoriesByHostID = `-- name: GetHostRepositoriesByHostID :many
SELECT hr.id, hr.host_id, hr.repository_id, hr.is_enabled, hr.last_checked,
    r.id as repo_id, r.name as repo_name, r.url as repo_url,
    r.distribution as repo_distribution, r.components as repo_components,
    r.repo_type as repo_repo_type, r.is_active as repo_is_active,
    r.is_secure as repo_is_secure, r.priority as repo_priority,
    r.description as repo_description, r.created_at as repo_created_at,
    r.updated_at as repo_updated_at,
    h.id as host_id2, h.friendly_name as host_friendly_name
FROM host_repositories hr
JOIN repositories r ON r.id = hr.repository_id
JOIN hosts h ON h.id = hr.host_id
WHERE hr.host_id = $1
ORDER BY r.name ASC
`

type GetHostRepositoriesByHostIDRow struct {
	ID               string           `json:"id"`
	HostID           string           `json:"host_id"`
	RepositoryID     string           `json:"repository_id"`
	IsEnabled        bool             `json:"is_enabled"`
	LastChecked      pgtype.Timestamp `json:"last_checked"`
	RepoID           string           `json:"repo_id"`
	RepoName         string           `json:"repo_name"`
	RepoUrl          string           `json:"repo_url"`
	RepoDistribution string           `json:"repo_distribution"`
	RepoComponents   string           `json:"repo_components"`
	RepoRepoType     string           `json:"repo_repo_type"`
	RepoIsActive     bool             `json:"repo_is_active"`
	RepoIsSecure     bool             `json:"repo_is_secure"`
	RepoPriority     *int32           `json:"repo_priority"`
	RepoDescription  *string          `json:"repo_description"`
	RepoCreatedAt    pgtype.Timestamp `json:"repo_created_at"`
	RepoUpdatedAt    pgtype.Timestamp `json:"repo_updated_at"`
	HostId2          string           `json:"host_id2"`
	HostFriendlyName string           `json:"host_friendly_name"`
}

func (q *Queries) GetHostRepositoriesByHostID(ctx context.Context, hostID string) ([]GetHostRepositoriesByHostIDRow, error) {
	rows, err := q.db.Query(ctx, getHostRepositoriesByHostID, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHostRepositoriesByHostIDRow
	for rows.Next() {
		var i GetHostRepositoriesByHostIDRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.RepositoryID,
			&i.IsEnabled,
			&i.LastChecked,
			&i.RepoID,
			&i.RepoName,
			&i.RepoUrl,
			&i.RepoDistribution,
			&i.RepoComponents,
			&i.RepoRepoType,
			&i.RepoIsActive,
			&i.RepoIsSecure,
			&i.RepoPriority,
			&i.RepoDescription,
			&i.RepoCreatedAt,
			&i.RepoUpdatedAt,
			&i.HostId2,
			&i.HostFriendlyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHostRepositoriesForRepo = `-- name: GetHostRepositoriesForRepo :many
SELECT hr.id, hr.host_id, hr.repository_id, hr.is_enabled, hr.last_checked,
    h.id as host_id2, h.friendly_name as host_friendly_name, h.hostname as host_hostname,
    h.ip as host_ip, h.os_type as host_os_type, h.os_version as host_os_version,
    h.status as host_status, h.last_update as host_last_update, h.needs_reboot as host_needs_reboot
FROM host_repositories hr
JOIN hosts h ON h.id = hr.host_id
WHERE hr.repository_id = $1
ORDER BY h.friendly_name ASC
`

type GetHostRepositoriesForRepoRow struct {
	ID               string           `json:"id"`
	HostID           string           `json:"host_id"`
	RepositoryID     string           `json:"repository_id"`
	IsEnabled        bool             `json:"is_enabled"`
	LastChecked      pgtype.Timestamp `json:"last_checked"`
	HostId2          string           `json:"host_id2"`
	HostFriendlyName string           `json:"host_friendly_name"`
	HostHostname     *string          `json:"host_hostname"`
	HostIp           *string          `json:"host_ip"`
	HostOsType       string           `json:"host_os_type"`
	HostOsVersion    string           `json:"host_os_version"`
	HostStatus       string           `json:"host_status"`
	HostLastUpdate   pgtype.Timestamp `json:"host_last_update"`
	HostNeedsReboot  *bool            `json:"host_needs_reboot"`
}

func (q *Queries) GetHostRepositoriesForRepo(ctx context.Context, repositoryID string) ([]GetHostRepositoriesForRepoRow, error) {
	rows, err := q.db.Query(ctx, getHostRepositoriesForRepo, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHostRepositoriesForRepoRow
	for rows.Next() {
		var i GetHostRepositoriesForRepoRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.RepositoryID,
			&i.IsEnabled,
			&i.LastChecked,
			&i.HostId2,
			&i.HostFriendlyName,
			&i.HostHostname,
			&i.HostIp,
			&i.HostOsType,
			&i.HostOsVersion,
			&i.HostStatus,
			&i.HostLastUpdate,
			&i.HostNeedsReboot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHostRepositoryCountByHostIDs = `-- name: GetHostRepositoryCountByHostIDs :many
SELECT host_id, COUNT(*)::int AS cnt
FROM host_repositories
WHERE host_id = ANY($1::text[])
GROUP BY host_id
`

type GetHostRepositoryCountByHostIDsRow struct {
	HostID string `json:"host_id"`
	Cnt    int32  `json:"cnt"`
}

func (q *Queries) GetHostRepositoryCountByHostIDs(ctx context.Context, dollar_1 []string) ([]GetHostRepositoryCountByHostIDsRow, error) {
	rows, err := q.db.Query(ctx, getHostRepositoryCountByHostIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHostRepositoryCountByHostIDsRow
	for rows.Next() {
		var i GetHostRepositoryCountByHostIDsRow
		if err := rows.Scan(&i.HostID, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRepoCountsForRepos = `-- name: GetRepoCountsForRepos :many
SELECT hr.repository_id,
    COUNT(*)::int AS host_count,
    COUNT(*) FILTER (WHERE hr.is_enabled)::int AS enabled_host_count,
    COUNT(*) FILTER (WHERE h.status = 'active')::int AS active_host_count
FROM host_repositories hr
JOIN hosts h ON h.id = hr.host_id
WHERE hr.repository_id = ANY($1::text[])
GROUP BY hr.repository_id
`

type GetRepoCountsForReposRow struct {
	RepositoryID     string `json:"repository_id"`
	HostCount        int32  `json:"host_count"`
	EnabledHostCount int32  `json:"enabled_host_count"`
	ActiveHostCount  int32  `json:"active_host_count"`
}

func (q *Queries) GetRepoCountsForRepos(ctx context.Context, dollar_1 []string) ([]GetRepoCountsForReposRow, error) {
	rows, err := q.db.Query(ctx, getRepoCountsForRepos, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRepoCountsForReposRow
	for rows.Next() {
		var i GetRepoCountsForReposRow
		if err := rows.Scan(
			&i.RepositoryID,
			&i.HostCount,
			&i.EnabledHostCount,
			&i.ActiveHostCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRepositoryByID = `-- name: GetRepositoryByID :one
SELECT id, name, url, distribution, components, repo_type, is_active, is_secure, priority, description, created_at, updated_at FROM repositories WHERE id = $1
`

func (q *Queries) GetRepositoryByID(ctx context.Context, id string) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepositoryByID, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Distribution,
		&i.Components,
		&i.RepoType,
		&i.IsActive,
		&i.IsSecure,
		&i.Priority,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepositoryByURLDistComponents = `-- name: GetRepositoryByURLDistComponents :one
SELECT id, name, repo_type, is_active, is_secure, priority, description
FROM repositories
WHERE url = $1 AND distribution = $2 AND components = $3
`

type GetRepositoryByURLDistComponentsParams struct {
	Url          string `json:"url"`
	Distribution string `json:"distribution"`
	Components   string `json:"components"`
}

type GetRepositoryByURLDistComponentsRow struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	RepoType    string  `json:"repo_type"`
	IsActive    bool    `json:"is_active"`
	IsSecure    bool    `json:"is_secure"`
	Priority    *int32  `json:"priority"`
	Description *string `json:"description"`
}

// Lock-free read on the (url, distribution, components) unique key. Serves
// two purposes for the report path, both described on UpsertRepository:
//  1. The pre-check that lets an unchanged report skip the upsert entirely,
//     so it never takes the hot-row lock. Hence the projection is exactly
//     the columns UpsertRepository's DO UPDATE would set.
//  2. Resolving the id when that upsert skipped its no-op DO UPDATE and
//     returned nothing. As a separate statement it reads at a fresh
//     snapshot and sees rows committed by concurrent reports.
//
// Use (2) REQUIRES READ COMMITTED: only there does a new statement take a new
// snapshot. At REPEATABLE READ or SERIALIZABLE it would reuse the transaction
// snapshot and resolve nothing. The pool sets no TxOptions, so the server
// default applies — do not raise it without revisiting this.
func (q *Queries) GetRepositoryByURLDistComponents(ctx context.Context, arg GetRepositoryByURLDistComponentsParams) (GetRepositoryByURLDistComponentsRow, error) {
	row := q.db.QueryRow(ctx, getRepositoryByURLDistComponents, arg.Url, arg.Distribution, arg.Components)
	var i GetRepositoryByURLDistComponentsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepoType,
		&i.IsActive,
		&i.IsSecure,
		&i.Priority,
		&i.Description,
	)
	return i, err
}

const getRepositoryForDelete = `-- name: GetRepositoryForDelete :one
SELECT r.id, r.name, r.url, COUNT(hr.id)::int as count
FROM repositories r
LEFT JOIN host_repositories hr ON hr.repository_id = r.id
WHERE r.id = $1
GROUP BY r.id, r.name, r.url
`

type GetRepositoryForDeleteRow struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Url   string `json:"url"`
	Count int32  `json:"count"`
}

func (q *Queries) GetRepositoryForDelete(ctx context.Context, id string) (GetRepositoryForDeleteRow, error) {
	row := q.db.QueryRow(ctx, getRepositoryForDelete, id)
	var i GetRepositoryForDeleteRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Count,
	)
	return i, err
}

const insertHostRepository = `-- name: InsertHostRepository :exec
INSERT INTO host_repositories (id, host_id, repository_id, is_enabled, last_checked)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (host_id, repository_id) DO UPDATE SET is_enabled = EXCLUDED.is_enabled, last_checked = NOW()
`

type InsertHostRepositoryParams struct {
	ID           string `json:"id"`
	HostID       string `json:"host_id"`
	RepositoryID string `json:"repository_id"`
	IsEnabled    bool   `json:"is_enabled"`
}

func (q *Queries) InsertHostRepository(ctx context.Context, arg InsertHostRepositoryParams) error {
	_, err := q.db.Exec(ctx, insertHostRepository,
		arg.ID,
		arg.HostID,
		arg.RepositoryID,
		arg.IsEnabled,
	)
	return err
}

const listOrphanedRepositories = `-- name: ListOrphanedRepositories :many
SELECT id, name, url FROM repositories r
WHERE NOT EXISTS (SELECT 1 FROM host_repositories hr WHERE hr.repository_id = r.id)
`

type ListOrphanedRepositoriesRow struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Url  string `json:"url"`
}

func (q *Queries) ListOrphanedRepositories(ctx context.Context) ([]ListOrphanedRepositoriesRow, error) {
	rows, err := q.db.Query(ctx, listOrphanedRepositories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrphanedRepositoriesRow
	for rows.Next() {
		var i ListOrphanedRepositoriesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositories = `-- name: ListRepositories :many
WITH filtered_repositories AS (
    SELECT r.id, r.name, r.url, r.distribution, r.components, r.repo_type, r.is_active, r.is_secure, r.priority, r.description, r.created_at, r.updated_at
    FROM repositories r
    WHERE ($5::text IS NULL OR EXISTS (SELECT 1 FROM host_repositories hr WHERE hr.repository_id = r.id AND hr.host_id = $5))
    AND ($6::text IS NULL OR r.name ILIKE '%' || $6 || '%' OR r.url ILIKE '%' || $6 || '%' OR r.distribution ILIKE '%' || $6 || '%' OR COALESCE(r.description, '') ILIKE '%' || $6 || '%')
    AND ($7::text IS NULL OR ($7 = 'active' AND r.is_active = true) OR ($7 = 'inactive' AND r.is_active = false))
    AND ($8::text IS NULL OR ($8 = 'secure' AND r.is_secure = true) OR ($8 = 'insecure' AND r.is_secure = false))
),
repo_counts AS (
    SELECT hr.repository_id, COUNT(*)::int AS host_count
    FROM host_repositories hr
    JOIN filtered_repositories fr ON fr.id = hr.repository_id
    GROUP BY hr.repository_id
),
enriched_repositories AS (
    SELECT fr.id, fr.name, fr.url, fr.distribution, fr.components, fr.repo_type, fr.is_active, fr.is_secure, fr.priority, fr.description, fr.created_at, fr.updated_at, COALESCE(rc.host_count, 0)::int AS host_count
    FROM filtered_repositories fr
    LEFT JOIN repo_counts rc ON rc.repository_id = fr.id
)
SELECT id, name, url, distribution, components, repo_type, is_active, is_secure, priority, description, created_at, updated_at
FROM enriched_repositories
ORDER BY
    CASE WHEN $1::text = 'name'         AND $2::text = 'asc'  THEN name END ASC,
    CASE WHEN $1::text = 'name'         AND $2::text = 'desc' THEN name END DESC,
    CASE WHEN $1::text = 'url'          AND $2::text = 'asc'  THEN url END ASC,
    CASE WHEN $1::text = 'url'          AND $2::text = 'desc' THEN url END DESC,
    CASE WHEN $1::text = 'distribution' AND $2::text = 'asc'  THEN distribution END ASC,
    CASE WHEN $1::text = 'distribution' AND $2::text = 'desc' THEN distribution END DESC,
    CASE WHEN $1::text = 'security'     AND $2::text = 'asc'  THEN is_secure END ASC,
    CASE WHEN $1::text = 'security'     AND $2::text = 'desc' THEN is_secure END DESC,
    CASE WHEN $1::text = 'status'       AND $2::text = 'asc'  THEN is_active END DESC,
    CASE WHEN $1::text = 'status'       AND $2::text = 'desc' THEN is_active END ASC,
    CASE WHEN $1::text = 'hostCount'    AND $2::text = 'asc'  THEN host_count END ASC,
    CASE WHEN $1::text = 'hostCount'    AND $2::text = 'desc' THEN host_count END DESC,
    name ASC,
    url ASC,
    id ASC
LIMIT $4::int
OFFSET $3::int
`

type ListRepositoriesParams struct {
	SortKey   string  `json:"sort_key"`
	SortDir   string  `json:"sort_dir"`
	RowOffset int32   `json:"row_offset"`
	RowLimit  int32   `json:"row_limit"`
	HostID    *string `json:"host_id"`
	Search    *string `json:"search"`
	Status    *string `json:"status"`
	Type      *string `json:"type"`
}

type ListRepositoriesRow struct {
	ID           string           `json:"id"`
	Name         string           `json:"name"`
	Url          string           `json:"url"`
	Distribution string           `json:"distribution"`
	Components   string           `json:"components"`
	RepoType     string           `json:"repo_type"`
	IsActive     bool             `json:"is_active"`
	IsSecure     bool             `json:"is_secure"`
	Priority     *int32           `json:"priority"`
	Description  *string          `json:"description"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListRepositories(ctx context.Context, arg ListRepositoriesParams) ([]ListRepositoriesRow, error) {
	rows, err := q.db.Query(ctx, listRepositories,
		arg.SortKey,
		arg.SortDir,
		arg.RowOffset,
		arg.RowLimit,
		arg.HostID,
		arg.Search,
		arg.Status,
		arg.Type,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRepositoriesRow
	for rows.Next() {
		var i ListRepositoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Distribution,
			&i.Components,
			&i.RepoType,
			&i.IsActive,
			&i.IsSecure,
			&i.Priority,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleHostRepository = `-- name: ToggleHostRepository :exec
UPDATE host_repositories SET is_enabled = $1, last_checked = NOW() WHERE host_id = $2 AND repository_id = $3
`

type ToggleHostRepositoryParams struct {
	IsEnabled    bool   `json:"is_enabled"`
	HostID       string `json:"host_id"`
	RepositoryID string `json:"repository_id"`
}

func (q *Queries) ToggleHostRepository(ctx context.Context, arg ToggleHostRepositoryParams) error {
	_, err := q.db.Exec(ctx, toggleHostRepository, arg.IsEnabled, arg.HostID, arg.RepositoryID)
	return err
}

const updateRepository = `-- name: UpdateRepository :exec
UPDATE repositories SET
    name = $1,
    description = $2,
    is_active = $3,
    priority = $4,
    updated_at = NOW()
WHERE id = $5
`

type UpdateRepositoryParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	IsActive    bool    `json:"is_active"`
	Priority    *int32  `json:"priority"`
	ID          string  `json:"id"`
}

func (q *Queries) UpdateRepository(ctx context.Context, arg UpdateRepositoryParams) error {
	_, err := q.db.Exec(ctx, updateRepository,
		arg.Name,
		arg.Description,
		arg.IsActive,
		arg.Priority,
		arg.ID,
	)
	return err
}

const upsertRepository = `-- name: UpsertRepository :one
INSERT INTO repositories (id, name, url, distribution, components, repo_type, is_active, is_secure, priority, description, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW(), NOW())
ON CONFLICT (url, distribution, components) DO UPDATE SET
    name        = EXCLUDED.name,
    repo_type   = EXCLUDED.repo_type,
    is_active   = EXCLUDED.is_active,
    is_secure   = EXCLUDED.is_secure,
    priority    = EXCLUDED.priority,
    description = COALESCE(EXCLUDED.description, repositories.description),
    updated_at  = NOW()
WHERE
       repositories.name        IS DISTINCT FROM EXCLUDED.name
    OR repositories.repo_type   IS DISTINCT FROM EXCLUDED.repo_type
    OR repositories.is_active   IS DISTINCT FROM EXCLUDED.is_active
    OR repositories.is_secure   IS DISTINCT FROM EXCLUDED.is_secure
    OR repositories.priority    IS DISTINCT FROM EXCLUDED.priority
    OR repositories.description IS DISTINCT FROM COALESCE(EXCLUDED.description, repositories.description)
RETURNING id
`

type UpsertRepositoryParams struct {
	ID           string  `json:"id"`
	Name         string  `json:"name"`
	Url          string  `json:"url"`
	Distribution string  `json:"distribution"`
	Components   string  `json:"components"`
	RepoType     string  `json:"repo_type"`
	IsActive     bool    `json:"is_active"`
	IsSecure     bool    `json:"is_secure"`
	Priority     *int32  `json:"priority"`
	Description  *string `json:"description"`
}

// Replaces the previous GetRepositoryByURLDistComponents + InsertRepository
// SELECT-then-INSERT pattern. Migration 000040 added a UNIQUE constraint on
// (url, distribution, components), making this a true upsert and closing
// the TOCTOU race where two concurrent host reports could both see "no row"
// and both INSERT.
//
// DO UPDATE touches non-key columns only, so the row lock taken is FOR NO
// KEY UPDATE — safe vs concurrent FK FOR KEY SHARE locks held by
// host_packages inserts pointing at this row.
//
// Repository rows are shared across the whole fleet: every host on a distro
// reports the same (url, distribution, components). Running this statement on
// every report takes a FOR NO KEY UPDATE lock on ONE hot row and holds it
// until the report transaction commits — which is after that transaction's
// full host_packages delete and bulk insert. Contention scales with fleet
// concurrency, not with the handful of repository rows per host, so at 64
// concurrent reports they serialise behind the hot row until statement_timeout.
//
// The skip-no-op WHERE below does NOT prevent that lock. PostgreSQL's
// ON CONFLICT arbiter locks the conflicting tuple BEFORE it evaluates the
// DO UPDATE WHERE, so a skipped no-op still holds the row lock to end of
// transaction (verified: holder reports INSERT 0 0 while a concurrent
// FOR NO KEY UPDATE on the same row blocks). The WHERE earns its keep by
// avoiding the heap write, dead tuple and WAL when two reports race on the
// same genuine change — not by avoiding locks.
//
// Avoiding the lock is therefore the CALLER's job: upsertRepositoryResolvingID
// reads the row first (a plain SELECT takes no lock) and only reaches this
// statement when the row is absent or a column it would set actually differs.
// Do not "simplify" the caller back to calling this unconditionally.
//
// Consequence of the WHERE: RETURNING is NOT always populated. A skipped
// no-op returns zero rows and this is a :one query, so the caller gets
// pgx.ErrNoRows and MUST resolve the id via GetRepositoryByURLDistComponents.
// Do NOT "fix" this with a same-statement fallback SELECT — both halves would
// read at the same statement snapshot and miss rows a concurrent transaction
// committed after the statement began.
func (q *Queries) UpsertRepository(ctx context.Context, arg UpsertRepositoryParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertRepository,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.Distribution,
		arg.Components,
		arg.RepoType,
		arg.IsActive,
		arg.IsSecure,
		arg.Priority,
		arg.Description,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
