// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFirstSettings = `-- name: GetFirstSettings :one
SELECT id, server_url, server_protocol, server_host, server_port, created_at, updated_at, update_interval, auto_update, default_compliance_mode, compliance_scan_interval, package_cache_refresh_mode, package_cache_refresh_max_age, github_repo_url, ssh_key_path, repository_type, last_update_check, latest_version, update_available, signup_enabled, default_user_role, ignore_ssl_self_signed, logo_dark, logo_light, favicon, logo_dark_data, logo_light_data, favicon_data, logo_dark_content_type, logo_light_content_type, favicon_content_type, metrics_enabled, metrics_anonymous_id, metrics_last_sent, show_github_version_on_login, ai_enabled, ai_provider, ai_model, ai_api_key, alerts_enabled, discord_oauth_enabled, discord_client_id, discord_client_secret, discord_redirect_uri, discord_button_text, oidc_enabled, oidc_issuer_url, oidc_client_id, oidc_client_secret, oidc_redirect_uri, oidc_scopes, oidc_auto_create_users, oidc_default_role, oidc_disable_local_auth, oidc_button_text, oidc_sync_roles, oidc_admin_group, oidc_superadmin_group, oidc_host_manager_group, oidc_readonly_group, oidc_user_group, oidc_enforce_https, max_login_attempts, lockout_duration_minutes, session_inactivity_timeout_minutes, patch_run_stall_timeout_minutes, agent_reports_retention_days, tfa_max_remember_sessions, password_min_length, password_require_uppercase, password_require_lowercase, password_require_number, password_require_special, enable_hsts, json_body_limit, agent_update_body_limit, db_transaction_long_timeout, cors_origin, enable_logging, log_level, timezone, jwt_expires_in, max_tfa_attempts, tfa_lockout_duration_minutes, tfa_remember_me_expires_in, trust_proxy, rate_limit_window_ms, rate_limit_max, auth_rate_limit_window_ms, auth_rate_limit_max, agent_rate_limit_window_ms, agent_rate_limit_max, password_rate_limit_window_ms, password_rate_limit_max, auth_browser_session_cookies FROM settings LIMIT 1
`

func (q *Queries) GetFirstSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRow(ctx, getFirstSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.ServerUrl,
		&i.ServerProtocol,
		&i.ServerHost,
		&i.ServerPort,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdateInterval,
		&i.AutoUpdate,
		&i.DefaultComplianceMode,
		&i.ComplianceScanInterval,
		&i.PackageCacheRefreshMode,
		&i.PackageCacheRefreshMaxAge,
		&i.GithubRepoUrl,
		&i.SshKeyPath,
		&i.RepositoryType,
		&i.LastUpdateCheck,
		&i.LatestVersion,
		&i.UpdateAvailable,
		&i.SignupEnabled,
		&i.DefaultUserRole,
		&i.IgnoreSslSelfSigned,
		&i.LogoDark,
		&i.LogoLight,
		&i.Favicon,
		&i.LogoDarkData,
		&i.LogoLightData,
		&i.FaviconData,
		&i.LogoDarkContentType,
		&i.LogoLightContentType,
		&i.FaviconContentType,
		&i.MetricsEnabled,
		&i.MetricsAnonymousID,
		&i.MetricsLastSent,
		&i.ShowGithubVersionOnLogin,
		&i.AiEnabled,
		&i.AiProvider,
		&i.AiModel,
		&i.AiApiKey,
		&i.AlertsEnabled,
		&i.DiscordOauthEnabled,
		&i.DiscordClientID,
		&i.DiscordClientSecret,
		&i.DiscordRedirectUri,
		&i.DiscordButtonText,
		&i.OidcEnabled,
		&i.OidcIssuerUrl,
		&i.OidcClientID,
		&i.OidcClientSecret,
		&i.OidcRedirectUri,
		&i.OidcScopes,
		&i.OidcAutoCreateUsers,
		&i.OidcDefaultRole,
		&i.OidcDisableLocalAuth,
		&i.OidcButtonText,
		&i.OidcSyncRoles,
		&i.OidcAdminGroup,
		&i.OidcSuperadminGroup,
		&i.OidcHostManagerGroup,
		&i.OidcReadonlyGroup,
		&i.OidcUserGroup,
		&i.OidcEnforceHttps,
		&i.MaxLoginAttempts,
		&i.LockoutDurationMinutes,
		&i.SessionInactivityTimeoutMinutes,
		&i.PatchRunStallTimeoutMinutes,
		&i.AgentReportsRetentionDays,
		&i.TfaMaxRememberSessions,
		&i.PasswordMinLength,
		&i.PasswordRequireUppercase,
		&i.PasswordRequireLowercase,
		&i.PasswordRequireNumber,
		&i.PasswordRequireSpecial,
		&i.EnableHsts,
		&i.JsonBodyLimit,
		&i.AgentUpdateBodyLimit,
		&i.DbTransactionLongTimeout,
		&i.CorsOrigin,
		&i.EnableLogging,
		&i.LogLevel,
		&i.Timezone,
		&i.JwtExpiresIn,
		&i.MaxTfaAttempts,
		&i.TfaLockoutDurationMinutes,
		&i.TfaRememberMeExpiresIn,
		&i.TrustProxy,
		&i.RateLimitWindowMs,
		&i.RateLimitMax,
		&i.AuthRateLimitWindowMs,
		&i.AuthRateLimitMax,
		&i.AgentRateLimitWindowMs,
		&i.AgentRateLimitMax,
		&i.PasswordRateLimitWindowMs,
		&i.PasswordRateLimitMax,
		&i.AuthBrowserSessionCookies,
	)
	return i, err
}

const updateSettings = `-- name: UpdateSettings :exec
UPDATE settings SET
    server_url = $1,
    server_protocol = $2,
    server_host = $3,
    server_port = $4,
    updated_at = NOW(),
    update_interval = $5,
    auto_update = $6,
    default_compliance_mode = $7,
    github_repo_url = $8,
    ssh_key_path = $9,
    repository_type = $10,
    last_update_check = $11,
    latest_version = $12,
    update_available = $13,
    signup_enabled = $14,
    default_user_role = $15,
    ignore_ssl_self_signed = $16,
    logo_dark = $17,
    logo_light = $18,
    favicon = $19,
    metrics_enabled = $20,
    metrics_anonymous_id = $21,
    metrics_last_sent = $22,
    show_github_version_on_login = $23,
    ai_enabled = $24,
    ai_provider = $25,
    ai_model = $26,
    ai_api_key = $27,
    alerts_enabled = $28,
    discord_oauth_enabled = $29,
    discord_client_id = $30,
    discord_client_secret = $31,
    discord_redirect_uri = $32,
    discord_button_text = $33,
    oidc_enabled = $34,
    oidc_issuer_url = $35,
    oidc_client_id = $36,
    oidc_client_secret = $37,
    oidc_redirect_uri = $38,
    oidc_scopes = $39,
    oidc_auto_create_users = $40,
    oidc_default_role = $41,
    oidc_disable_local_auth = $42,
    oidc_button_text = $43,
    oidc_sync_roles = $44,
    oidc_admin_group = $45,
    oidc_superadmin_group = $46,
    oidc_host_manager_group = $47,
    oidc_readonly_group = $48,
    oidc_user_group = $49,
    oidc_enforce_https = $50,
    logo_dark_data = $51,
    logo_light_data = $52,
    favicon_data = $53,
    logo_dark_content_type = $54,
    logo_light_content_type = $55,
    favicon_content_type = $56,
    compliance_scan_interval = $57,
    package_cache_refresh_mode = $58,
    package_cache_refresh_max_age = $59
WHERE id = $60
`

type UpdateSettingsParams struct {
	ServerUrl                 string           `json:"server_url"`
	ServerProtocol            string           `json:"server_protocol"`
	ServerHost                string           `json:"server_host"`
	ServerPort                int32            `json:"server_port"`
	UpdateInterval            int32            `json:"update_interval"`
	AutoUpdate                bool             `json:"auto_update"`
	DefaultComplianceMode     string           `json:"default_compliance_mode"`
	GithubRepoUrl             string           `json:"github_repo_url"`
	SshKeyPath                *string          `json:"ssh_key_path"`
	RepositoryType            string           `json:"repository_type"`
	LastUpdateCheck           pgtype.Timestamp `json:"last_update_check"`
	LatestVersion             *string          `json:"latest_version"`
	UpdateAvailable           bool             `json:"update_available"`
	SignupEnabled             bool             `json:"signup_enabled"`
	DefaultUserRole           string           `json:"default_user_role"`
	IgnoreSslSelfSigned       bool             `json:"ignore_ssl_self_signed"`
	LogoDark                  *string          `json:"logo_dark"`
	LogoLight                 *string          `json:"logo_light"`
	Favicon                   *string          `json:"favicon"`
	MetricsEnabled            bool             `json:"metrics_enabled"`
	MetricsAnonymousID        *string          `json:"metrics_anonymous_id"`
	MetricsLastSent           pgtype.Timestamp `json:"metrics_last_sent"`
	ShowGithubVersionOnLogin  bool             `json:"show_github_version_on_login"`
	AiEnabled                 bool             `json:"ai_enabled"`
	AiProvider                string           `json:"ai_provider"`
	AiModel                   *string          `json:"ai_model"`
	AiApiKey                  *string          `json:"ai_api_key"`
	AlertsEnabled             bool             `json:"alerts_enabled"`
	DiscordOauthEnabled       bool             `json:"discord_oauth_enabled"`
	DiscordClientID           *string          `json:"discord_client_id"`
	DiscordClientSecret       *string          `json:"discord_client_secret"`
	DiscordRedirectUri        *string          `json:"discord_redirect_uri"`
	DiscordButtonText         *string          `json:"discord_button_text"`
	OidcEnabled               bool             `json:"oidc_enabled"`
	OidcIssuerUrl             *string          `json:"oidc_issuer_url"`
	OidcClientID              *string          `json:"oidc_client_id"`
	OidcClientSecret          *string          `json:"oidc_client_secret"`
	OidcRedirectUri           *string          `json:"oidc_redirect_uri"`
	OidcScopes                *string          `json:"oidc_scopes"`
	OidcAutoCreateUsers       bool             `json:"oidc_auto_create_users"`
	OidcDefaultRole           *string          `json:"oidc_default_role"`
	OidcDisableLocalAuth      bool             `json:"oidc_disable_local_auth"`
	OidcButtonText            *string          `json:"oidc_button_text"`
	OidcSyncRoles             bool             `json:"oidc_sync_roles"`
	OidcAdminGroup            *string          `json:"oidc_admin_group"`
	OidcSuperadminGroup       *string          `json:"oidc_superadmin_group"`
	OidcHostManagerGroup      *string          `json:"oidc_host_manager_group"`
	OidcReadonlyGroup         *string          `json:"oidc_readonly_group"`
	OidcUserGroup             *string          `json:"oidc_user_group"`
	OidcEnforceHttps          bool             `json:"oidc_enforce_https"`
	LogoDarkData              []byte           `json:"logo_dark_data"`
	LogoLightData             []byte           `json:"logo_light_data"`
	FaviconData               []byte           `json:"favicon_data"`
	LogoDarkContentType       *string          `json:"logo_dark_content_type"`
	LogoLightContentType      *string          `json:"logo_light_content_type"`
	FaviconContentType        *string          `json:"favicon_content_type"`
	ComplianceScanInterval    int32            `json:"compliance_scan_interval"`
	PackageCacheRefreshMode   string           `json:"package_cache_refresh_mode"`
	PackageCacheRefreshMaxAge int32            `json:"package_cache_refresh_max_age"`
	ID                        string           `json:"id"`
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) error {
	_, err := q.db.Exec(ctx, updateSettings,
		arg.ServerUrl,
		arg.ServerProtocol,
		arg.ServerHost,
		arg.ServerPort,
		arg.UpdateInterval,
		arg.AutoUpdate,
		arg.DefaultComplianceMode,
		arg.GithubRepoUrl,
		arg.SshKeyPath,
		arg.RepositoryType,
		arg.LastUpdateCheck,
		arg.LatestVersion,
		arg.UpdateAvailable,
		arg.SignupEnabled,
		arg.DefaultUserRole,
		arg.IgnoreSslSelfSigned,
		arg.LogoDark,
		arg.LogoLight,
		arg.Favicon,
		arg.MetricsEnabled,
		arg.MetricsAnonymousID,
		arg.MetricsLastSent,
		arg.ShowGithubVersionOnLogin,
		arg.AiEnabled,
		arg.AiProvider,
		arg.AiModel,
		arg.AiApiKey,
		arg.AlertsEnabled,
		arg.DiscordOauthEnabled,
		arg.DiscordClientID,
		arg.DiscordClientSecret,
		arg.DiscordRedirectUri,
		arg.DiscordButtonText,
		arg.OidcEnabled,
		arg.OidcIssuerUrl,
		arg.OidcClientID,
		arg.OidcClientSecret,
		arg.OidcRedirectUri,
		arg.OidcScopes,
		arg.OidcAutoCreateUsers,
		arg.OidcDefaultRole,
		arg.OidcDisableLocalAuth,
		arg.OidcButtonText,
		arg.OidcSyncRoles,
		arg.OidcAdminGroup,
		arg.OidcSuperadminGroup,
		arg.OidcHostManagerGroup,
		arg.OidcReadonlyGroup,
		arg.OidcUserGroup,
		arg.OidcEnforceHttps,
		arg.LogoDarkData,
		arg.LogoLightData,
		arg.FaviconData,
		arg.LogoDarkContentType,
		arg.LogoLightContentType,
		arg.FaviconContentType,
		arg.ComplianceScanInterval,
		arg.PackageCacheRefreshMode,
		arg.PackageCacheRefreshMaxAge,
		arg.ID,
	)
	return err
}

const updateSettingsConfig = `-- name: UpdateSettingsConfig :exec
UPDATE settings SET
    updated_at = NOW(),
    max_login_attempts = COALESCE($1, max_login_attempts),
    lockout_duration_minutes = COALESCE($2, lockout_duration_minutes),
    session_inactivity_timeout_minutes = COALESCE($3, session_inactivity_timeout_minutes),
    tfa_max_remember_sessions = COALESCE($4, tfa_max_remember_sessions),
    password_min_length = COALESCE($5, password_min_length),
    password_require_uppercase = COALESCE($6, password_require_uppercase),
    password_require_lowercase = COALESCE($7, password_require_lowercase),
    password_require_number = COALESCE($8, password_require_number),
    password_require_special = COALESCE($9, password_require_special),
    enable_hsts = COALESCE($10, enable_hsts),
    json_body_limit = COALESCE($11, json_body_limit),
    agent_update_body_limit = COALESCE($12, agent_update_body_limit),
    db_transaction_long_timeout = COALESCE($13, db_transaction_long_timeout),
    cors_origin = COALESCE($14, cors_origin),
    enable_logging = COALESCE($15, enable_logging),
    log_level = COALESCE($16, log_level),
    timezone = COALESCE($17, timezone),
    jwt_expires_in = COALESCE($18, jwt_expires_in),
    max_tfa_attempts = COALESCE($19, max_tfa_attempts),
    tfa_lockout_duration_minutes = COALESCE($20, tfa_lockout_duration_minutes),
    tfa_remember_me_expires_in = COALESCE($21, tfa_remember_me_expires_in),
    default_user_role = COALESCE($22, default_user_role),
    trust_proxy = COALESCE($23, trust_proxy),
    rate_limit_window_ms = COALESCE($24, rate_limit_window_ms),
    rate_limit_max = COALESCE($25, rate_limit_max),
    auth_rate_limit_window_ms = COALESCE($26, auth_rate_limit_window_ms),
    auth_rate_limit_max = COALESCE($27, auth_rate_limit_max),
    agent_rate_limit_window_ms = COALESCE($28, agent_rate_limit_window_ms),
    agent_rate_limit_max = COALESCE($29, agent_rate_limit_max),
    password_rate_limit_window_ms = COALESCE($30, password_rate_limit_window_ms),
    password_rate_limit_max = COALESCE($31, password_rate_limit_max),
    auth_browser_session_cookies = COALESCE($32, auth_browser_session_cookies),
    patch_run_stall_timeout_minutes = COALESCE($33, patch_run_stall_timeout_minutes),
    agent_reports_retention_days = COALESCE($34, agent_reports_retention_days)
WHERE id = $35
`

type UpdateSettingsConfigParams struct {
	MaxLoginAttempts                *int32  `json:"max_login_attempts"`
	LockoutDurationMinutes          *int32  `json:"lockout_duration_minutes"`
	SessionInactivityTimeoutMinutes *int32  `json:"session_inactivity_timeout_minutes"`
	TfaMaxRememberSessions          *int32  `json:"tfa_max_remember_sessions"`
	PasswordMinLength               *int32  `json:"password_min_length"`
	PasswordRequireUppercase        *bool   `json:"password_require_uppercase"`
	PasswordRequireLowercase        *bool   `json:"password_require_lowercase"`
	PasswordRequireNumber           *bool   `json:"password_require_number"`
	PasswordRequireSpecial          *bool   `json:"password_require_special"`
	EnableHsts                      *bool   `json:"enable_hsts"`
	JsonBodyLimit                   *string `json:"json_body_limit"`
	AgentUpdateBodyLimit            *string `json:"agent_update_body_limit"`
	DbTransactionLongTimeout        *int32  `json:"db_transaction_long_timeout"`
	CorsOrigin                      *string `json:"cors_origin"`
	EnableLogging                   *bool   `json:"enable_logging"`
	LogLevel                        *string `json:"log_level"`
	Timezone                        *string `json:"timezone"`
	JwtExpiresIn                    *string `json:"jwt_expires_in"`
	MaxTfaAttempts                  *int32  `json:"max_tfa_attempts"`
	TfaLockoutDurationMinutes       *int32  `json:"tfa_lockout_duration_minutes"`
	TfaRememberMeExpiresIn          *string `json:"tfa_remember_me_expires_in"`
	DefaultUserRole                 string  `json:"default_user_role"`
	TrustProxy                      *bool   `json:"trust_proxy"`
	RateLimitWindowMs               *int32  `json:"rate_limit_window_ms"`
	RateLimitMax                    *int32  `json:"rate_limit_max"`
	AuthRateLimitWindowMs           *int32  `json:"auth_rate_limit_window_ms"`
	AuthRateLimitMax                *int32  `json:"auth_rate_limit_max"`
	AgentRateLimitWindowMs          *int32  `json:"agent_rate_limit_window_ms"`
	AgentRateLimitMax               *int32  `json:"agent_rate_limit_max"`
	PasswordRateLimitWindowMs       *int32  `json:"password_rate_limit_window_ms"`
	PasswordRateLimitMax            *int32  `json:"password_rate_limit_max"`
	AuthBrowserSessionCookies       *bool   `json:"auth_browser_session_cookies"`
	PatchRunStallTimeoutMinutes     *int32  `json:"patch_run_stall_timeout_minutes"`
	AgentReportsRetentionDays       *int32  `json:"agent_reports_retention_days"`
	ID                              string  `json:"id"`
}

func (q *Queries) UpdateSettingsConfig(ctx context.Context, arg UpdateSettingsConfigParams) error {
	_, err := q.db.Exec(ctx, updateSettingsConfig,
		arg.MaxLoginAttempts,
		arg.LockoutDurationMinutes,
		arg.SessionInactivityTimeoutMinutes,
		arg.TfaMaxRememberSessions,
		arg.PasswordMinLength,
		arg.PasswordRequireUppercase,
		arg.PasswordRequireLowercase,
		arg.PasswordRequireNumber,
		arg.PasswordRequireSpecial,
		arg.EnableHsts,
		arg.JsonBodyLimit,
		arg.AgentUpdateBodyLimit,
		arg.DbTransactionLongTimeout,
		arg.CorsOrigin,
		arg.EnableLogging,
		arg.LogLevel,
		arg.Timezone,
		arg.JwtExpiresIn,
		arg.MaxTfaAttempts,
		arg.TfaLockoutDurationMinutes,
		arg.TfaRememberMeExpiresIn,
		arg.DefaultUserRole,
		arg.TrustProxy,
		arg.RateLimitWindowMs,
		arg.RateLimitMax,
		arg.AuthRateLimitWindowMs,
		arg.AuthRateLimitMax,
		arg.AgentRateLimitWindowMs,
		arg.AgentRateLimitMax,
		arg.PasswordRateLimitWindowMs,
		arg.PasswordRateLimitMax,
		arg.AuthBrowserSessionCookies,
		arg.PatchRunStallTimeoutMinutes,
		arg.AgentReportsRetentionDays,
		arg.ID,
	)
	return err
}
