// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_api_tokens.sql

package db

import (
	"context"
	"time"
)

const listUserApiTokens = `-- name: ListUserApiTokens :many
SELECT id, name, created_at, expires_at, last_used_at
FROM user_api_tokens
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListUserApiTokensRow struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	CreatedAt   time.Time  `json:"created_at"`
	ExpiresAt   *time.Time `json:"expires_at"`
	LastUsedAt  *time.Time `json:"last_used_at"`
}

func (q *Queries) ListUserApiTokens(ctx context.Context, userID string) ([]ListUserApiTokensRow, error) {
	rows, err := q.db.Query(ctx, listUserApiTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserApiTokensRow
	for rows.Next() {
		var i ListUserApiTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserApiTokenByHash = `-- name: GetUserApiTokenByHash :one
SELECT t.id, t.user_id, t.name, t.token_hash, t.created_at, t.expires_at, t.last_used_at,
       u.id AS u_id, u.username AS u_username, u.email AS u_email,
       u.role AS u_role, u.is_active AS u_is_active
FROM user_api_tokens t
JOIN users u ON u.id = t.user_id
WHERE t.token_hash = $1
`

type GetUserApiTokenByHashRow struct {
	ID          string     `json:"id"`
	UserID      string     `json:"user_id"`
	Name        string     `json:"name"`
	TokenHash   string     `json:"token_hash"`
	CreatedAt   time.Time  `json:"created_at"`
	ExpiresAt   *time.Time `json:"expires_at"`
	LastUsedAt  *time.Time `json:"last_used_at"`
	UId         string     `json:"u_id"`
	UUsername   string     `json:"u_username"`
	UEmail      string     `json:"u_email"`
	URole       string     `json:"u_role"`
	UIsActive   bool       `json:"u_is_active"`
}

func (q *Queries) GetUserApiTokenByHash(ctx context.Context, tokenHash string) (GetUserApiTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getUserApiTokenByHash, tokenHash)
	var i GetUserApiTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.UId,
		&i.UUsername,
		&i.UEmail,
		&i.URole,
		&i.UIsActive,
	)
	return i, err
}

const createUserApiToken = `-- name: CreateUserApiToken :one
INSERT INTO user_api_tokens (id, user_id, name, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, created_at, expires_at, last_used_at
`

type CreateUserApiTokenParams struct {
	ID        string     `json:"id"`
	UserID    string     `json:"user_id"`
	Name      string     `json:"name"`
	TokenHash string     `json:"token_hash"`
	ExpiresAt *time.Time `json:"expires_at"`
}

func (q *Queries) CreateUserApiToken(ctx context.Context, arg CreateUserApiTokenParams) (ListUserApiTokensRow, error) {
	row := q.db.QueryRow(ctx, createUserApiToken,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i ListUserApiTokensRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteUserApiToken = `-- name: DeleteUserApiToken :exec
DELETE FROM user_api_tokens WHERE id = $1
`

func (q *Queries) DeleteUserApiToken(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUserApiToken, id)
	return err
}

const updateUserApiTokenLastUsed = `-- name: UpdateUserApiTokenLastUsed :exec
UPDATE user_api_tokens SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateUserApiTokenLastUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateUserApiTokenLastUsed, id)
	return err
}
